/**
 * Pulls Turkish recipes from TheMealDB (https://www.themealdb.com) — a
 * public JSON API with no auth and a permissive usage policy for dev.
 *
 * Writes to: packages/recipe-db/src/seed/external-themealdb.ts
 *
 * The resulting seed is NOT auto-wired into src/index.ts — it is kept
 * out-of-band so curated seeds stay the primary source. To include it:
 *   1) import `themealdbTurkish` in src/index.ts
 *   2) append it to the `seeds` array
 *   3) run `pnpm --filter @fittrack/recipe-db build:json`
 *
 * Run with: pnpm --filter @fittrack/recipe-db sync
 *
 * Known bigger datasets we considered but still need human vetting:
 *   - HuggingFace `mertbozkurt/Turkish_recipes` (thousands of rows, license TBD)
 *   - Kaggle Turkish-recipes CSVs (per-dataset licenses, quality varies)
 * Tell us the URL once you pick one and we'll wire a normalizer.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Recipe } from '@fittrack/shared';

const AREA = 'Turkish';
const LIST_URL = `https://www.themealdb.com/api/json/v1/1/filter.php?a=${AREA}`;
const LOOKUP_URL = (id: string) =>
  `https://www.themealdb.com/api/json/v1/1/lookup.php?i=${id}`;

interface MealSummary {
  idMeal: string;
  strMeal: string;
}
interface MealDetail {
  idMeal: string;
  strMeal: string;
  strInstructions: string;
  strCategory: string | null;
  [key: string]: string | null;
}

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}: ${url}`);
  return res.json() as Promise<T>;
}

function toSlug(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function pickIngredients(detail: MealDetail): Recipe['ingredients'] {
  const out: Recipe['ingredients'] = [];
  for (let i = 1; i <= 20; i++) {
    const name = (detail[`strIngredient${i}`] ?? '').trim();
    const measure = (detail[`strMeasure${i}`] ?? '').trim();
    if (!name) continue;
    out.push({ name, amount: measure || '—' });
  }
  return out;
}

function splitSteps(raw: string): string[] {
  return raw
    .split(/\r?\n+/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
}

function guessCategory(cat: string | null): Recipe['category'] {
  const c = (cat ?? '').toLowerCase();
  if (c.includes('dessert')) return 'dessert';
  if (c.includes('side')) return 'main_veg';
  if (c.includes('pasta')) return 'pasta';
  if (c.includes('starter') || c.includes('soup')) return 'soup';
  return 'main_meat';
}

async function main(): Promise<void> {
  const { meals } = await fetchJson<{ meals: MealSummary[] }>(LIST_URL);
  if (!meals?.length) {
    console.error('No Turkish meals returned from TheMealDB.');
    process.exit(1);
  }
  console.log(`Found ${meals.length} Turkish meals, fetching details…`);

  const recipes: Recipe[] = [];
  for (const m of meals) {
    try {
      const detail = await fetchJson<{ meals: MealDetail[] }>(LOOKUP_URL(m.idMeal));
      const d = detail.meals?.[0];
      if (!d) continue;
      const steps = splitSteps(d.strInstructions ?? '');
      if (steps.length === 0) continue;
      recipes.push({
        id: `themealdb-${toSlug(d.strMeal)}`,
        nameTr: d.strMeal,
        nameEn: d.strMeal,
        category: guessCategory(d.strCategory),
        cuisine: 'turkish',
        servings: 4,
        prepMinutes: 15,
        cookMinutes: 30,
        difficulty: 'medium',
        tags: ['themealdb'],
        ingredients: pickIngredients(d),
        steps,
        source: `TheMealDB #${d.idMeal}`,
      });
    } catch (err) {
      console.warn(`skip ${m.strMeal}: ${err}`);
    }
  }

  const fileBody = `import type { RecipeSeed } from './_types.js';

// Auto-generated by scripts/fetch-open.ts — do not hand-edit.
// Run \`pnpm --filter @fittrack/recipe-db sync\` to refresh.
export const themealdbTurkish: RecipeSeed[] = ${JSON.stringify(recipes, null, 2)};
`;

  const here = fileURLToPath(new URL('.', import.meta.url));
  const out = resolve(here, '../src/seed/external-themealdb.ts');
  writeFileSync(out, fileBody, 'utf8');
  console.log(`wrote ${recipes.length} recipes → ${out}`);
  console.log('Next: import & spread `themealdbTurkish` in src/index.ts if you want them live.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
