import type { RecipeSeed } from './_types.js';

export const breakfast: RecipeSeed[] = [
  {
    id: 'menemen',
    nameTr: 'Menemen',
    nameEn: 'Turkish Scrambled Eggs with Tomato',
    category: 'breakfast',
    cuisine: 'turkish',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 15,
    difficulty: 'easy',
    tags: ['vegetarian', 'quick', 'student_friendly', 'high_protein'],
    ingredients: [
      { name: 'Yumurta', amount: '4 adet' },
      { name: 'Olgun domates', amount: '3 adet' },
      { name: 'Yeşil sivri biber', amount: '3 adet' },
      { name: 'Zeytinyağı veya tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Biberleri ince doğrayın; domatesleri soyup küçük küpler halinde kesin.',
      'Tavada yağı ısıtın, biberleri 2-3 dakika soteleyin.',
      'Domatesleri ekleyin; suyunu bırakıp çekene dek 6-7 dakika pişirin.',
      'Tuz, karabiber, pul biber ekleyin.',
      'Yumurtaları ekleyip hafifçe karıştırın; tercihinize göre dağılmadan ya da karıştırarak pişirin.',
      'Sıcak ekmekle servis edin.',
    ],
    nutritionPerServing: { kcal: 340, proteinG: 18, carbsG: 10, fatG: 26 },
  },
  {
    id: 'sucuklu-yumurta',
    nameTr: 'Sucuklu Yumurta',
    nameEn: 'Eggs with Turkish Sausage',
    category: 'breakfast',
    cuisine: 'turkish',
    servings: 2,
    prepMinutes: 2,
    cookMinutes: 8,
    difficulty: 'easy',
    tags: ['quick', 'high_protein', 'student_friendly'],
    ingredients: [
      { name: 'Sucuk', amount: '8 dilim' },
      { name: 'Yumurta', amount: '4 adet' },
      { name: 'Tereyağı (opsiyonel)', amount: '1 yemek kaşığı' },
      { name: 'Karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Tavayı orta ateşte ısıtın; sucukları yağsız atın.',
      'Her iki yüzünü 1 dakika kızartın (yağını bırakır).',
      'Tereyağını ekleyin, sonra yumurtaları sucukların aralarına kırın.',
      'Sarılar akışkan kalacak şekilde 2-3 dakika pişirin.',
      'Karabiber serpip tavadan servis edin.',
    ],
    nutritionPerServing: { kcal: 450, proteinG: 24, carbsG: 3, fatG: 38 },
  },
  {
    id: 'omlet',
    nameTr: 'Peynirli Omlet',
    nameEn: 'Cheese Omelette',
    category: 'breakfast',
    cuisine: 'turkish',
    servings: 1,
    prepMinutes: 3,
    cookMinutes: 5,
    difficulty: 'easy',
    tags: ['quick', 'student_friendly', 'high_protein', 'vegetarian'],
    ingredients: [
      { name: 'Yumurta', amount: '3 adet' },
      { name: 'Beyaz peynir (veya kaşar)', amount: '40 g' },
      { name: 'Süt', amount: '1 yemek kaşığı' },
      { name: 'Tereyağı', amount: '1 yemek kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Maydanoz (opsiyonel)', amount: '1 dal' },
    ],
    steps: [
      'Yumurtaları süt, tuz ve karabiberle çırpın.',
      'Kısık ateşte tereyağını tavada eritin.',
      'Yumurtaları dökün; kenarları tutmaya başlayınca ortasına peyniri yerleştirin.',
      'İkiye katlayıp 30 saniye daha pişirin.',
      'Maydanoz serperek servis edin.',
    ],
    nutritionPerServing: { kcal: 380, proteinG: 26, carbsG: 3, fatG: 30 },
  },
  {
    id: 'cilbir',
    nameTr: 'Çılbır (Yoğurtlu Yumurta)',
    nameEn: 'Çılbır (Poached Eggs on Yogurt)',
    category: 'breakfast',
    cuisine: 'turkish',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 8,
    difficulty: 'medium',
    tags: ['traditional', 'high_protein', 'vegetarian'],
    ingredients: [
      { name: 'Yumurta', amount: '4 adet' },
      { name: 'Süzme yoğurt', amount: '2 su bardağı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Pul biber', amount: '1 tatlı kaşığı' },
      { name: 'Kuru nane', amount: '1 çay kaşığı' },
      { name: 'Sirke', amount: '1 yemek kaşığı' },
      { name: 'Tuz', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Yoğurdu oda sıcaklığına getirin; ezilmiş sarımsak ve tuzu karıştırın.',
      'Yumurtaları tek tek küçük kâselere kırın.',
      'Tencerede su ile sirkeyi kaynatın; kısık ateşte girdap oluşturup yumurtaları yavaşça bırakın.',
      '3 dakika kadar pişirip kevgirle alın; kurulayın.',
      'Tabakta yoğurdun üstüne yumurtaları yerleştirin.',
      'Tavada tereyağını eritin; pul biber ve naneyi 15 saniye kavurun.',
      'Acılı yağı üstlerine gezdirin.',
    ],
    nutritionPerServing: { kcal: 430, proteinG: 25, carbsG: 10, fatG: 32 },
  },
  {
    id: 'pancake',
    nameTr: 'Yulaflı Pankek',
    nameEn: 'Oat Pancakes',
    category: 'breakfast',
    cuisine: 'international',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 10,
    difficulty: 'easy',
    tags: ['healthy', 'quick', 'student_friendly', 'high_protein', 'vegetarian'],
    ingredients: [
      { name: 'Yulaf ezmesi', amount: '1 su bardağı' },
      { name: 'Yumurta', amount: '2 adet' },
      { name: 'Muz (olgun)', amount: '1 adet' },
      { name: 'Süt', amount: 'yarım su bardağı' },
      { name: 'Kabartma tozu', amount: '1 çay kaşığı' },
      { name: 'Vanilya (opsiyonel)', amount: '1 tutam' },
      { name: 'Tereyağı (tava için)', amount: 'yeterince' },
    ],
    steps: [
      'Tüm malzemeleri blenderdan geçirip pürüzsüz hamur elde edin.',
      'Tavayı kısık ateşte ısıtıp az yağlayın.',
      'Her biri için 1 kepçe hamur dökün; kabarcıklar çıkınca çevirin.',
      'Her yüzü 1,5-2 dakika pişirin.',
      'Üzerine bal, süzme peynir veya meyve ile servis edin.',
    ],
    nutritionPerServing: { kcal: 300, proteinG: 14, carbsG: 40, fatG: 9 },
  },
  {
    id: 'haslanmis-yumurta-kahvaltisi',
    nameTr: 'Klasik Türk Kahvaltı Tabağı',
    nameEn: 'Turkish Breakfast Plate',
    category: 'breakfast',
    cuisine: 'turkish',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 10,
    difficulty: 'easy',
    tags: ['traditional', 'vegetarian'],
    ingredients: [
      { name: 'Yumurta (haşlama)', amount: '2 adet' },
      { name: 'Beyaz peynir', amount: '100 g' },
      { name: 'Kaşar peyniri', amount: '80 g' },
      { name: 'Siyah zeytin', amount: 'yarım çay bardağı' },
      { name: 'Yeşil zeytin', amount: 'yarım çay bardağı' },
      { name: 'Domates, salatalık', amount: '1\'er adet' },
      { name: 'Taze ekmek', amount: 'yeterince' },
      { name: 'Bal veya reçel', amount: '2 yemek kaşığı' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
    ],
    steps: [
      'Yumurtaları kaynar suda 7-8 dakika haşlayın; soğuk suya alıp soyun.',
      'Domates ve salatalığı dilimleyin.',
      'Peynirleri ve zeytinleri küçük tabaklara ayırın.',
      'Bal/reçel ile tereyağını yanına koyup ekmekle servis edin.',
      'Demli siyah çay eşliğinde sunun.',
    ],
    nutritionPerServing: { kcal: 560, proteinG: 26, carbsG: 35, fatG: 34 },
  },
  {
    id: 'simit-tabagi',
    nameTr: 'Hızlı Simit Kahvaltısı',
    nameEn: 'Simit Breakfast',
    category: 'breakfast',
    cuisine: 'turkish',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['quick', 'student_friendly'],
    ingredients: [
      { name: 'Simit', amount: '2 adet' },
      { name: 'Krem peynir veya labne', amount: '4 yemek kaşığı' },
      { name: 'Domates', amount: '1 adet' },
      { name: 'Salatalık', amount: '1 adet' },
      { name: 'Zeytin', amount: '1 çay bardağı' },
      { name: 'Roka', amount: '1 avuç' },
    ],
    steps: [
      'Simidi enlemesine ikiye bölün.',
      'İç kısımlarına bolca labne sürün.',
      'Üzerine domates, salatalık dilimleri ve roka yerleştirin.',
      'Kenarlarına zeytin koyarak servis edin.',
    ],
    nutritionPerServing: { kcal: 450, proteinG: 14, carbsG: 65, fatG: 14 },
  },
  {
    id: 'avokadolu-tost',
    nameTr: 'Avokadolu Tost',
    nameEn: 'Avocado Toast',
    category: 'breakfast',
    cuisine: 'international',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 4,
    difficulty: 'easy',
    tags: ['healthy', 'quick', 'student_friendly', 'vegetarian'],
    ingredients: [
      { name: 'Tam buğday ekmeği', amount: '4 dilim' },
      { name: 'Olgun avokado', amount: '1 adet' },
      { name: 'Limon suyu', amount: '1 tatlı kaşığı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Yumurta (sahanda)', amount: '2 adet' },
      { name: 'Cherry domates', amount: '5 adet' },
    ],
    steps: [
      'Ekmekleri tostlayın.',
      'Avokadoyu çatalla ezip tuz, karabiber ve limon ekleyin.',
      'Ezmeyi ekmeklere sürün.',
      'Üzerine sahanda yumurta ve ikiye kesilmiş cherry domatesleri koyun.',
      'Pul biber serperek servis edin.',
    ],
    nutritionPerServing: { kcal: 420, proteinG: 16, carbsG: 35, fatG: 26 },
  },
  {
    id: 'yulafli-kahvalti-kasesi',
    nameTr: 'Meyveli Yulaf Kasesi',
    nameEn: 'Overnight Oats',
    category: 'breakfast',
    cuisine: 'international',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['healthy', 'quick', 'make_ahead', 'vegetarian', 'student_friendly'],
    ingredients: [
      { name: 'Yulaf ezmesi', amount: 'yarım su bardağı' },
      { name: 'Süt veya yoğurt', amount: '1 su bardağı' },
      { name: 'Bal veya akçaağaç şurubu', amount: '1 tatlı kaşığı' },
      { name: 'Muz (dilim)', amount: '1 adet' },
      { name: 'Kuruyemiş (ceviz / badem)', amount: '1 yemek kaşığı' },
      { name: 'Tarçın', amount: '1 tutam' },
      { name: 'Chia tohumu (opsiyonel)', amount: '1 çay kaşığı' },
    ],
    steps: [
      'Bir kavanoza yulaf, süt, bal, tarçın ve chia koyup karıştırın.',
      'Gece boyu buzdolabında bekletin (minimum 4 saat).',
      'Sabah üstüne muz ve kuruyemişleri ekleyip karıştırarak servis edin.',
    ],
    nutritionPerServing: { kcal: 420, proteinG: 16, carbsG: 65, fatG: 10 },
  },
  {
    id: 'hasanpasa-kasarli-yumurta',
    nameTr: 'Kaşarlı Sahan Yumurta',
    nameEn: 'Sunny-Side Eggs with Cheddar',
    category: 'breakfast',
    cuisine: 'turkish',
    servings: 1,
    prepMinutes: 2,
    cookMinutes: 5,
    difficulty: 'easy',
    tags: ['quick', 'high_protein', 'student_friendly', 'vegetarian'],
    ingredients: [
      { name: 'Yumurta', amount: '2 adet' },
      { name: 'Kaşar peyniri (rende)', amount: '2 yemek kaşığı' },
      { name: 'Tereyağı', amount: '1 yemek kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Küçük tavada tereyağını eritin.',
      'Yumurtaları tavaya kırın.',
      'Beyaz kısım pişmeye başladığında kaşarı yumurtaların etrafına serpin.',
      'Tavanın üstünü kapatıp 2 dakika daha pişirin.',
      'Tuz-karabiber ekleyip sıcak servis edin.',
    ],
    nutritionPerServing: { kcal: 320, proteinG: 22, carbsG: 2, fatG: 25 },
  },
  {
    id: 'gozleme',
    nameTr: 'Peynirli Gözleme',
    nameEn: 'Cheese Gözleme',
    category: 'breakfast',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 30,
    cookMinutes: 20,
    difficulty: 'medium',
    tags: ['traditional', 'vegetarian'],
    ingredients: [
      { name: 'Un', amount: '3 su bardağı' },
      { name: 'Ilık su', amount: '1 su bardağı' },
      { name: 'Yoğurt', amount: '2 yemek kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Beyaz peynir', amount: '200 g' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Tereyağı veya yağ (pişirmek için)', amount: 'yeterince' },
    ],
    steps: [
      'Un, yoğurt, tuz ve ılık su ile yumuşak hamur yoğurun; 20 dakika dinlendirin.',
      'Hamuru 8 bezeye bölün; her bezeyi ince bir daire halinde açın.',
      'Peynir ve kıyılmış maydanoz karışımını yarısına yayın; yarım ay şeklinde kapatın.',
      'Tavayı kızdırın, gözlemeyi az yağla her iki yüzü 2-3 dakika pişirin.',
      'Üzerine tereyağı sürerek servis edin.',
    ],
    nutritionPerServing: { kcal: 460, proteinG: 15, carbsG: 60, fatG: 18 },
  },
  {
    id: 'havuclu-yogurt-kahvalti',
    nameTr: 'Havuçlu Tarator Mezesi',
    nameEn: 'Carrot Yogurt Dip',
    category: 'breakfast',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 10,
    difficulty: 'easy',
    tags: ['vegetarian', 'healthy', 'quick'],
    ingredients: [
      { name: 'Havuç', amount: '3 adet' },
      { name: 'Zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Süzme yoğurt', amount: '1 su bardağı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Ceviz', amount: 'yarım çay bardağı' },
      { name: 'Tuz', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Havuçları rendeleyin.',
      'Tavada yağı ısıtıp havuçları 8-10 dakika yumuşayana dek kavurun; soğutun.',
      'Yoğurt, ezilmiş sarımsak ve tuzu karıştırın.',
      'Soğuyan havuçları yoğurtla birleştirin; üzerine ceviz serpin.',
      'Ekmek veya kahvaltı yanında servis edin.',
    ],
    nutritionPerServing: { kcal: 180, proteinG: 5, carbsG: 10, fatG: 13 },
  },
];
