import type { RecipeSeed } from './_types.js';

export const desserts: RecipeSeed[] = [
  {
    id: 'sutlac',
    nameTr: 'Sütlaç',
    nameEn: 'Turkish Rice Pudding',
    category: 'dessert',
    cuisine: 'turkish',
    servings: 6,
    prepMinutes: 5,
    cookMinutes: 40,
    difficulty: 'easy',
    tags: ['traditional', 'vegetarian'],
    ingredients: [
      { name: 'Baldo pirinç', amount: '1 su bardağı' },
      { name: 'Su', amount: '2 su bardağı' },
      { name: 'Süt', amount: '1 litre' },
      { name: 'Şeker', amount: '1 su bardağı' },
      { name: 'Nişasta', amount: '2 yemek kaşığı' },
      { name: 'Vanilya', amount: '1 paket' },
      { name: 'Tarçın (servis)', amount: 'yeterince' },
    ],
    steps: [
      'Pirinci yıkayıp su ile pirinç şişene dek 20 dk kaynatın.',
      'Sütü ekleyin; kaynayınca şekeri ekleyip karıştırın.',
      'Yarım bardak sütte ezdiğiniz nişastayı yavaşça ekleyip karıştırın; 5 dk daha pişirin.',
      'Vanilyayı ekleyin; kâselere alın, soğuttuktan sonra buzdolabına alın.',
      'Tarçınla servis edin. Fırın sütlaç için 200°C fırında üstü 10 dk kızartılır.',
    ],
    nutritionPerServing: { kcal: 260, proteinG: 6, carbsG: 52, fatG: 3 },
  },
  {
    id: 'muhallebi',
    nameTr: 'Muhallebi',
    nameEn: 'Turkish Milk Pudding',
    category: 'dessert',
    cuisine: 'turkish',
    servings: 5,
    prepMinutes: 3,
    cookMinutes: 15,
    difficulty: 'easy',
    tags: ['vegetarian', 'quick', 'traditional'],
    ingredients: [
      { name: 'Süt', amount: '1 litre' },
      { name: 'Şeker', amount: 'yarım su bardağı' },
      { name: 'Nişasta', amount: '3 yemek kaşığı' },
      { name: 'Un', amount: '2 yemek kaşığı' },
      { name: 'Vanilya', amount: '1 paket' },
      { name: 'Gül suyu', amount: '1 tatlı kaşığı' },
      { name: 'Hindistan cevizi/kaşığı', amount: 'serpmek için' },
    ],
    steps: [
      'Nişasta ve unu yarım bardak sütte ezin.',
      'Kalan sütü ve şekeri tencerede ısıtın.',
      'Kaynamaya yakın nişasta karışımını ekleyip sürekli karıştırın.',
      'Koyulaştığında vanilya ve gül suyunu ekleyin; 1 dakika daha pişirin.',
      'Kâselere paylaştırıp soğutun; hindistan cevizi serpin.',
    ],
    nutritionPerServing: { kcal: 220, proteinG: 6, carbsG: 42, fatG: 3 },
  },
  {
    id: 'kesk ul',
    nameTr: 'Keşkül',
    nameEn: 'Almond Milk Pudding',
    category: 'dessert',
    cuisine: 'turkish',
    servings: 5,
    prepMinutes: 10,
    cookMinutes: 20,
    difficulty: 'medium',
    tags: ['vegetarian', 'traditional'],
    ingredients: [
      { name: 'Süt', amount: '1 litre' },
      { name: 'Şeker', amount: '1 su bardağı' },
      { name: 'Badem (haşlanmış, soyulmuş)', amount: 'yarım su bardağı' },
      { name: 'Nişasta', amount: '3 yemek kaşığı' },
      { name: 'Yumurta sarısı', amount: '2 adet' },
      { name: 'Hindistan cevizi, fıstık', amount: 'servis için' },
    ],
    steps: [
      'Bademi rondoda ince çekin.',
      'Sütü ısıtın; şeker ve bademi ekleyin.',
      'Nişastayı yarım bardak soğuk sütte ezip sıcak karışıma yavaşça katın.',
      'Koyulaşana dek çırparak pişirin.',
      'Ocaktan alıp yumurta sarılarını hafifçe katın; tekrar 1 dakika ısıtın.',
      'Kâselere alıp soğutun; hindistan cevizi ve fıstıkla servis edin.',
    ],
    nutritionPerServing: { kcal: 290, proteinG: 9, carbsG: 40, fatG: 10 },
  },
  {
    id: 'revani',
    nameTr: 'Revani',
    nameEn: 'Semolina Cake with Syrup',
    category: 'dessert',
    cuisine: 'turkish',
    servings: 10,
    prepMinutes: 20,
    cookMinutes: 30,
    difficulty: 'easy',
    tags: ['traditional', 'vegetarian'],
    ingredients: [
      { name: 'Yumurta', amount: '4 adet' },
      { name: 'Şeker (kek için)', amount: '1 su bardağı' },
      { name: 'Yoğurt', amount: '1 su bardağı' },
      { name: 'Sıvı yağ', amount: 'yarım su bardağı' },
      { name: 'İrmik', amount: '1 su bardağı' },
      { name: 'Un', amount: '1 su bardağı' },
      { name: 'Kabartma tozu', amount: '1 paket' },
      { name: 'Limon kabuğu', amount: '1 adet' },
      { name: 'Şerbet için şeker', amount: '2 su bardağı' },
      { name: 'Su', amount: '2,5 su bardağı' },
      { name: 'Limon suyu', amount: '2 yemek kaşığı' },
      { name: 'Hindistan cevizi', amount: 'servis için' },
    ],
    steps: [
      'Şerbet için şekeri suyla 10 dk kaynatın; son 1 dk limon ekleyin. Soğutun.',
      'Yumurta ve şekeri çırpın; yoğurt, yağ, limon kabuğunu katın.',
      'İrmik, un ve kabartma tozunu ekleyip harç yapın.',
      'Yağlanmış tepsiye yayın; 180°C fırında 25-30 dk kızartın.',
      'Soğumuş şerbeti sıcak revaniye yavaşça dökün; çekmesini bekleyin.',
      'Dilimleyip hindistan cevizi serperek servis edin.',
    ],
    nutritionPerServing: { kcal: 380, proteinG: 6, carbsG: 65, fatG: 11 },
  },
  {
    id: 'sekerpare',
    nameTr: 'Şekerpare',
    nameEn: 'Turkish Sweet Biscuits',
    category: 'dessert',
    cuisine: 'turkish',
    servings: 16,
    prepMinutes: 20,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['traditional', 'vegetarian'],
    ingredients: [
      { name: 'Tereyağı', amount: '125 g' },
      { name: 'Pudra şekeri', amount: 'yarım su bardağı' },
      { name: 'Yumurta', amount: '1 adet' },
      { name: 'İrmik', amount: 'yarım su bardağı' },
      { name: 'Un', amount: '2 su bardağı' },
      { name: 'Kabartma tozu', amount: '1 paket' },
      { name: 'Vanilya', amount: '1 paket' },
      { name: 'Badem içi', amount: '16 adet' },
      { name: 'Şerbet için şeker', amount: '2 su bardağı' },
      { name: 'Su', amount: '2,5 su bardağı' },
      { name: 'Limon', amount: '1 dilim' },
    ],
    steps: [
      'Şerbeti önceden kaynatıp soğutun.',
      'Tereyağı ve pudra şekerini iyice karıştırın; yumurtayı ekleyin.',
      'İrmik, vanilya, kabartma tozu ve unla yumuşak hamur yapın.',
      '16 beze alıp yuvarlayın; üstlerine birer badem bastırın.',
      'Tepsiye dizip 170°C fırında 25 dk kızartın.',
      'Sıcak şekerparelere soğuk şerbeti dökün; oda sıcaklığında çektirin.',
    ],
    nutritionPerServing: { kcal: 220, proteinG: 3, carbsG: 34, fatG: 9 },
  },
  {
    id: 'kabak-tatlisi',
    nameTr: 'Kabak Tatlısı',
    nameEn: 'Candied Pumpkin',
    category: 'dessert',
    cuisine: 'turkish',
    servings: 6,
    prepMinutes: 10,
    cookMinutes: 45,
    difficulty: 'easy',
    tags: ['traditional', 'vegetarian', 'autumn'],
    ingredients: [
      { name: 'Balkabağı (soyulmuş)', amount: '1 kg' },
      { name: 'Şeker', amount: '2 su bardağı' },
      { name: 'Karanfil', amount: '5-6 adet' },
      { name: 'Tarçın', amount: '1 çubuk' },
      { name: 'Ceviz', amount: '1 su bardağı' },
      { name: 'Tahin (opsiyonel)', amount: '2 yemek kaşığı' },
    ],
    steps: [
      'Kabakları iri küpler halinde doğrayıp tencereye yerleştirin.',
      'Üzerine şeker, karanfil ve tarçını serpip 2 saat dinlendirin (suyunu bırakır).',
      'Kısık ateşte kapalı şekilde 35-40 dk pişirin; çok suyu kalırsa açık pişirin.',
      'Soğutup tabağa alın; ceviz ve tahinle servis edin.',
    ],
    nutritionPerServing: { kcal: 320, proteinG: 3, carbsG: 58, fatG: 11 },
  },
  {
    id: 'asure',
    nameTr: 'Aşure',
    nameEn: 'Ashure (Noah\'s Pudding)',
    category: 'dessert',
    cuisine: 'turkish',
    servings: 10,
    prepMinutes: 600,
    cookMinutes: 120,
    difficulty: 'hard',
    tags: ['traditional', 'vegetarian', 'vegan'],
    ingredients: [
      { name: 'Aşurelik buğday', amount: '1 su bardağı' },
      { name: 'Kuru fasulye (haşlanmış)', amount: 'yarım su bardağı' },
      { name: 'Nohut (haşlanmış)', amount: 'yarım su bardağı' },
      { name: 'Pirinç', amount: '2 yemek kaşığı' },
      { name: 'Kuru incir', amount: '4 adet' },
      { name: 'Kuru kayısı', amount: '6 adet' },
      { name: 'Kuş üzümü', amount: 'yarım su bardağı' },
      { name: 'Şeker', amount: '2 su bardağı' },
      { name: 'Gül suyu', amount: '1 yemek kaşığı' },
      { name: 'Ceviz, fıstık, nar (servis)', amount: 'yeterince' },
      { name: 'Tarçın', amount: '1 tatlı kaşığı' },
    ],
    steps: [
      'Aşurelik buğdayı gece suda bekletin; ertesi gün yumuşayana kadar haşlayın.',
      'Haşlanmış nohut, fasulye ve incir-kayısıyı küçük doğrayıp ekleyin.',
      'Pirinci ve kuş üzümünü ekleyip 30 dk pişirin; koyulaştırmak için biraz un/pirinç unu da eklenebilir.',
      'Şeker ve gül suyunu son 10 dk ekleyip kaynatın.',
      'Kâselere alıp soğutun; üstüne ceviz, fıstık, nar ve tarçınla süsleyin.',
    ],
    nutritionPerServing: { kcal: 350, proteinG: 7, carbsG: 72, fatG: 5 },
  },
  {
    id: 'kazandibi',
    nameTr: 'Kazandibi',
    nameEn: 'Burnt Milk Pudding',
    category: 'dessert',
    cuisine: 'turkish',
    servings: 8,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'medium',
    tags: ['traditional', 'vegetarian'],
    ingredients: [
      { name: 'Süt', amount: '1 litre' },
      { name: 'Şeker', amount: '1 su bardağı' },
      { name: 'Nişasta', amount: '5 yemek kaşığı' },
      { name: 'Un', amount: '2 yemek kaşığı' },
      { name: 'Pirinç unu', amount: '1 yemek kaşığı' },
      { name: 'Vanilya', amount: '1 paket' },
      { name: 'Pudra şekeri (taban)', amount: '2 yemek kaşığı' },
    ],
    steps: [
      'Sütün yarısına nişasta, un ve pirinç ununu ezip pürüzsüz yapın.',
      'Kalan sütü şekerle tencerede ısıtın; kaynamadan önce karışımı yavaşça ekleyin.',
      'Koyulaşana dek sürekli karıştırın; vanilyayı ekleyin.',
      'Fırın tepsisine pudra şekerini serpin.',
      'Muhallebiyi dikkatlice tepsiye yayın; düz yaptıktan sonra kısık altta 10 dk tabanı karamelleyin.',
      'Soğutup kesip ters çevirerek ruloya servis edin.',
    ],
    nutritionPerServing: { kcal: 240, proteinG: 5, carbsG: 48, fatG: 3 },
  },
  {
    id: 'irmik-helvasi',
    nameTr: 'İrmik Helvası',
    nameEn: 'Semolina Halva',
    category: 'dessert',
    cuisine: 'turkish',
    servings: 6,
    prepMinutes: 5,
    cookMinutes: 30,
    difficulty: 'easy',
    tags: ['traditional', 'vegetarian', 'quick'],
    ingredients: [
      { name: 'İrmik', amount: '2 su bardağı' },
      { name: 'Tereyağı', amount: '150 g' },
      { name: 'Şeker', amount: '1,5 su bardağı' },
      { name: 'Süt', amount: '2 su bardağı' },
      { name: 'Su', amount: '1 su bardağı' },
      { name: 'Çam fıstığı', amount: 'yarım çay bardağı' },
      { name: 'Tarçın', amount: 'servis için' },
    ],
    steps: [
      'Şeker, süt ve suyu ayrı tencerede kaynatın; şurup kıvamına gelsin.',
      'Başka tencerede tereyağını eritip fıstığı hafif kavurun.',
      'İrmiği ekleyip kısık ateşte altın rengi olana kadar sabırla kavurun (~20 dk).',
      'Sıcak şerbeti yavaşça ekleyip karıştırın; suyunu çekene kadar pişirin.',
      'Kapağını örtüp 10 dk dinlendirin; kalıplara alın, tarçınla servis edin.',
    ],
    nutritionPerServing: { kcal: 480, proteinG: 7, carbsG: 68, fatG: 21 },
  },
  {
    id: 'kadayif',
    nameTr: 'Tel Kadayıf',
    nameEn: 'Shredded Kadayif',
    category: 'dessert',
    cuisine: 'turkish',
    servings: 10,
    prepMinutes: 15,
    cookMinutes: 30,
    difficulty: 'medium',
    tags: ['traditional', 'vegetarian'],
    ingredients: [
      { name: 'Tel kadayıf', amount: '500 g' },
      { name: 'Tereyağı (eritilmiş)', amount: '200 g' },
      { name: 'Ceviz (dövülmüş)', amount: '1,5 su bardağı' },
      { name: 'Şerbet için şeker', amount: '3 su bardağı' },
      { name: 'Su', amount: '3 su bardağı' },
      { name: 'Limon suyu', amount: '1 yemek kaşığı' },
    ],
    steps: [
      'Şerbeti: şeker ve suyu 10 dk kaynatıp limon ekleyin; soğutun.',
      'Kadayıfı parçalarına ayırıp yarısını tepsiye düzgün serin; eritilmiş yağla ıslatın.',
      'Ceviz kırığını yayın; üzerine kalan kadayıfı düzgünce yerleştirin; yağı döküp bastırın.',
      '200°C fırında alt-üst kızarana dek 20-25 dk pişirin.',
      'Fırından çıkar çıkmaz soğuk şerbeti dökün; çekmesini bekleyin.',
      'Dilimleyerek servis edin.',
    ],
    nutritionPerServing: { kcal: 560, proteinG: 6, carbsG: 70, fatG: 28 },
  },
  {
    id: 'lokma',
    nameTr: 'Lokma',
    nameEn: 'Turkish Syrup Doughnuts',
    category: 'dessert',
    cuisine: 'turkish',
    servings: 8,
    prepMinutes: 60,
    cookMinutes: 20,
    difficulty: 'medium',
    tags: ['traditional', 'vegetarian'],
    ingredients: [
      { name: 'Un', amount: '3 su bardağı' },
      { name: 'Ilık su', amount: '2 su bardağı' },
      { name: 'Yaş maya', amount: '20 g' },
      { name: 'Şeker (hamur)', amount: '1 tatlı kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Kızartma yağı', amount: 'yeterince' },
      { name: 'Şerbet için şeker', amount: '3 su bardağı' },
      { name: 'Su', amount: '3 su bardağı' },
      { name: 'Limon', amount: '1 dilim' },
    ],
    steps: [
      'Şerbeti 15 dk kaynatıp son dakika limon ekleyin; soğutun.',
      'Un, maya, şeker, tuz ve ılık suyla akışkan hamur yapın; 45 dk mayalandırın.',
      'Yağı orta ateşte ısıtın.',
      'Elle veya kaşıkla ceviz büyüklüğünde parçalar kopararak yağa bırakın.',
      'Altın rengi olana dek kızartın; süzüp soğuk şerbete atın, 2 dk sonra alın.',
      'Sıcak servis edin.',
    ],
    nutritionPerServing: { kcal: 420, proteinG: 5, carbsG: 78, fatG: 10 },
  },
  {
    id: 'cikolatali-sufle',
    nameTr: 'Çikolatalı Sufle',
    nameEn: 'Chocolate Soufflé',
    category: 'dessert',
    cuisine: 'international',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 12,
    difficulty: 'medium',
    tags: ['vegetarian', 'quick'],
    ingredients: [
      { name: 'Bitter çikolata', amount: '100 g' },
      { name: 'Tereyağı', amount: '50 g' },
      { name: 'Yumurta', amount: '2 adet' },
      { name: 'Şeker', amount: '3 yemek kaşığı' },
      { name: 'Un', amount: '2 yemek kaşığı' },
      { name: 'Vanilya', amount: '1 paket' },
    ],
    steps: [
      'Çikolata ve tereyağını benmaride eritin.',
      'Yumurta ve şekeri çırpın; eriyen çikolatayı ekleyin.',
      'Un ve vanilyayı ekleyip pürüzsüz harç yapın.',
      'Yağlanmış sufle kaplarına paylaştırın.',
      '200°C önceden ısıtılmış fırında 10-12 dakika, kenarları tutup ortası akışkan kalacak şekilde pişirin.',
      'Hemen servis edin; isterseniz dondurma ile.',
    ],
    nutritionPerServing: { kcal: 380, proteinG: 7, carbsG: 32, fatG: 25 },
  },
];
