import type { RecipeSeed } from './_types.js';

export const drinks: RecipeSeed[] = [
  {
    id: 'ayran',
    nameTr: 'Ayran',
    nameEn: 'Ayran',
    category: 'drink',
    cuisine: 'turkish',
    servings: 2,
    prepMinutes: 3,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['quick', 'student_friendly', 'traditional', 'vegetarian'],
    ingredients: [
      { name: 'Yoğurt', amount: '1,5 su bardağı' },
      { name: 'Soğuk su', amount: '1,5 su bardağı' },
      { name: 'Tuz', amount: 'yarım çay kaşığı' },
      { name: 'Buz', amount: 'isteğe bağlı' },
    ],
    steps: [
      'Yoğurdu derin bir kaseye alıp çırpma teli ile çırpın.',
      'Suyu azar azar ilave edip pürüzsüz, köpüklü kıvam elde edin.',
      'Tuzu ekleyin; soğuk veya buzlu servis edin.',
    ],
    nutritionPerServing: { kcal: 70, proteinG: 5, carbsG: 6, fatG: 3 },
  },
  {
    id: 'limonata',
    nameTr: 'Ev Yapımı Limonata',
    nameEn: 'Turkish Lemonade',
    category: 'drink',
    cuisine: 'turkish',
    servings: 6,
    prepMinutes: 10,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['quick', 'vegetarian', 'vegan', 'summer'],
    ingredients: [
      { name: 'Limon', amount: '6 adet' },
      { name: 'Portakal', amount: '1 adet' },
      { name: 'Şeker', amount: '1 su bardağı' },
      { name: 'Soğuk su', amount: '1,5 litre' },
      { name: 'Nane', amount: 'birkaç yaprak' },
    ],
    steps: [
      'Limon ve portakalları iyice yıkayın; dörde bölüp çekirdeklerini alın.',
      'Şekerle birlikte rondoda pulse yaparak iri parça kalacak şekilde çekin.',
      'Soğuk suyu ekleyip karıştırın; 1 saat dinlendirin, süzün.',
      'Buzlu ve naneli servis edin.',
    ],
    nutritionPerServing: { kcal: 120, proteinG: 0, carbsG: 30, fatG: 0 },
  },
  {
    id: 'salep',
    nameTr: 'Salep',
    nameEn: 'Salep',
    category: 'drink',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 15,
    difficulty: 'easy',
    tags: ['winter', 'traditional', 'vegetarian', 'comfort'],
    ingredients: [
      { name: 'Salep tozu (hazır)', amount: '2 yemek kaşığı' },
      { name: 'Süt', amount: '1 litre' },
      { name: 'Şeker', amount: '3-4 yemek kaşığı' },
      { name: 'Tarçın', amount: 'serpmek için' },
    ],
    steps: [
      'Salep tozunu ve şekeri yarım bardak soğuk sütle ezin.',
      'Kalan sütü tencerede ısıtın.',
      'Salep karışımını sıcak süte yavaş yavaş, sürekli karıştırarak ekleyin.',
      'Kaynayınca kısık ateşte koyulaşana kadar 5-7 dakika karıştırın.',
      'Fincanlara alın; üzerine tarçın serpin.',
    ],
    nutritionPerServing: { kcal: 220, proteinG: 8, carbsG: 32, fatG: 7 },
  },
  {
    id: 'turk-kahvesi',
    nameTr: 'Türk Kahvesi',
    nameEn: 'Turkish Coffee',
    category: 'drink',
    cuisine: 'turkish',
    servings: 1,
    prepMinutes: 1,
    cookMinutes: 4,
    difficulty: 'easy',
    tags: ['traditional', 'vegetarian', 'vegan'],
    ingredients: [
      { name: 'Türk kahvesi', amount: '1 yemek kaşığı' },
      { name: 'Şeker (isteğe göre)', amount: '0-2 çay kaşığı' },
      { name: 'Soğuk su', amount: '1 küçük fincan' },
    ],
    steps: [
      'Cezveye soğuk su ve şekeri koyun.',
      'Kahveyi üzerine ekleyin, karıştırmadan altını yakın.',
      'Kısık ateşte köpük oluşana dek bekleyin (yaklaşık 3 dakika).',
      'Köpüğü fincana alın; cezveyi tekrar ateşe koyup kaynatın.',
      'Kahveyi yavaşça fincana boşaltın; üstünde köpük kalsın.',
      'Suyla birlikte servis edin.',
    ],
    nutritionPerServing: { kcal: 25, proteinG: 0, carbsG: 5, fatG: 0 },
  },
  {
    id: 'protein-smoothie',
    nameTr: 'Muzlu Protein Smoothie',
    nameEn: 'Banana Protein Smoothie',
    category: 'drink',
    cuisine: 'international',
    servings: 1,
    prepMinutes: 3,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['quick', 'high_protein', 'healthy', 'post_workout', 'student_friendly'],
    ingredients: [
      { name: 'Muz (donmuş)', amount: '1 adet' },
      { name: 'Süt veya bitkisel süt', amount: '1 su bardağı' },
      { name: 'Yoğurt', amount: '3 yemek kaşığı' },
      { name: 'Yulaf', amount: '2 yemek kaşığı' },
      { name: 'Bal', amount: '1 tatlı kaşığı' },
      { name: 'Fıstık ezmesi', amount: '1 tatlı kaşığı' },
      { name: 'Tarçın (opsiyonel)', amount: '1 tutam' },
    ],
    steps: [
      'Tüm malzemeleri blendera alın.',
      '30-40 saniye pürüzsüz olana dek çekin.',
      'Hemen servis edin.',
    ],
    nutritionPerServing: { kcal: 380, proteinG: 16, carbsG: 60, fatG: 10 },
  },
];
