import type { RecipeSeed } from './_types.js';

// Auto-generated by scripts/fetch-open.ts — do not hand-edit.
// Run `pnpm --filter @fittrack/recipe-db sync` to refresh.
export const themealdbTurkish: RecipeSeed[] = [
  {
    "id": "themealdb-adana-kebab",
    "nameTr": "Adana kebab",
    "nameEn": "Adana kebab",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Romano Pepper",
        "amount": "2 large"
      },
      {
        "name": "Lamb Mince",
        "amount": "800g"
      },
      {
        "name": "Red Pepper Paste",
        "amount": "3  tablespoons"
      },
      {
        "name": "Pul Biber",
        "amount": "1 tablespoon"
      },
      {
        "name": "Sunflower Oil",
        "amount": "3  tablespoons"
      }
    ],
    "steps": [
      "step 1",
      "Finely chop the peppers in a food processor, then tip them in a sieve and press into the sieve so that the peppers release all of their juices. Tip into a bowl along with the mince, red pepper paste, pul biber, 1½ tsp flaky sea salt, and 2 tbsp of the oil. Mix together, kneading well for at least 2-3 mins. If you need to, wet your hands with cold water to prevent the mixture from sticking. The mixture should be sticky when ready. Cover and chill for at least 2 hrs, or up to 12 hrs.",
      "step 2",
      "When ready to cook, heat the grill to high or an oven to 220C/200C fan/gas 6. Divide the mixture into 12 equal portions, around 85g each. If you’d like to skewer them, divide into 8 equal portions and roll into balls. Using wet hands, thread the balls onto the end of the skewers, massaging the mixture down the skewers in between the palms of your hands, until evenly distributed. Ensure that the mixture is fully wrapped tightly around the skewers without any exposed metal. Alternatively, lay them on a large baking tray lined with parchment paper if cooking in the oven, or foil if cooking under the grill. Shape into 20cm-long köfte. Wet your fingers with a little cold water and make indents all along the köfte for the traditional shape.",
      "step 3",
      "Gently brush each köfte with the remaining 1 tbsp oil and cook under the grill, on the top shelf for 10-12 mins, turning regularly, or cook in the oven for 16-18 mins, until crispy on the outside and juicy in the middle"
    ],
    "source": "TheMealDB #53262"
  },
  {
    "id": "themealdb-apricot-turkish-delight-mess",
    "nameTr": "Apricot & Turkish delight mess",
    "nameEn": "Apricot & Turkish delight mess",
    "category": "dessert",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Mascarpone",
        "amount": "100g"
      },
      {
        "name": "Greek Yogurt",
        "amount": "50g"
      },
      {
        "name": "Icing Sugar",
        "amount": "25g"
      },
      {
        "name": "Orange Blossom Water",
        "amount": "2 tablespoons"
      },
      {
        "name": "Meringue Nests",
        "amount": "1"
      },
      {
        "name": "Apricot",
        "amount": "3"
      },
      {
        "name": "Turkish Delight",
        "amount": "2 pieces"
      },
      {
        "name": "Almonds",
        "amount": "25g"
      },
      {
        "name": "Mint",
        "amount": "4"
      }
    ],
    "steps": [
      "step 1",
      "Place the mascarpone, yogurt, sugar and orange flower water into a large bowl and whisk until thickened. Fold the remaining ingredients through, then divide the mix between 2 dessert glasses or bowls and decorate with extra mint, if you like."
    ],
    "source": "TheMealDB #53276"
  },
  {
    "id": "themealdb-aubergine-hummus-grills",
    "nameTr": "Aubergine & hummus grills",
    "nameEn": "Aubergine & hummus grills",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Aubergine",
        "amount": "2"
      },
      {
        "name": "Vegetable Oil",
        "amount": "2 tablespoons"
      },
      {
        "name": "Bread",
        "amount": "3 sliced thinly"
      },
      {
        "name": "Hummus",
        "amount": "300g"
      },
      {
        "name": "Walnuts",
        "amount": "100g"
      },
      {
        "name": "Parsley",
        "amount": "40g"
      },
      {
        "name": "Cherry Tomatoes",
        "amount": "200g"
      },
      {
        "name": "Lemon",
        "amount": "Juice of 1/2"
      },
      {
        "name": "Extra Virgin Olive Oil",
        "amount": "Splash"
      }
    ],
    "steps": [
      "step 1",
      "Lay the aubergine out in one layer on a large baking sheet. Brush sparingly with vegetable oil, then season generously. Grill for 15 mins, turning twice and brushing with oil until the slices are softened and cooked through. Meanwhile, whizz the bread into crumbs. Add 2 tsp oil and whizz briefly again, to coat.",
      "step 2",
      "Spread a couple of tsps of hummus on top of each slice of aubergine. Tip the breadcrumbs onto a large plate, then press the hummus side of the aubergines into the crumbs to coat. Grill again, crumb-side up, for about 3 mins until golden.",
      "step 3",
      "Toss the walnuts, parsley and cherry tomatoes in a bowl, season, then add the lemon juice and olive oil and toss again. Serve the grills with the salad, a dollop more hummus and some pitta bread."
    ],
    "source": "TheMealDB #53278"
  },
  {
    "id": "themealdb-aubergine-couscous-salad",
    "nameTr": "Aubergine couscous salad",
    "nameEn": "Aubergine couscous salad",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Aubergine",
        "amount": "1 sliced"
      },
      {
        "name": "Olive Oil",
        "amount": "3  tablespoons"
      },
      {
        "name": "Couscous",
        "amount": "140g"
      },
      {
        "name": "Vegetable Stock",
        "amount": "225g"
      },
      {
        "name": "Cherry Tomatoes",
        "amount": "200g"
      },
      {
        "name": "Mint",
        "amount": "Handful"
      },
      {
        "name": "Goats Cheese",
        "amount": "100g"
      },
      {
        "name": "Lemon",
        "amount": "Juice of 1/2"
      }
    ],
    "steps": [
      "step 1",
      "Heat grill to high. Put the aubergine on a baking sheet, brush with oil and season. Grill for about 15 mins, turning and brushing with more oil halfway, until browned and softened.",
      "step 2",
      "Meanwhile, tip the couscous into a large bowl, pour over the stock, then cover and leave for 10 mins. Mix the tomatoes, mint, goat’s cheese and remaining oil together. Fluff the couscous up with a fork, then stir in the aubergines, tomato mixture and lemon juice."
    ],
    "source": "TheMealDB #53267"
  },
  {
    "id": "themealdb-baklava-with-spiced-nuts-ricotta-chocolate",
    "nameTr": "Baklava with spiced nuts, ricotta & chocolate",
    "nameEn": "Baklava with spiced nuts, ricotta & chocolate",
    "category": "dessert",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Sugar",
        "amount": "500g"
      },
      {
        "name": "Lemon Juice",
        "amount": "To taste"
      },
      {
        "name": "Walnuts",
        "amount": "300g"
      },
      {
        "name": "Pecan Nuts",
        "amount": "200g"
      },
      {
        "name": "Almonds",
        "amount": "100g"
      },
      {
        "name": "Ground Cinnamon",
        "amount": "2 tablespoons"
      },
      {
        "name": "Ground Cardomom",
        "amount": "1 tablespoon"
      },
      {
        "name": "Ricotta",
        "amount": "500g"
      },
      {
        "name": "Lemon",
        "amount": "Zest of 1"
      },
      {
        "name": "Orange",
        "amount": "Zest of 1"
      },
      {
        "name": "Vanilla Bean Paste",
        "amount": "1 tablespoon"
      },
      {
        "name": "Unsalted Butter",
        "amount": "250g"
      },
      {
        "name": "Filo Pastry",
        "amount": "500g"
      },
      {
        "name": "Ground Pistachios",
        "amount": "100g"
      }
    ],
    "steps": [
      "step 1",
      "First, make the syrup. Tip the sugar into a large saucepan with 650ml water. Stir over a low heat until the sugar has dissolved, then turn up the heat and bring to the boil. Reduce the heat to a simmer and cook for 15 mins, then squeeze in a few drops of lemon juice and simmer for a further 5 mins. Remove from the heat and leave to cool. Meanwhile, for assembling the baklava later, melt the butter in a small pan over a low heat for 5 mins, skimming and discarding any froth that rises to the surface.",
      "step 2",
      "For the filling, crush all of the nuts in a pestle and mortar, or blitz in a food processor – you want a mixture of finely ground nuts with a few chunky pieces. Tip into a bowl, stir through the spices and set aside.",
      "step 3",
      "In a separate bowl, mix the ricotta with the lemon and orange zests and vanilla. Heat the oven to 180C/160C fan/gas 4. Brush the bottom of a large baking tray (about 35 x 47cm) with some of the melted butter. Working with one sheet of filo at a time (covering the rest with a damp tea towel to prevent it drying out), lay the sheet out on a board so one of the short ends is facing you. Sprinkle 30g of the nut mixture evenly over the whole sheet, then spoon 1 tbsp of the ricotta mixture across the end closest to you. Fold this end over to enclose the filling, then lay a long, thin skewer next to the folded edge and roll the pastry around it to create a long roll. When it’s fully rolled up, it should be roughly the thickness of a chipolata sausage. While holding one end of the rolling pin or skewer, gently scrunch the filo roll like an accordion and carefully push it off the skewer and onto the prepared tray. Repeat with the rest of the filo and fillings – you should get about 12 rolls. Cut each roll into four to make 48 large baklava, or eight to make 96 mini.",
      "step 4",
      "Brush with the remaining melted butter. Bake for 20-25 mins until evenly golden, turning the tray around halfway through. While still hot, immediately pour over 5-6 ladlefuls of the syrup. You should hear the syrup sizzle as it hits the hot baklava. Set aside to cool and absorb.",
      "step 5",
      "Melt the dark chocolate in a heatproof bowl set over a pan of simmering water, ensuring the bowl doesn’t touch the water, or in the microwave in short bursts. Drizzle this over the cooled baklava and sprinkle with the ground pistachios."
    ],
    "source": "TheMealDB #53279"
  },
  {
    "id": "themealdb-cacik",
    "nameTr": "Cacik",
    "nameEn": "Cacik",
    "category": "main_veg",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Natural Yoghurt",
        "amount": "500g"
      },
      {
        "name": "Lemon Juice",
        "amount": "2 tsp"
      },
      {
        "name": "Extra Virgin Olive Oil",
        "amount": "1 tablespoon"
      },
      {
        "name": "Dried Mint",
        "amount": "1 tablespoon"
      },
      {
        "name": "Cucumber",
        "amount": "1"
      },
      {
        "name": "Garlic",
        "amount": "2 cloves minced"
      }
    ],
    "steps": [
      "step 1",
      "Put a sieve over a large bowl, line it with a thick sheet of non-dyed kitchen paper or a clean muslin cloth, and spoon in the yogurt. Cover with another sheet of kitchen paper and leave to strain in the fridge for a minimum of 12 hrs.",
      "step 2",
      "Add the lemon juice, most of the olive oil and the dried mint to a bowl and stir well for the dried mint to soften and soak up the juices. Mix in the strained yogurt, then pour away the strained yogurt liquid and leave that bowl to one side.",
      "step 3",
      "Halve the cucumber(s) lengthways and remove the seeds by running a teaspoon from the top to the bottom of the flesh, halve the cucumbers widthways to make them shorter and easier to handle, then coarsely grate each one into the bowl the yogurt was straining over. Using clean hands (or a clean muslin cloth), squeeze as much of the liquid out of the cucumber as possible.",
      "step 4",
      "Add the strained, grated cucumber, garlic and ¾ tsp flaky salt to the rest of the ingredients and mix well. Garnish with a drizzle of extra virgin olive oil and a sprinkling of dried mint."
    ],
    "source": "TheMealDB #53256"
  },
  {
    "id": "themealdb-chicken-wings-with-cumin-lemon-garlic",
    "nameTr": "Chicken wings with cumin, lemon & garlic",
    "nameEn": "Chicken wings with cumin, lemon & garlic",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Chicken Wings",
        "amount": "12"
      },
      {
        "name": "Garlic",
        "amount": "2 cloves minced"
      },
      {
        "name": "Lemon",
        "amount": "Zest and juice of 1"
      },
      {
        "name": "Cumin Seeds",
        "amount": "1 tsp"
      },
      {
        "name": "Olive Oil",
        "amount": "2 tablespoons"
      },
      {
        "name": "Honey",
        "amount": "1 tablespoon"
      }
    ],
    "steps": [
      "step 1",
      "Using a pair of sharp kitchen scissors, cut each wing at the knuckle into two pieces. Mix the garlic, lemon zest and juice, cumin and oil with plenty of seasoning, then tip into a dish with the chicken wings and toss to coat. Cover and put in the fridge to marinate for at least 1 hr, or overnight if you have time.",
      "step 2",
      "Heat oven to 200C/180C fan/gas 6, or heat an outdoor barbecue. Bake the chicken wings on an oven tray for 45-50 mins until crisp, or barbecue for 20 mins, drizzling over the honey for the final 10 mins of each method. Serve on a platter with plenty of paper napkins. Fill small bowls with olives, pistachios or almonds, dates and pickled chillies and flatbreads to serve alongside, along with the dishes below."
    ],
    "source": "TheMealDB #53261"
  },
  {
    "id": "themealdb-chilli-ginger-lamb-chops",
    "nameTr": "Chilli ginger lamb chops",
    "nameEn": "Chilli ginger lamb chops",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Garlic",
        "amount": "4 Cloves Crushed"
      },
      {
        "name": "Ginger",
        "amount": "1 tblsp"
      },
      {
        "name": "Lemon Juice",
        "amount": "1 tblsp"
      },
      {
        "name": "Olive Oil",
        "amount": "1 tblsp"
      },
      {
        "name": "Chili Powder",
        "amount": "1/2 tsp"
      },
      {
        "name": "Cumin",
        "amount": "1 tsp"
      },
      {
        "name": "Lamb Loin Chops",
        "amount": "8"
      }
    ],
    "steps": [
      "step 1",
      "Put the garlic in a bowl with the ginger, lemon juice, oil, spices and seasoning. Blitz with a hand blender until smooth, then use to coat the lamb chops on both sides. Leave to marinate in the fridge for a couple of hours or overnight.",
      "step 2",
      "Heat a barbecue until hot. Barbecue the chops over the coals for 3 mins on each side until cooked but still pink and juicy in the centre."
    ],
    "source": "TheMealDB #53265"
  },
  {
    "id": "themealdb-corba",
    "nameTr": "Corba",
    "nameEn": "Corba",
    "category": "main_veg",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Lentils",
        "amount": "1 cup"
      },
      {
        "name": "Onion",
        "amount": "1 large"
      },
      {
        "name": "Carrots",
        "amount": "1 large"
      },
      {
        "name": "Tomato Puree",
        "amount": "1 tbs"
      },
      {
        "name": "Cumin",
        "amount": "2 tsp"
      },
      {
        "name": "Paprika",
        "amount": "1 tsp"
      },
      {
        "name": "Mint",
        "amount": "1/2 tsp"
      },
      {
        "name": "Thyme",
        "amount": "1/2 tsp"
      },
      {
        "name": "Black Pepper",
        "amount": "1/4 tsp"
      },
      {
        "name": "Red Pepper Flakes",
        "amount": "1/4 tsp"
      },
      {
        "name": "Vegetable Stock",
        "amount": "4 cups"
      },
      {
        "name": "Water",
        "amount": "1 cup"
      },
      {
        "name": "Sea Salt",
        "amount": "Pinch"
      }
    ],
    "steps": [
      "Pick through your lentils for any foreign debris, rinse them 2 or 3 times, drain, and set aside.  Fair warning, this will probably turn your lentils into a solid block that you’ll have to break up later",
      "In a large pot over medium-high heat, sauté the olive oil and the onion with a pinch of salt for about 3 minutes, then add the carrots and cook for another 3 minutes.",
      "Add the tomato paste and stir it around for around 1 minute. Now add the cumin, paprika, mint, thyme, black pepper, and red pepper as quickly as you can and stir for 10 seconds to bloom the spices. Congratulate yourself on how amazing your house now smells.",
      "Immediately add the lentils, water, broth, and salt. Bring the soup to a (gentle) boil.",
      "After it has come to a boil, reduce heat to medium-low, cover the pot halfway, and cook for 15-20 minutes or until the lentils have fallen apart and the carrots are completely cooked.",
      "After the soup has cooked and the lentils are tender, blend the soup either in a blender or simply use a hand blender to reach the consistency you desire. Taste for seasoning and add more salt if necessary.",
      "Serve with crushed-up crackers, torn up bread, or something else to add some extra thickness.  You could also use a traditional thickener (like cornstarch or flour), but I prefer to add crackers for some texture and saltiness.  Makes great leftovers, stays good in the fridge for about a week."
    ],
    "source": "TheMealDB #52977"
  },
  {
    "id": "themealdb-ezme",
    "nameTr": "Ezme",
    "nameEn": "Ezme",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Tomato",
        "amount": "3 Large"
      },
      {
        "name": "Romano Pepper",
        "amount": "1 medium"
      },
      {
        "name": "Green Chilli",
        "amount": "1 medium"
      },
      {
        "name": "Onion",
        "amount": "1 small"
      },
      {
        "name": "Garlic",
        "amount": "2 cloves minced"
      },
      {
        "name": "Parsley",
        "amount": "25g"
      },
      {
        "name": "Red Pepper Paste",
        "amount": "2 tablespoons"
      },
      {
        "name": "Tomato Puree",
        "amount": "1 tablespoon"
      },
      {
        "name": "Pomegranate Molasses",
        "amount": "2 tablespoons"
      },
      {
        "name": "Pul Biber",
        "amount": "1 tablespoon"
      },
      {
        "name": "Sumac",
        "amount": "2 tsp"
      },
      {
        "name": "Dried Mint",
        "amount": "1 tablespoon"
      },
      {
        "name": "Extra Virgin Olive Oil",
        "amount": "60 ml"
      }
    ],
    "steps": [
      "step 1",
      "Put the tomatoes and all of the peppers in a food processor and blitz until finely chopped. Tip out into a sieve, set over a bowl and leave to strain. Add the onions, garlic and parsley to the food processor and blitz until finely chopped, then set aside.",
      "step 2",
      "Add red pepper paste, tomato purée, pomegranate molasses, pul biber, sumac, dried mint and most of the extra virgin olive oil to a serving bowl and whisk well so everything comes together as a sauce. Tip in the blitzed onion mixture and the strained pepper mixture along with 1 tsp flaky sea salt . Stir well, then drizzle with the remaining extra virgin olive oil to serve."
    ],
    "source": "TheMealDB #53254"
  },
  {
    "id": "themealdb-falafel",
    "nameTr": "Falafel",
    "nameEn": "Falafel",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Sunflower Oil",
        "amount": "2 tablespoons"
      },
      {
        "name": "Onion",
        "amount": "1 chopped"
      },
      {
        "name": "Garlic",
        "amount": "1 clove peeled crushed"
      },
      {
        "name": "Chickpeas",
        "amount": "400g"
      },
      {
        "name": "Ground Cumin",
        "amount": "1 tsp"
      },
      {
        "name": "Ground Coriander",
        "amount": "1 tsp"
      },
      {
        "name": "Parsley",
        "amount": "Handful"
      },
      {
        "name": "Egg",
        "amount": "1 beaten"
      }
    ],
    "steps": [
      "step 1",
      "Heat 1 tbsp oil in a large pan, then fry the onion and garlic over a low heat for 5 mins until softened. Tip into a large mixing bowl with the chickpeas and spices, then mash together with a fork or potato masher until the chickpeas are totally broken down. Stir in the parsley or dried herbs, with seasoning to taste. Add the egg, then squish the mixture together with your hands.",
      "step 2",
      "Mould the mix into 6 balls, then flatten into patties. Heat the remaining oil in the pan, then fry the falafels on a medium heat for 3 mins on each side, until golden brown and firm. Serve hot or cold with couscous, pitta bread or salad."
    ],
    "source": "TheMealDB #53266"
  },
  {
    "id": "themealdb-griddled-aubergines-with-sesame-dressing",
    "nameTr": "Griddled aubergines with sesame dressing",
    "nameEn": "Griddled aubergines with sesame dressing",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Aubergine",
        "amount": "2 large"
      },
      {
        "name": "Olive Oil",
        "amount": "2 tablespoons"
      },
      {
        "name": "Greek Yogurt",
        "amount": "250g"
      },
      {
        "name": "Tahini Paste",
        "amount": "3  tablespoons"
      },
      {
        "name": "Garlic",
        "amount": "1 clove peeled crushed"
      },
      {
        "name": "Lemon",
        "amount": "Juice of 1"
      },
      {
        "name": "Coriander",
        "amount": "Handful"
      },
      {
        "name": "Parsley",
        "amount": "Handful"
      },
      {
        "name": "Mint",
        "amount": "Handful"
      }
    ],
    "steps": [
      "step 1",
      "Brush each aubergine slice with some oil, then season. Heat a griddle pan or barbecue. When hot, griddle the aubergine slices for 2-3 mins on each side until golden brown and tender.",
      "step 2",
      "Mix the yogurt with the tahini, garlic, lemon juice and herbs, then season. Top the aubergines with the dressing and scatter over extra herb leaves."
    ],
    "source": "TheMealDB #53274"
  },
  {
    "id": "themealdb-griddled-flatbreads",
    "nameTr": "Griddled flatbreads",
    "nameEn": "Griddled flatbreads",
    "category": "main_veg",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Strong Wholemeal Flour",
        "amount": "250g"
      },
      {
        "name": "Strong white bread flour",
        "amount": "250g"
      },
      {
        "name": "Yeast",
        "amount": "15g"
      },
      {
        "name": "Sugar",
        "amount": "1 tsp"
      },
      {
        "name": "Olive Oil",
        "amount": "2 tablespoons"
      }
    ],
    "steps": [
      "step 1",
      "Tip the flours into a food processor. Add the yeast, sugar and 1tsp salt, then mix well. Pour in 350ml warm water and the oil, then process to a soft dough. Mix for 1 min, then leave until doubled in size, about 1 hour.",
      "step 2",
      "Pulse the dough a couple of times just to knock out the air, then tip onto a floured surface. Cut the dough in half and roll out one half to a rectangle about 20 x 40cm. Trim the edges using a large sharp knife, then cut into eight 10cm squares. Line a large tray or two baking sheets with non-stick paper and arrange the bread rectangles over the tray in one layer. Repeat with the other half of the dough. Leave in a warm place for about 30 mins until the dough is just starting to rise.",
      "step 3",
      "Place bread directly onto the BBQ racks and cook for a couple of mins until they puff up, then flip over and cook on the other side. Tip into a basket and serve with the dips."
    ],
    "source": "TheMealDB #53272"
  },
  {
    "id": "themealdb-grilled-aubergines-with-spicy-chickpeas-walnut-sauce",
    "nameTr": "Grilled aubergines with spicy chickpeas & walnut sauce",
    "nameEn": "Grilled aubergines with spicy chickpeas & walnut sauce",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Olive Oil",
        "amount": "4 tablespoons"
      },
      {
        "name": "Onion",
        "amount": "1 chopped"
      },
      {
        "name": "Red Chilli",
        "amount": "1 chopped"
      },
      {
        "name": "Ginger",
        "amount": "2cm piece"
      },
      {
        "name": "Ground Cumin",
        "amount": "1/2 teaspoon"
      },
      {
        "name": "Chickpeas",
        "amount": "400g"
      },
      {
        "name": "Tomato",
        "amount": "200g"
      },
      {
        "name": "Lemon",
        "amount": "Juice of 1/2"
      },
      {
        "name": "Aubergine",
        "amount": "2"
      },
      {
        "name": "Greek Yogurt",
        "amount": "200g"
      },
      {
        "name": "Garlic Clove",
        "amount": "1"
      },
      {
        "name": "Walnuts",
        "amount": "25g"
      },
      {
        "name": "Coriander",
        "amount": "Handful"
      }
    ],
    "steps": [
      "step 1",
      "Heat 2 tbsp oil in a pan, add the onion and fry until soft and lightly browned, about 10 mins. Add the chilli, ginger and spices and mix well. Stir in the chickpeas, tomatoes and 5 tbsp water, bring to the boil, then simmer for 10 mins. Add a little salt and pepper and the lemon juice.",
      "step 2",
      "Arrange the aubergines over a grill pan. Brush lightly with oil, sprinkle with salt and pepper, then grill until golden. Flip them over, brush again with oil, season and grill again until tender and golden.",
      "step 3",
      "Mix the yogurt with the garlic, most of the walnuts and coriander and a little salt and pepper. Arrange the aubergine slices over a warm platter and spoon over the chickpea mix. Drizzle with the walnut sauce and scatter with the remaining walnuts and coriander."
    ],
    "source": "TheMealDB #53255"
  },
  {
    "id": "themealdb-hot-cumin-lamb-wrap-with-crunchy-slaw-spicy-mayo",
    "nameTr": "Hot cumin lamb wrap with crunchy slaw & spicy mayo",
    "nameEn": "Hot cumin lamb wrap with crunchy slaw & spicy mayo",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Lamb Leg",
        "amount": "4 small"
      },
      {
        "name": "Olive Oil",
        "amount": "2 tsp"
      },
      {
        "name": "Ground Cumin",
        "amount": "1 tsp"
      },
      {
        "name": "Sugar",
        "amount": "1 tablespoon"
      },
      {
        "name": "White Wine Vinegar",
        "amount": "3  tablespoons"
      },
      {
        "name": "Carrots",
        "amount": "2"
      },
      {
        "name": "Spring Onions",
        "amount": "2 sliced"
      },
      {
        "name": "White Cabbage",
        "amount": "400g"
      },
      {
        "name": "Sweet Peppadew Peppers",
        "amount": "5"
      },
      {
        "name": "Mayonnaise",
        "amount": "3  tablespoons"
      },
      {
        "name": "Pita Bread",
        "amount": "4 large"
      }
    ],
    "steps": [
      "step 1",
      "Heat a griddle pan. Rub the lamb steaks with the oil, cumin and some seasoning. Griddle for about 3-4 mins on each side or until cooked to your liking. Place to one side on a plate to rest.",
      "step 2",
      "In a large bowl, stir the sugar into the vinegar until dissolved. Add the carrots, spring onions, cabbage and some seasoning, and toss together.",
      "step 3",
      "Blitz the whole peppers and the mayo in a food processor. Add a heap of the salad to each flatbread. Slice the lamb, trimming off any excess fat and lay on top of the salad, drizzling with the resting juices. Spoon over the mayo and scatter with a few of the sliced peppers. Roll up and eat. If using pitta, split and stuff. Serve any extra salad on the side."
    ],
    "source": "TheMealDB #53258"
  },
  {
    "id": "themealdb-hummus",
    "nameTr": "Hummus",
    "nameEn": "Hummus",
    "category": "main_veg",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Chickpeas",
        "amount": "400g"
      },
      {
        "name": "Tahini Paste",
        "amount": "1 tablespoon"
      },
      {
        "name": "Garlic Clove",
        "amount": "1 large"
      },
      {
        "name": "Greek Yogurt",
        "amount": "3  tablespoons"
      },
      {
        "name": "Lemon",
        "amount": "Juice of half"
      }
    ],
    "steps": [
      "step 1",
      "Drain the chickpeas into a sieve set over a bowl or jug to catch the liquid. Tip the chickpeas, tahini, garlic and yogurt into a food processor or blender and whizz to smooth.",
      "step 2",
      "Whizz in a tbsp of the chickpea liquid at a time until you have a nice consistency, then scrape into a bowl.",
      "step 3",
      "Stir in a squeeze of lemon juice and season to taste."
    ],
    "source": "TheMealDB #53269"
  },
  {
    "id": "themealdb-imam-bayildi-with-bbq-lamb-tzatziki",
    "nameTr": "Imam bayildi with BBQ lamb & tzatziki",
    "nameEn": "Imam bayildi with BBQ lamb & tzatziki",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Aubergine",
        "amount": "3"
      },
      {
        "name": "Olive Oil",
        "amount": "2 tablespoons"
      },
      {
        "name": "Onion",
        "amount": "1 chopped"
      },
      {
        "name": "Garlic",
        "amount": "2 cloves chopped"
      },
      {
        "name": "Cinnamon",
        "amount": "1 tsp"
      },
      {
        "name": "Tomato",
        "amount": "8"
      },
      {
        "name": "Parsley",
        "amount": "Bunch"
      },
      {
        "name": "Lamb Loin Chops",
        "amount": "12"
      },
      {
        "name": "Paprika",
        "amount": "Pinch"
      },
      {
        "name": "Lemon",
        "amount": "1"
      },
      {
        "name": "Greek Yogurt",
        "amount": "150g"
      },
      {
        "name": "Cucumber",
        "amount": "1/2"
      },
      {
        "name": "Mint",
        "amount": "2 tbs chopped"
      }
    ],
    "steps": [
      "step 1",
      "Heat oven to 190C/170C fan/gas 5. Halve the aubergines lengthways and score the flesh side deeply, brush with a good layer of olive oil and put on a baking sheet. Roast for 20 mins or until the flesh is soft enough to scoop out.",
      "step 2",
      "Fry the onion in a little oil until soft, add the garlic and cinnamon and fry for 1 min. Once the aubergines are cool enough to handle, scoop out the centres. Roughly chop the flesh and add it to the onions. Halve the tomatoes, scoop the seeds and juice into a sieve set over a bowl, then chop the flesh. Add the chopped tomatoes to the pan and cook everything for 10 mins until nice and soft. Add a little more oil if you need to. Stir in the parsley, leaving a little for scattering at the end.",
      "step 3",
      "Lay the aubergine halves in a baking dish and divide the tomato mixture between them. Pour over the juice from the tomatoes, drizzle with more olive oil and bake for 30 mins until the aubergines have collapsed.",
      "step 4",
      "Meanwhile, mix the tzatziki ingredients together and put in a small serving bowl.",
      "step 5",
      "Season the lamb with salt, black pepper and a pinch of paprika. Griddle, grill or barbecue for 3 mins on each side or until the fat is nicely browned, then put in a serving dish and squeeze over the lemon halves. Scatter the aubergines with parsley, then serve with the lamb and tzatziki."
    ],
    "source": "TheMealDB #53253"
  },
  {
    "id": "themealdb-kofta-burgers",
    "nameTr": "kofta burgers",
    "nameEn": "kofta burgers",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Lamb",
        "amount": "1kg"
      },
      {
        "name": "Onion",
        "amount": "2"
      },
      {
        "name": "Garlic Bulb",
        "amount": "1"
      },
      {
        "name": "Garam Masala",
        "amount": "6 tablespoons"
      },
      {
        "name": "Coriander",
        "amount": "Bunch"
      },
      {
        "name": "Chilli Sauce",
        "amount": "1 tablespoon"
      },
      {
        "name": "Pita Bread",
        "amount": "8"
      },
      {
        "name": "Tomato",
        "amount": "4 sliced"
      },
      {
        "name": "Red Cabbage",
        "amount": "1/2"
      },
      {
        "name": "Red Onions",
        "amount": "1 sliced"
      },
      {
        "name": "Yogurt",
        "amount": "Small pack"
      }
    ],
    "steps": [
      "step 1",
      "Tip the mince into a large bowl (use a clean washing-up bowl if you don’t have anything big enough) with all the other burger ingredients and a good pinch of salt. Roll up your sleeves, get your hands into the mix and squelch everything together through your fingers until completely mixed. Pat the mix into 16 small burgers. These may now be frozen for up to 1 month or chilled up to a day ahead.",
      "step 2",
      "To cook, heat grill to its highest setting and lay the burgers in a single layer on a baking tray (you may need to do this in batches, depending on how big your tray is). Grill on the highest shelf for 5-6 mins on each side until browned and cooked through. Pile burgers onto a platter and serve with all the accompaniments, so everyone can construct their own sandwich."
    ],
    "source": "TheMealDB #53257"
  },
  {
    "id": "themealdb-kumpir",
    "nameTr": "Kumpir",
    "nameEn": "Kumpir",
    "category": "main_veg",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Potatoes",
        "amount": "2 large"
      },
      {
        "name": "Butter",
        "amount": "2 tbs"
      },
      {
        "name": "Cheese",
        "amount": "150g"
      },
      {
        "name": "Onion",
        "amount": "1 large"
      },
      {
        "name": "Red Pepper",
        "amount": "1 large"
      },
      {
        "name": "Red Chilli Flakes",
        "amount": "Pinch"
      }
    ],
    "steps": [
      "If you order kumpir in Turkey, the standard filling is first, lots of butter mashed into the potato, followed by cheese. There’s then a row of other toppings that you can just point at to your heart’s content – sweetcorn, olives, salami, coleslaw, Russian salad, allsorts – and you walk away with an over-stuffed potato because you got ever-excited by the choices on offer.",
      "Grate (roughly – you can use as much as you like) 150g of cheese.",
      "Finely chop one onion and one sweet red pepper.",
      "Put these ingredients into a large bowl with a good sprinkling of salt and pepper, chilli flakes (optional)."
    ],
    "source": "TheMealDB #52978"
  },
  {
    "id": "themealdb-lamb-apricot-meatballs",
    "nameTr": "Lamb & apricot meatballs",
    "nameEn": "Lamb & apricot meatballs",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Olive Oil",
        "amount": "2 tablespoons"
      },
      {
        "name": "Red Onions",
        "amount": "2 chopped"
      },
      {
        "name": "Garlic",
        "amount": "4 Cloves Crushed"
      },
      {
        "name": "Ground Cumin",
        "amount": "2 tsp"
      },
      {
        "name": "Ground Coriander",
        "amount": "2 tsp"
      },
      {
        "name": "Tinned Tomatos",
        "amount": "400g"
      },
      {
        "name": "Sugar",
        "amount": "1/2 teaspoon"
      },
      {
        "name": "Mint",
        "amount": "10g"
      },
      {
        "name": "Lamb Mince",
        "amount": "500g"
      },
      {
        "name": "Dried Apricots",
        "amount": "8"
      },
      {
        "name": "Breadcrumbs",
        "amount": "50g"
      },
      {
        "name": "Pita Bread",
        "amount": "To serve"
      }
    ],
    "steps": [
      "step 1",
      "Heat 2 tsp oil in a pan and soften the onions for 5 mins. Add the garlic and spices and cook for a few mins more. Spoon half the onion mixture into a bowl and set aside to cool. Add the tomatoes, sugar and seasoning to the remaining onions in the pan and simmer for about 10 mins until reduced.",
      "step 2",
      "Meanwhile, add the mint, lamb, apricots and breadcrumbs to the cooled onions, season and mix well with your hands. Shape into little meatballs.",
      "step 3",
      "Heat the rest of the oil in a non-stick pan and fry the meatballs until golden (in batches if you need to). Stir in the sauce with a splash of water and gently cook everything for a few mins until the meatballs are cooked through. Serve with pitta bread and salad."
    ],
    "source": "TheMealDB #53277"
  },
  {
    "id": "themealdb-roast-aubergine-with-goat-s-cheese-toasted-flatbread",
    "nameTr": "Roast aubergine with goat's cheese & toasted flatbread",
    "nameEn": "Roast aubergine with goat's cheese & toasted flatbread",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Aubergine",
        "amount": "2 sliced"
      },
      {
        "name": "Extra Virgin Olive Oil",
        "amount": "3  tablespoons"
      },
      {
        "name": "Cherry Tomatoes",
        "amount": "12"
      },
      {
        "name": "Pita Bread",
        "amount": "1"
      },
      {
        "name": "Balsamic Vinegar",
        "amount": "3  tablespoons"
      },
      {
        "name": "Mint",
        "amount": "Handful"
      },
      {
        "name": "Shallots",
        "amount": "1 chopped"
      },
      {
        "name": "Shallots",
        "amount": "1 sliced"
      },
      {
        "name": "Red Chilli",
        "amount": "1 chopped"
      },
      {
        "name": "Goats Cheese",
        "amount": "50g"
      },
      {
        "name": "Rocket",
        "amount": "Handful"
      }
    ],
    "steps": [
      "step 1",
      "Heat oven to 200C/180C fan/gas 6. Brush the aubergine slices with 1 tbsp of the oil, then season. Arrange on a baking tray or sheet and roast for 20 mins until browned, popping the tomatoes on the tray for the final 5 mins. Tear the flatbread into pieces and place on a separate baking sheet. Brown in the oven for 8 mins, or until crisp, then remove.",
      "step 2",
      "For the dressing, in a small bowl, mix the vinegar, mint, chopped shallots, chilli, remaining oil and some salt and pepper.",
      "step 3",
      "Scatter the aubergine slices, tomatoes, sliced shallot and crisp flatbread into a serving bowl. Pour over the dressing, sprinkle with the goat’s cheese and scatter over a little rocket."
    ],
    "source": "TheMealDB #53273"
  },
  {
    "id": "themealdb-roasted-chicken-with-creamy-walnut-sauce",
    "nameTr": "Roasted chicken with creamy walnut sauce",
    "nameEn": "Roasted chicken with creamy walnut sauce",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Chicken Thighs",
        "amount": "8"
      },
      {
        "name": "Cumin",
        "amount": "1 tsp"
      },
      {
        "name": "Paprika",
        "amount": "1/2 tsp"
      },
      {
        "name": "Olive Oil",
        "amount": "2 tablespoons"
      },
      {
        "name": "Pita Bread",
        "amount": "6"
      },
      {
        "name": "Chicken Stock",
        "amount": "150ml"
      },
      {
        "name": "Walnuts",
        "amount": "175g"
      },
      {
        "name": "Onion",
        "amount": "1 chopped"
      },
      {
        "name": "Garlic",
        "amount": "2 cloves chopped"
      },
      {
        "name": "Single Cream",
        "amount": "50 ml"
      },
      {
        "name": "Lemon",
        "amount": "Juice of 1"
      },
      {
        "name": "Coriander",
        "amount": "Handful"
      }
    ],
    "steps": [
      "step 1",
      "Heat oven to 200C/180C fan/gas 6. In a roasting tin, toss together the chicken, cumin, paprika, 1 tbsp olive oil and seasoning. Cook for 40 mins until the chicken is crisp and cooked through.",
      "step 2",
      "Meanwhile, tear up 1 pitta bread and place in a small bowl. Pour over a couple of tbsp chicken stock and leave to soak. Dry-fry the walnuts in a frying pan for about 3 mins until golden and toasted. Set aside. Heat the remaining oil in the pan and cook the onion and garlic until softened. Place the softened pitta bread, onion mixture and most of the nuts into a blender. Pour over the rest of the chicken stock and whizz together until a rough paste forms. Return the mixture to the pan. Add the cream and lemon juice, season and keep warm.",
      "step 3",
      "When the chicken is cooked, arrange on a platter. Stir the coriander through the sauce and spoon into a bowl. Roughly chop the remaining walnuts and scatter over the chicken. Toast the pittas, cut into wedges and serve alongside"
    ],
    "source": "TheMealDB #53268"
  },
  {
    "id": "themealdb-slow-roast-lamb-with-cinnamon-fennel-citrus",
    "nameTr": "Slow-roast lamb with cinnamon, fennel & citrus",
    "nameEn": "Slow-roast lamb with cinnamon, fennel & citrus",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Lamb Leg",
        "amount": "1"
      },
      {
        "name": "Lemon",
        "amount": "Zest and juice of 1"
      },
      {
        "name": "Olive Oil",
        "amount": "4 tablespoons"
      },
      {
        "name": "Clear Honey",
        "amount": "2 tablespoons"
      },
      {
        "name": "Cinnamon",
        "amount": "1 tablespoon"
      },
      {
        "name": "Fennel Seeds",
        "amount": "1 tablespoon"
      },
      {
        "name": "Ground Cumin",
        "amount": "1 tablespoon"
      },
      {
        "name": "Garlic",
        "amount": "3 Cloves Crushed"
      }
    ],
    "steps": [
      "step 1",
      "Put the lamb into a large food bag with all the juice and marinate overnight.",
      "step 2",
      "The next day, take the lamb out of the fridge 1 hr before you want to cook it. Heat oven to 220C/200C fan/gas 7. Take the lamb out of the marinade (reserve remaining marinade) and pat dry. Rub with half the oil and roast for 15-20 mins until browned. Remove lamb and reduce oven to 160C/140C fan/gas 3.",
      "step 3",
      "Mix the zests, remaining oil, honey, spices and garlic with plenty of seasoning. Lay a large sheet of baking parchment on a large sheet of foil. Sit the lamb leg on top, rub all over with the paste and pull up the sides of the foil. Drizzle marinade into base, and scrunch foil to seal.",
      "step 4",
      "Roast for 4 hrs, until very tender. Rest, still wrapped, for 30 mins. Unwrap and serve with juices."
    ],
    "source": "TheMealDB #53260"
  },
  {
    "id": "themealdb-smoked-aubergine-puree",
    "nameTr": "Smoked aubergine purée",
    "nameEn": "Smoked aubergine purée",
    "category": "main_veg",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Aubergine",
        "amount": "2 medium"
      },
      {
        "name": "Lemon",
        "amount": "Juice of 1"
      },
      {
        "name": "Garlic",
        "amount": "3 Cloves Crushed"
      },
      {
        "name": "Yogurt",
        "amount": "150ml"
      },
      {
        "name": "Dill",
        "amount": "Bunch"
      }
    ],
    "steps": [
      "step 1",
      "Heat grill to very hot. Slice the aubergines in half lengthways, then grill for 25 mins, turning occasionally, until soft – the skin will remain firm, but the flesh will soften. Lift the aubergines off the grill and leave until cool enough to handle.",
      "step 2",
      "Using a sharp knife, score the grilled flesh and scoop out the flesh with a spoon. Tip into a bowl and mash with a fork until you get a thick pulp. Beat in the lemon juice and garlic. Add the yogurt and dill, and season. Serve while still warm."
    ],
    "source": "TheMealDB #53259"
  },
  {
    "id": "themealdb-smoky-chicken-skewers",
    "nameTr": "Smoky chicken skewers",
    "nameEn": "Smoky chicken skewers",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Chicken Thighs",
        "amount": "6"
      },
      {
        "name": "Olive Oil",
        "amount": "2 tablespoons"
      },
      {
        "name": "Fennel Seeds",
        "amount": "1 tsp"
      },
      {
        "name": "Ground Cumin",
        "amount": "1 tsp"
      },
      {
        "name": "sweet smoked paprika",
        "amount": "1 tsp"
      },
      {
        "name": "Garlic",
        "amount": "1 clove peeled crushed"
      },
      {
        "name": "Red Wine Vinegar",
        "amount": "1 tsp"
      },
      {
        "name": "Smoky Aïoli",
        "amount": "To serve"
      }
    ],
    "steps": [
      "step 1",
      "You need 15 skewers: if wooden, soak in water for 10 mins. Cut chicken into 3cm pieces and place in a bowl. Add 1 tbsp olive oil, the spices, garlic and vinegar, toss well and season. You can do this up to a day before and refrigerate.",
      "step 2",
      "Thread 2-3 pieces on each skewer. Pour remaining oil in a frying pan or rub onto a griddle pan. Get the pan hot and sear the chicken for 3-4 mins on each side – you may have to do this in batches, keeping the cooked skewers warm in a low oven. Serve with smoky aïoli if you like."
    ],
    "source": "TheMealDB #53264"
  },
  {
    "id": "themealdb-sweet-potato-salad",
    "nameTr": "Sweet potato salad",
    "nameEn": "Sweet potato salad",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Sweet Potatoes",
        "amount": "1200g"
      },
      {
        "name": "Olive Oil",
        "amount": "1 tablespoon"
      },
      {
        "name": "Shallots",
        "amount": "2"
      },
      {
        "name": "Spring Onions",
        "amount": "4 sliced"
      },
      {
        "name": "Chives",
        "amount": "Bunch"
      },
      {
        "name": "Sherry vinegar",
        "amount": "5 tablespoons"
      },
      {
        "name": "Extra Virgin Olive Oil",
        "amount": "2 tablespoons"
      },
      {
        "name": "Honey",
        "amount": "2 tablespoons"
      }
    ],
    "steps": [
      "step 1",
      "Heat oven to 200C/180C fan/gas 6. Toss the sweet potato chunks with the olive oil and some seasoning, and spread on a baking parchment-lined baking sheet. Roast for 30 - 35 mins until tender and golden. Cool at room temperature.",
      "step 2",
      "When just about cool whisk together all the dressing ingredients with a little more seasoning and gently toss through the potato chunks – use your hands to avoid breaking them up."
    ],
    "source": "TheMealDB #53275"
  },
  {
    "id": "themealdb-turkish-lamb-pilau",
    "nameTr": "Turkish lamb pilau",
    "nameEn": "Turkish lamb pilau",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Pine Nuts",
        "amount": "Handful"
      },
      {
        "name": "Olive Oil",
        "amount": "1 tablespoon"
      },
      {
        "name": "Onion",
        "amount": "1 Large Chopped"
      },
      {
        "name": "Cinnamon",
        "amount": "2"
      },
      {
        "name": "Lamb",
        "amount": "500g"
      },
      {
        "name": "Basmati Rice",
        "amount": "250g"
      },
      {
        "name": "Lamb Stock",
        "amount": "1"
      },
      {
        "name": "Dried Apricots",
        "amount": "12"
      },
      {
        "name": "Mint",
        "amount": "Handful"
      }
    ],
    "steps": [
      "step 1",
      "Dry-fry the pine nuts or almonds in a large pan until lightly toasted, then tip onto a plate. Add the oil to the pan, then fry the onion and cinnamon together until starting to turn golden. Turn up the heat, stir in the lamb, fry until the meat changes colour, then tip in the rice and cook for 1 min, stirring all the time.",
      "step 2",
      "Pour in 500ml boiling water, crumble in the stock cube, add the apricots, then season to taste. Turn the heat down, cover and simmer for 12 mins until the rice is tender and the stock has been absorbed. Toss in the pine nuts and mint and serve."
    ],
    "source": "TheMealDB #53263"
  },
  {
    "id": "themealdb-turkish-rice-vermicelli-rice",
    "nameTr": "Turkish rice (vermicelli rice)",
    "nameEn": "Turkish rice (vermicelli rice)",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Rice",
        "amount": "300g"
      },
      {
        "name": "Vegetable Oil",
        "amount": "3  tablespoons"
      },
      {
        "name": "Vermicelli Pasta",
        "amount": "70g"
      },
      {
        "name": "Unsalted Butter",
        "amount": "30g"
      },
      {
        "name": "Chicken Stock",
        "amount": "600ml"
      }
    ],
    "steps": [
      "step 1",
      "Pour the rice into a very large bowl under cold running water and carefully drain the water out of the bowl through a sieve. Repeat a few times until the water in the bowl is clear, then fill the bowl up with cold water and leave rice to soak for 10 mins while you cook the vermicelli.",
      "step 2",
      "Put the oil into a medium pan over medium heat. Add the vermicelli and stir continuously until the strands turn a rich golden brown, 2-3 mins. Remove from the heat, stir through the butter until it melts and allow the vermicelli to cool for 1-2 mins.",
      "step 3",
      "Drain the rice thoroughly through a sieve. Add the rice to the pan and stir well. Pour the hot stock into the pan, sprinkle in ½ tsp salt, stir well then return the pan to the hob over a high heat. Bring to the boil, then reduce the heat to the lowest it will go, put the lid on the pan and simmer for 7-9 mins. Remove the pan from the heat, cover with a couple of sheets of kitchen paper or a light tea towel and the pan lid, and let the rice sit in the pan for 10 mins. Fluff up with a fork before serving."
    ],
    "source": "TheMealDB #53252"
  },
  {
    "id": "themealdb-turkish-style-lamb",
    "nameTr": "Turkish-style lamb",
    "nameEn": "Turkish-style lamb",
    "category": "main_meat",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Lamb Leg",
        "amount": "4"
      },
      {
        "name": "Seasoning",
        "amount": "2 tsp"
      },
      {
        "name": "Dried Oregano",
        "amount": "1 tsp"
      },
      {
        "name": "Mint",
        "amount": "Bunch"
      },
      {
        "name": "Yogurt",
        "amount": "300g"
      },
      {
        "name": "Pita Bread",
        "amount": "4"
      },
      {
        "name": "Iceberg Lettuce",
        "amount": "1/2"
      },
      {
        "name": "Red Onions",
        "amount": "1 sliced"
      },
      {
        "name": "Lemon",
        "amount": "1"
      }
    ],
    "steps": [
      "step 1",
      "Heat grill to high. Season the lamb, then grill for 2 mins on each side until browned, but still very rare. Meanwhile, mix the seasoning, oregano and half of the mint into one of the tubs of yogurt, smother this over the lamb, then return to the grill for another 2-3 mins or until the yogurt is blistered and the meat is cooked to your liking.",
      "step 2",
      "Leave the meat to rest on a board for a few mins while you toast the pittas, shred the lettuce and thinly slice the red onion. Stir the rest of the mint into the second tub of yogurt. Thickly slice the meat and stuff into the pitta bread with the salad and minted yogurt. Squeeze over lemon juice before tucking in, if you like."
    ],
    "source": "TheMealDB #53270"
  },
  {
    "id": "themealdb-walnut-date-honey-cake",
    "nameTr": "Walnut, date & honey cake",
    "nameEn": "Walnut, date & honey cake",
    "category": "dessert",
    "cuisine": "turkish",
    "servings": 4,
    "prepMinutes": 15,
    "cookMinutes": 30,
    "difficulty": "medium",
    "tags": [
      "themealdb"
    ],
    "ingredients": [
      {
        "name": "Self-raising Flour",
        "amount": "225g"
      },
      {
        "name": "Ground Cinnamon",
        "amount": "1/2 teaspoon"
      },
      {
        "name": "Butter",
        "amount": "175g"
      },
      {
        "name": "Muscovado Sugar",
        "amount": "100g"
      },
      {
        "name": "Clear Honey",
        "amount": "3  tablespoons"
      },
      {
        "name": "Egg",
        "amount": "2 Beaten"
      },
      {
        "name": "Banana",
        "amount": "2 medium"
      },
      {
        "name": "Stoned Dates",
        "amount": "100g"
      },
      {
        "name": "Walnuts",
        "amount": "50g"
      }
    ],
    "steps": [
      "step 1",
      "Preheat the oven to 160C/Gas 3/fan oven 140C. Line the base and long sides of a 900g/2lb loaf tin with greaseproof paper, buttering the tin and paper.",
      "step 2",
      "Tip the flour, cinnamon, butter, sugar, 2 tablespoons of the honey and the eggs into a large mixing bowl. Mash the bananas and chop the dates (kitchen scissors are easiest for this) and add to the bowl. Beat the mixture for 2-3 minutes, using a wooden spoon or hand-held mixer, until well blended.",
      "step 3",
      "Spoon into the prepared tin and level the top. Scatter the walnut pieces over. Bake for 1 hour, then lightly press the top – it will feel firm if cooked. If not, bake for a further 10 minutes.",
      "step 4",
      "Cool for 15 minutes, then lift out of the tin using the paper. When cold, drizzle the remaining honey over. Cut into thick slices."
    ],
    "source": "TheMealDB #53271"
  }
];
