import type { RecipeSeed } from './_types.js';

export const meatMains: RecipeSeed[] = [
  {
    id: 'izgara-kofte',
    nameTr: 'Izgara Köfte',
    nameEn: 'Grilled Meatballs',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 15,
    difficulty: 'easy',
    tags: ['traditional', 'high_protein'],
    ingredients: [
      { name: 'Dana kıyma (orta yağlı)', amount: '500 g', grams: 500 },
      { name: 'Kuru soğan (rende)', amount: '1 adet' },
      { name: 'Sarımsak (ezilmiş)', amount: '2 diş' },
      { name: 'Eski ekmek içi', amount: '1 dilim' },
      { name: 'Yumurta', amount: '1 adet' },
      { name: 'Tuz, karabiber, kimyon', amount: 'tatmınıza göre' },
      { name: 'Kuru kekik', amount: '1 çay kaşığı' },
    ],
    steps: [
      'Ekmek içini biraz su ile ıslatıp sıkın.',
      'Tüm malzemeleri iyice yoğurun; en az 30 dakika buzdolabında dinlendirin.',
      'Elinizi ıslatarak köfte şekilleri verin.',
      'Izgara veya tavada her iki yüzünü 3-4 dakika pişirin.',
      'Kekik serperek, közlenmiş biber ve pilav ile servis edin.',
    ],
    nutritionPerServing: { kcal: 340, proteinG: 28, carbsG: 5, fatG: 22 },
  },
  {
    id: 'sulu-kofte',
    nameTr: 'Sulu Köfte',
    nameEn: 'Meatballs in Tomato Sauce',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 35,
    difficulty: 'easy',
    tags: ['traditional', 'comfort'],
    ingredients: [
      { name: 'Dana kıyma', amount: '400 g', grams: 400 },
      { name: 'Pirinç', amount: '2 yemek kaşığı' },
      { name: 'Soğan', amount: '2 adet' },
      { name: 'Patates', amount: '2 adet' },
      { name: 'Havuç', amount: '1 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Biber salçası', amount: '1 tatlı kaşığı' },
      { name: 'Sıvı yağ', amount: '2 yemek kaşığı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '4 su bardağı' },
    ],
    steps: [
      'Kıymayı bir soğan rendesi, pirinç, tuz ve karabiber ile yoğurun; küçük köfteler yapın.',
      'Tencerede yağı ısıtıp ince doğranmış diğer soğanı kavurun.',
      'Salçaları ekleyip 1 dakika çevirin.',
      'Küp küp patates, havuç ve köfteleri tencereye dizin.',
      'Sıcak su ve baharatları ekleyip kaynatın.',
      'Kısık ateşte kapağı örtülü 25 dakika pişirin; su azaldıysa ekleyin.',
    ],
    nutritionPerServing: { kcal: 380, proteinG: 24, carbsG: 30, fatG: 19 },
  },
  {
    id: 'kuru-fasulye-etli',
    nameTr: 'Etli Kuru Fasulye',
    nameEn: 'White Beans with Beef',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 5,
    prepMinutes: 480,
    cookMinutes: 90,
    difficulty: 'medium',
    tags: ['traditional', 'comfort', 'high_protein'],
    ingredients: [
      { name: 'Kuru fasulye (gece suda)', amount: '2 su bardağı', grams: 360 },
      { name: 'Dana kuşbaşı', amount: '300 g', grams: 300 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Domates', amount: '1 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Biber salçası', amount: '1 tatlı kaşığı' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Sıvı yağ', amount: '2 yemek kaşığı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '5 su bardağı' },
    ],
    steps: [
      'Fasulyeleri bir gece öncesinden ılık suda bekletin, süzün.',
      'Yağ ve tereyağı karışımında kuşbaşı eti kavurun, suyunu çekip kızarsın.',
      'Doğranmış soğanı ekleyip pembeleşene kadar kavurun.',
      'Salçaları ekleyin; rende domatesi de ilave edin.',
      'Süzülmüş fasulye ve sıcak suyu ekleyin; kaynatın.',
      'Düdüklüde 25-30 dakika, tencerede 60-75 dakika pişirin.',
      'Baharatları ekleyip 5 dakika daha kaynatın; pilav ile servis edin.',
    ],
    nutritionPerServing: { kcal: 450, proteinG: 28, carbsG: 40, fatG: 18 },
  },
  {
    id: 'nohutlu-tavuk',
    nameTr: 'Nohutlu Tavuk Sulu Yemek',
    nameEn: 'Chicken with Chickpeas',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 40,
    difficulty: 'easy',
    tags: ['high_protein', 'healthy'],
    ingredients: [
      { name: 'Tavuk but (kemiksiz)', amount: '500 g', grams: 500 },
      { name: 'Haşlanmış nohut', amount: '1,5 su bardağı', grams: 270 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Biber salçası', amount: '1 tatlı kaşığı' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Tuz, karabiber, kimyon', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '2,5 su bardağı' },
    ],
    steps: [
      'Tavukları küp doğrayın; tencerede yağ ile suyunu çekene dek kavurun.',
      'İnce doğranmış soğanı ekleyip yumuşatın.',
      'Salçaları ekleyip 1 dakika çevirin.',
      'Nohut ve sıcak suyu ilave edin; baharatları ekleyin.',
      'Kapak kapalı kısık ateşte 25-30 dakika pişirin; suyu koyulaşsın.',
    ],
    nutritionPerServing: { kcal: 360, proteinG: 32, carbsG: 22, fatG: 15 },
  },
  {
    id: 'tavuklu-sebzeli-sote',
    nameTr: 'Tavuklu Sebzeli Sote',
    nameEn: 'Chicken & Vegetable Sauté',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    difficulty: 'easy',
    tags: ['high_protein', 'quick', 'healthy', 'student_friendly'],
    ingredients: [
      { name: 'Tavuk göğüs (küp)', amount: '500 g', grams: 500 },
      { name: 'Kapya biber', amount: '1 adet' },
      { name: 'Yeşil biber', amount: '1 adet' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Mantar', amount: '150 g', grams: 150 },
      { name: 'Domates', amount: '2 adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Tuz, karabiber, kekik, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Tavukları marine etmek için yarım çay kaşığı tuz, karabiber ve biraz yağ ile 10 dakika bekletin.',
      'Tavada yağı kızdırın, tavukları suyunu çekene dek soteleyin.',
      'Soğan, sarımsak ve biberleri ekleyip 5 dakika pişirin.',
      'Mantarları ekleyip suyunu çekene kadar çevirin.',
      'Rende domatesi ekleyin; 5 dakika daha pişirin.',
      'Baharatları ekleyip servis edin.',
    ],
    nutritionPerServing: { kcal: 300, proteinG: 32, carbsG: 10, fatG: 14 },
  },
  {
    id: 'firinda-tavuk-but',
    nameTr: 'Fırında Sebzeli Tavuk But',
    nameEn: 'Baked Chicken Thighs with Vegetables',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 55,
    difficulty: 'easy',
    tags: ['oven', 'healthy', 'one_pan'],
    ingredients: [
      { name: 'Tavuk but', amount: '4 adet', grams: 700 },
      { name: 'Patates', amount: '3 adet' },
      { name: 'Havuç', amount: '2 adet' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Kapya biber', amount: '1 adet' },
      { name: 'Zeytinyağı', amount: '4 yemek kaşığı' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Sarımsak', amount: '4 diş' },
      { name: 'Limon suyu', amount: '2 yemek kaşığı' },
      { name: 'Tuz, karabiber, kekik, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Fırını 200°C\'de ısıtın.',
      'Tavukları yıkayıp kurulayın; yağ, salça, ezilmiş sarımsak, limon ve baharatlarla marine edin.',
      'Sebzeleri iri parçalara doğrayıp fırın tepsisine dizin; üzerlerine de yağ ve tuz.',
      'Marine tavukları sebzelerin üzerine koyun.',
      '200°C fırında 45-55 dakika, tavuk tamamen pişene kadar kızartın.',
      'Son 5 dakika üst grill açabilirsiniz.',
    ],
    nutritionPerServing: { kcal: 520, proteinG: 35, carbsG: 30, fatG: 27 },
  },
  {
    id: 'etli-biber-dolma',
    nameTr: 'Etli Biber Dolma',
    nameEn: 'Stuffed Peppers with Meat',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 25,
    cookMinutes: 60,
    difficulty: 'medium',
    tags: ['traditional'],
    ingredients: [
      { name: 'Dolmalık biber', amount: '8 adet' },
      { name: 'Dana kıyma', amount: '300 g', grams: 300 },
      { name: 'Baldo pirinç', amount: '1 su bardağı', grams: 180 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Domates', amount: '2 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Maydanoz, nane, dereotu', amount: 'yarım demet' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '2 su bardağı' },
    ],
    steps: [
      'Pirinci yıkayıp tuzlu suda 20 dakika bekletin.',
      'Tavada yağı ısıtıp ince soğanı kavurun.',
      'Kıymayı ekleyip suyunu çekene kadar pişirin.',
      'Salça, rende domates ve süzülmüş pirinci ekleyin; 2-3 dakika çevirin.',
      'Yeşillikleri ve baharatları ekleyin; harcı soğutun.',
      'Biberlerin içini temizleyip harçla doldurun.',
      'Tencerede biberleri dik dizin; üzerlerine 1 domates dilimi koyun.',
      'Sıcak su ve biraz tuz ekleyip kapağını kapatın; 45 dakika kısık ateşte pişirin.',
    ],
    nutritionPerServing: { kcal: 420, proteinG: 20, carbsG: 45, fatG: 16 },
  },
  {
    id: 'kiymali-ispanak',
    nameTr: 'Kıymalı Ispanak',
    nameEn: 'Spinach with Ground Beef',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['healthy', 'iron_rich', 'quick'],
    ingredients: [
      { name: 'Ispanak', amount: '750 g', grams: 750 },
      { name: 'Dana kıyma', amount: '250 g', grams: 250 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Pirinç', amount: '2 yemek kaşığı' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '1,5 su bardağı' },
    ],
    steps: [
      'Ispanağı iyice yıkayıp iri doğrayın.',
      'Yağda soğanı kavurun, kıymayı ekleyip suyunu çekirin.',
      'Salçayı ekleyip çevirin; pirinç ve sıcak suyu ilave edin.',
      'Ispanakları ekleyip karıştırın, suyu çekmeye başlayınca baharatları atın.',
      'Kısık ateşte kapak örtülü 15 dakika pişirin.',
      'Sarımsaklı yoğurt ile servis edin.',
    ],
    nutritionPerServing: { kcal: 280, proteinG: 20, carbsG: 18, fatG: 14 },
  },
  {
    id: 'beyti-sis',
    nameTr: 'Beyti Köfte / Kaşarlı Köfte',
    nameEn: 'Beyti Kebab',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 15,
    difficulty: 'medium',
    tags: ['traditional', 'high_protein'],
    ingredients: [
      { name: 'Dana kıyma (yağlı)', amount: '500 g', grams: 500 },
      { name: 'Kuru soğan', amount: '1 adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Kaşar peyniri', amount: '100 g', grams: 100 },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Tuz, karabiber, kimyon, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Soğan, sarımsak ve maydanozu rondodan geçirin.',
      'Kıyma ile birlikte baharatları ekleyip en az 10 dakika yoğurun.',
      'Harcı şiş veya ince uzun köfte formuna getirin.',
      'Tava veya ızgarada her tarafı 3-4 dakika pişirin.',
      'Üstlerine rendelenmiş kaşar serpip 2 dakika daha fırında bekletin.',
      'Yufkalarla sararak lavaş gibi servis edin.',
    ],
    nutritionPerServing: { kcal: 450, proteinG: 34, carbsG: 5, fatG: 32 },
  },
  {
    id: 'hasan-pasa-kofte',
    nameTr: 'Hasanpaşa Köfte',
    nameEn: 'Hasan Pasha Meatballs',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 25,
    cookMinutes: 40,
    difficulty: 'medium',
    tags: ['traditional', 'comfort'],
    ingredients: [
      { name: 'Dana kıyma', amount: '500 g', grams: 500 },
      { name: 'Kuru soğan (rende)', amount: '1 adet' },
      { name: 'Yumurta', amount: '1 adet' },
      { name: 'Galeta unu', amount: '3 yemek kaşığı' },
      { name: 'Patates', amount: '600 g', grams: 600 },
      { name: 'Süt', amount: 'yarım su bardağı' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Kaşar peyniri', amount: '80 g', grams: 80 },
      { name: 'Domates sosu (salça + su)', amount: '1 su bardağı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Kıyma, rende soğan, yumurta, galeta unu ve baharatları yoğurun.',
      'Harcı fırın kabına yayın; her köfte yerine çukur açın.',
      'Patatesleri haşlayıp tereyağı ve sütle püre yapın.',
      'Her çukura 1 yemek kaşığı püre koyup üstüne rende kaşar serpin.',
      'Kenarlara domates sosunu dökün.',
      '180°C fırında 30-40 dakika, üzeri kızarana dek pişirin.',
    ],
    nutritionPerServing: { kcal: 520, proteinG: 30, carbsG: 38, fatG: 26 },
  },
  {
    id: 'kuzu-kapama',
    nameTr: 'Kuzu Kapama',
    nameEn: 'Lamb Kapama',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 5,
    prepMinutes: 15,
    cookMinutes: 90,
    difficulty: 'medium',
    tags: ['traditional', 'high_protein'],
    ingredients: [
      { name: 'Kuzu kuşbaşı', amount: '700 g', grams: 700 },
      { name: 'Kuru soğan', amount: '2 adet' },
      { name: 'Marul veya pazı yaprağı', amount: '1 baş' },
      { name: 'Taze soğan', amount: '1 demet' },
      { name: 'Dereotu', amount: 'yarım demet' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Limon', amount: '1 adet' },
      { name: 'Sıcak su', amount: '3 su bardağı' },
    ],
    steps: [
      'Tencerede tereyağını eritin, kuşbaşı eti suyunu çekip hafif kızartın.',
      'Doğranmış kuru soğanı ekleyip kavurun.',
      'Sıcak su ekleyip kapağı kapalı 50 dakika, etler yumuşayana dek pişirin.',
      'İri doğranmış marul/pazı ve taze soğanı ekleyin.',
      '20 dakika daha kısık ateşte pişirin; dereotu ekleyin.',
      'Tuz, karabiber ve limon sıkarak servis edin.',
    ],
    nutritionPerServing: { kcal: 440, proteinG: 34, carbsG: 10, fatG: 28 },
  },
  {
    id: 'piliç-sis',
    nameTr: 'Piliç Şiş',
    nameEn: 'Chicken Skewers',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 75,
    cookMinutes: 15,
    difficulty: 'easy',
    tags: ['high_protein', 'grill'],
    ingredients: [
      { name: 'Tavuk göğüs (küp)', amount: '600 g', grams: 600 },
      { name: 'Yoğurt', amount: 'yarım su bardağı' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Limon suyu', amount: '2 yemek kaşığı' },
      { name: 'Domates salçası', amount: '1 tatlı kaşığı' },
      { name: 'Sarımsak', amount: '3 diş' },
      { name: 'Tuz, karabiber, kekik, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Marinade için: yoğurt, yağ, limon, salça, ezilmiş sarımsak ve baharatları karıştırın.',
      'Tavuk küplerini marinad ile karıştırıp en az 1 saat buzdolabında bekletin.',
      'Şişlere dizin (arada isteğe göre biber/soğan).',
      'Sıcak ızgara veya tavada her yüzünü 3-4 dakika pişirin.',
      'Sumak soğan ve bulgur pilavı ile servis edin.',
    ],
    nutritionPerServing: { kcal: 340, proteinG: 40, carbsG: 3, fatG: 18 },
  },
  {
    id: 'etli-nohut',
    nameTr: 'Etli Nohut',
    nameEn: 'Chickpea Stew with Beef',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 5,
    prepMinutes: 480,
    cookMinutes: 90,
    difficulty: 'easy',
    tags: ['traditional', 'high_protein', 'budget'],
    ingredients: [
      { name: 'Kuru nohut (gece suda)', amount: '2 su bardağı', grams: 360 },
      { name: 'Dana kuşbaşı', amount: '300 g', grams: 300 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Biber salçası', amount: '1 tatlı kaşığı' },
      { name: 'Sıvı yağ', amount: '3 yemek kaşığı' },
      { name: 'Tuz, karabiber, kimyon', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '5 su bardağı' },
    ],
    steps: [
      'Nohutu bir gece öncesinden suda bekletin, süzün.',
      'Tencerede yağı ısıtın; eti suyunu çekip kızarana kadar kavurun.',
      'Soğanı ekleyip pembeleştirin; salçaları ekleyin.',
      'Nohut ve sıcak suyu ekleyip kaynatın.',
      'Düdüklüde 25 dakika, tencerede 75 dakika pişirin.',
      'Baharatları ekleyip son 5 dakika daha kaynatın.',
    ],
    nutritionPerServing: { kcal: 420, proteinG: 28, carbsG: 42, fatG: 15 },
  },
  {
    id: 'kayseri-mantisi',
    nameTr: 'Kayseri Mantısı',
    nameEn: 'Kayseri Manti',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 60,
    cookMinutes: 15,
    difficulty: 'hard',
    tags: ['traditional'],
    ingredients: [
      { name: 'Un', amount: '3 su bardağı' },
      { name: 'Yumurta', amount: '1 adet' },
      { name: 'Su', amount: 'yarım su bardağı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Dana kıyma', amount: '200 g', grams: 200 },
      { name: 'Soğan (rende)', amount: '1 adet' },
      { name: 'Sarımsaklı yoğurt', amount: '2 su bardağı' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Domates salçası', amount: '1 tatlı kaşığı' },
      { name: 'Pul biber, nane', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Un, yumurta, su ve tuzla sert bir hamur yoğurup 30 dakika dinlendirin.',
      'İç harç için kıyma, rende soğan, tuz ve karabiberi karıştırın.',
      'Hamuru ince açın, küçük karelere bölün.',
      'Her karenin ortasına nohut büyüklüğünde harç koyup dört kenarı kapatıp sıkıştırın.',
      'Kaynar tuzlu suda 8-10 dakika haşlayın; süzün.',
      'Üzerine sarımsaklı yoğurt; ayrı tavada tereyağı + salça + pul biberi kızdırıp gezdirin.',
      'Nane ile süsleyip servis edin.',
    ],
    nutritionPerServing: { kcal: 550, proteinG: 24, carbsG: 70, fatG: 20 },
  },
  {
    id: 'balik-firinda',
    nameTr: 'Fırında Levrek',
    nameEn: 'Baked Sea Bass',
    category: 'main_meat',
    cuisine: 'turkish',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['seafood', 'healthy', 'high_protein', 'omega3'],
    ingredients: [
      { name: 'Levrek (temizlenmiş)', amount: '2 adet', grams: 500 },
      { name: 'Limon', amount: '1 adet' },
      { name: 'Sarımsak', amount: '3 diş' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Taze biberiye veya kekik', amount: '1 dal' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Cherry domates', amount: '10 adet' },
    ],
    steps: [
      'Fırını 200°C\'ye ısıtın.',
      'Balıkları yıkayıp kurulayın; iç ve dışlarına tuz, karabiber sürün.',
      'Karın boşluğuna limon dilimleri, ezilmiş sarımsak ve maydanoz koyun.',
      'Balıkları yağlı kağıt serili tepsiye alın; üzerlerine zeytinyağı gezdirin.',
      'Kenarlara cherry domatesleri yerleştirin.',
      'Fırında 20-25 dakika pişirin; üzerini 2 dakika grill yapın.',
      'Limon ve salata ile servis edin.',
    ],
    nutritionPerServing: { kcal: 320, proteinG: 34, carbsG: 6, fatG: 18 },
  },
];
