import type { RecipeSeed } from './_types.js';

export const meze: RecipeSeed[] = [
  {
    id: 'haydari',
    nameTr: 'Haydari',
    nameEn: 'Turkish Yogurt Dip',
    category: 'meze',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['vegetarian', 'quick'],
    ingredients: [
      { name: 'Süzme yoğurt', amount: '2 su bardağı' },
      { name: 'Beyaz peynir', amount: '50 g' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Dereotu, nane', amount: '2 dal' },
      { name: 'Zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Tuz', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Yoğurt, ufalanmış peynir ve ezilmiş sarımsağı karıştırın.',
      'Kıyılmış yeşillikleri ekleyin.',
      'Zeytinyağını gezdirip servis edin.',
    ],
    nutritionPerServing: { kcal: 140, proteinG: 9, carbsG: 6, fatG: 9 },
  },
  {
    id: 'kiymali-hummus',
    nameTr: 'Humus',
    nameEn: 'Hummus',
    category: 'meze',
    cuisine: 'mediterranean',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'quick', 'high_protein'],
    ingredients: [
      { name: 'Haşlanmış nohut', amount: '2 su bardağı' },
      { name: 'Tahin', amount: '3 yemek kaşığı' },
      { name: 'Limon suyu', amount: '3 yemek kaşığı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Kimyon, tuz', amount: 'tatmınıza göre' },
      { name: 'Soğuk su', amount: 'kıvam için' },
    ],
    steps: [
      'Nohut, tahin, limon ve sarımsağı rondoya alın.',
      'Yavaşça yağ ve soğuk su ekleyerek pürüzsüz kıvam elde edin.',
      'Kimyon ve tuzla tatlandırın.',
      'Tabağa alıp üstüne yağ, sumak veya kırmızı biber serpin.',
    ],
    nutritionPerServing: { kcal: 240, proteinG: 10, carbsG: 22, fatG: 14 },
  },
  {
    id: 'patlican-salatasi',
    nameTr: 'Közlenmiş Patlıcan Salatası',
    nameEn: 'Roasted Eggplant Dip',
    category: 'meze',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 30,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'traditional'],
    ingredients: [
      { name: 'Patlıcan', amount: '3 adet' },
      { name: 'Yoğurt (opsiyonel)', amount: 'yarım su bardağı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Limon suyu', amount: '2 yemek kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Maydanoz', amount: '2 dal' },
    ],
    steps: [
      'Patlıcanları direk alevde veya 220°C fırında közleyin (20-25 dk).',
      'Kabuklarını soyup dikkatlice çatalla ezin; acı suyunu süzün.',
      'Ezilmiş sarımsak, yoğurt, yağ, limon ve tuzu ekleyin.',
      'Soğuk servis edin; üzerine maydanoz serpin.',
    ],
    nutritionPerServing: { kcal: 150, proteinG: 3, carbsG: 12, fatG: 11 },
  },
  {
    id: 'acili-ezme',
    nameTr: 'Acılı Ezme',
    nameEn: 'Spicy Tomato Dip',
    category: 'meze',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'raw', 'spicy'],
    ingredients: [
      { name: 'Domates', amount: '2 adet' },
      { name: 'Kırmızı soğan', amount: '1 adet' },
      { name: 'Kapya biber', amount: '1 adet' },
      { name: 'Sivri biber', amount: '2 adet' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Nar ekşisi', amount: '2 yemek kaşığı' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Sumak, tuz, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Sebzeleri çok ince doğrayın (veya rondoda pulse).',
      'Maydanozu kıyıp karıştırın.',
      'Nar ekşisi, yağ ve baharatları ekleyip harmanlayın.',
      'Soğuk servis edin.',
    ],
    nutritionPerServing: { kcal: 160, proteinG: 2, carbsG: 14, fatG: 11 },
  },
  {
    id: 'atom',
    nameTr: 'Atom Mezesi',
    nameEn: 'Atom Dip',
    category: 'meze',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 2,
    difficulty: 'easy',
    tags: ['vegetarian', 'spicy', 'quick'],
    ingredients: [
      { name: 'Süzme yoğurt', amount: '2 su bardağı' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Pul biber', amount: '1 tatlı kaşığı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
    ],
    steps: [
      'Yoğurt, ezilmiş sarımsak ve tuzu çırpın; tabağa alın.',
      'Tavada tereyağını eritip pul biberi kavurun.',
      'Yağı yoğurdun üstüne gezdirin; ılıkken servis edin.',
    ],
    nutritionPerServing: { kcal: 150, proteinG: 8, carbsG: 8, fatG: 10 },
  },
  {
    id: 'russian-salata',
    nameTr: 'Rus Salatası',
    nameEn: 'Russian Salad',
    category: 'meze',
    cuisine: 'international',
    servings: 6,
    prepMinutes: 20,
    cookMinutes: 20,
    difficulty: 'easy',
    tags: ['vegetarian'],
    ingredients: [
      { name: 'Patates', amount: '3 adet' },
      { name: 'Havuç', amount: '2 adet' },
      { name: 'Bezelye', amount: '1 su bardağı' },
      { name: 'Haşlanmış yumurta', amount: '2 adet' },
      { name: 'Turşu (kornişon)', amount: 'yarım su bardağı' },
      { name: 'Mayonez', amount: 'yarım su bardağı' },
      { name: 'Yoğurt', amount: '2 yemek kaşığı' },
      { name: 'Maydanoz', amount: '1 dal' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Patates, havuç ve bezelyeyi haşlayın; soğutun.',
      'Patates, havuç, yumurta ve turşuyu küçük küp doğrayın.',
      'Mayonez ve yoğurdu ekleyip karıştırın; baharatları katın.',
      'Üzerine maydanoz serpip soğuk servis edin.',
    ],
    nutritionPerServing: { kcal: 260, proteinG: 7, carbsG: 24, fatG: 15 },
  },
  {
    id: 'cacik',
    nameTr: 'Cacık',
    nameEn: 'Cacik (Yogurt with Cucumber)',
    category: 'meze',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['vegetarian', 'quick', 'traditional', 'summer'],
    ingredients: [
      { name: 'Salatalık', amount: '2 adet' },
      { name: 'Yoğurt', amount: '2 su bardağı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Zeytinyağı', amount: '1 yemek kaşığı' },
      { name: 'Nane', amount: '1 çay kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Soğuk su', amount: 'yarım su bardağı' },
    ],
    steps: [
      'Salatalıkları rendeleyin veya küçük küp doğrayın.',
      'Yoğurt ve suyu çırpın; sarımsak, tuz ve naneyi ekleyin.',
      'Salatalığı ekleyip karıştırın.',
      'Üstüne yağ gezdirip buzlu servis edin.',
    ],
    nutritionPerServing: { kcal: 90, proteinG: 5, carbsG: 8, fatG: 4 },
  },
  {
    id: 'yesil-mercimek-koftesi',
    nameTr: 'Mercimek Köftesi',
    nameEn: 'Lentil Patties',
    category: 'meze',
    cuisine: 'turkish',
    servings: 6,
    prepMinutes: 30,
    cookMinutes: 20,
    difficulty: 'medium',
    tags: ['vegetarian', 'vegan', 'traditional', 'high_protein'],
    ingredients: [
      { name: 'Kırmızı mercimek', amount: '1 su bardağı' },
      { name: 'İnce bulgur', amount: '1 su bardağı' },
      { name: 'Soğan', amount: '2 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Biber salçası', amount: '1 tatlı kaşığı' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Taze soğan', amount: '1 demet' },
      { name: 'Maydanoz', amount: '1 demet' },
      { name: 'Kimyon, karabiber, tuz', amount: 'tatmınıza göre' },
      { name: 'Marul (servis)', amount: '1 baş' },
    ],
    steps: [
      'Mercimeği 3 bardak suyla yumuşayana kadar kaynatın.',
      'Ocağı kapatıp bulguru ekleyin, kapağı kapalı 15 dk bekletin.',
      'Başka tavada yağda soğanı kavurun, salçaları ekleyip karıştırın; mercimek karışımına ekleyin.',
      'Ilınca yeşillikleri ve baharatları ekleyip yoğurun.',
      'Küçük köfteler şeklinde şekil verin.',
      'Marul yaprakları üzerinde limon ve maydanozla servis edin.',
    ],
    nutritionPerServing: { kcal: 260, proteinG: 10, carbsG: 40, fatG: 8 },
  },
  {
    id: 'patlican-kizartmasi-yoğurtlu',
    nameTr: 'Yoğurtlu Patlıcan Kızartması',
    nameEn: 'Fried Eggplant with Yogurt',
    category: 'meze',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    difficulty: 'easy',
    tags: ['vegetarian', 'traditional'],
    ingredients: [
      { name: 'Patlıcan', amount: '2 adet' },
      { name: 'Sıvı yağ', amount: 'kızartma için' },
      { name: 'Yoğurt', amount: '2 su bardağı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Salça', amount: '1 tatlı kaşığı' },
      { name: 'Tuz, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Patlıcanları yuvarlak dilimleyip tuzlu suda 15 dk bekletin; kurulayın.',
      'Yağda her iki yüzünü altın rengi olana dek kızartın; havlu kağıda alın.',
      'Yoğurt ve ezilmiş sarımsağı karıştırın.',
      'Tavada tereyağı ve salçayı hafif kavurun.',
      'Tabağa patlıcan dizip üzerine sarımsaklı yoğurt, üstüne acılı sosu gezdirin.',
    ],
    nutritionPerServing: { kcal: 340, proteinG: 7, carbsG: 18, fatG: 27 },
  },
  {
    id: 'beyaz-peynirli-atistirma',
    nameTr: 'Peynir Topları',
    nameEn: 'Cheese Balls',
    category: 'meze',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['vegetarian', 'quick', 'no_cook'],
    ingredients: [
      { name: 'Lor peyniri', amount: '250 g' },
      { name: 'Beyaz peynir', amount: '100 g' },
      { name: 'Ceviz (kıyılmış)', amount: 'yarım su bardağı' },
      { name: 'Maydanoz', amount: '1 demet' },
      { name: 'Kırmızı biber', amount: '1 tatlı kaşığı' },
      { name: 'Zeytinyağı', amount: '1 yemek kaşığı' },
    ],
    steps: [
      'Peynirleri ezip karıştırın.',
      'Ceviz, maydanoz ve kırmızı biberi ekleyin; yağı ekleyin.',
      'Ceviz büyüklüğünde toplar yapın; isterseniz dışını kıyılmış ceviz veya maydanozla kaplayın.',
      'Buzdolabında 15 dk dinlendirip servis edin.',
    ],
    nutritionPerServing: { kcal: 260, proteinG: 12, carbsG: 4, fatG: 22 },
  },
];
