import type { RecipeSeed } from './_types.js';

export const pastry: RecipeSeed[] = [
  {
    id: 'sigara-boregi',
    nameTr: 'Sigara Böreği',
    nameEn: 'Cheese Rolls',
    category: 'pastry',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 15,
    difficulty: 'easy',
    tags: ['traditional', 'vegetarian'],
    ingredients: [
      { name: 'Yufka', amount: '2 adet' },
      { name: 'Beyaz peynir', amount: '200 g' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Yumurta (kapatmak için)', amount: '1 adet' },
      { name: 'Süt', amount: '2 yemek kaşığı' },
      { name: 'Sıvı yağ', amount: 'kızartma için' },
    ],
    steps: [
      'Peynir ve maydanozu karıştırıp harç yapın.',
      'Yufkaları 8 üçgene kesin; geniş kenarına 1 tatlı kaşığı harç koyun.',
      'Yan kenarları kıvırıp rulo şeklinde sarın; ucunu çırpılmış yumurta-sütle kapatın.',
      'Kızgın yağda altın rengi olana dek kızartın; havlu kağıda alın.',
    ],
    nutritionPerServing: { kcal: 400, proteinG: 13, carbsG: 30, fatG: 26 },
  },
  {
    id: 'su-boregi',
    nameTr: 'Su Böreği',
    nameEn: 'Turkish Water Börek',
    category: 'pastry',
    cuisine: 'turkish',
    servings: 6,
    prepMinutes: 30,
    cookMinutes: 40,
    difficulty: 'hard',
    tags: ['traditional', 'family', 'vegetarian'],
    ingredients: [
      { name: 'Yufka', amount: '5 yaprak' },
      { name: 'Beyaz peynir', amount: '300 g' },
      { name: 'Maydanoz', amount: '1 demet' },
      { name: 'Yumurta', amount: '3 adet' },
      { name: 'Süt', amount: '2 su bardağı' },
      { name: 'Tereyağı', amount: '100 g' },
      { name: 'Sıvı yağ', amount: 'yarım su bardağı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
    ],
    steps: [
      'Büyük bir tencerede suyu kaynatın, buzlu su hazırlayın.',
      'Yumurta, süt, eritilmiş tereyağı, sıvı yağ ve tuzu çırpın.',
      'Yufkayı tepsi boyuna kesin; kaynayan suya 10 saniye batırıp buzlu suya alın, süzün.',
      'Yağlanmış tepsiye önce 1 yufka, üzerine karışım ve peynir-maydanoz; ortaya geldikçe ara yufkalar.',
      'Son kat yufka koyup üstüne bol karışım dökün.',
      '180°C fırında 35-40 dakika üzeri kızarana dek pişirin.',
      'Oda sıcaklığında dilimleyin.',
    ],
    nutritionPerServing: { kcal: 580, proteinG: 20, carbsG: 48, fatG: 34 },
  },
  {
    id: 'puf-boregi',
    nameTr: 'Puf Böreği',
    nameEn: 'Puff Börek',
    category: 'pastry',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 30,
    cookMinutes: 15,
    difficulty: 'medium',
    tags: ['vegetarian', 'traditional'],
    ingredients: [
      { name: 'Un', amount: '3 su bardağı' },
      { name: 'Yumurta', amount: '1 adet' },
      { name: 'Yoğurt', amount: '1 yemek kaşığı' },
      { name: 'Ilık su', amount: '1 su bardağı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Beyaz peynir', amount: '200 g' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Sıvı yağ', amount: 'kızartma için' },
    ],
    steps: [
      'Un, yumurta, yoğurt, tuz ve ılık suyla yumuşak hamur yoğurun; 20 dakika dinlendirin.',
      'Peynir ve maydanozu karıştırıp iç harç yapın.',
      'Hamuru bezelere bölüp ince dairelere açın.',
      'Bir yarısına harç koyup yarım ay şekli verin; kenarlarına bastırıp kapatın.',
      'Kızgın yağda şişene kadar her iki yüzünü kızartın.',
    ],
    nutritionPerServing: { kcal: 480, proteinG: 15, carbsG: 48, fatG: 24 },
  },
  {
    id: 'pogaca',
    nameTr: 'Klasik Poğaça',
    nameEn: 'Turkish Pogaca',
    category: 'pastry',
    cuisine: 'turkish',
    servings: 12,
    prepMinutes: 25,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['vegetarian', 'breakfast', 'make_ahead'],
    ingredients: [
      { name: 'Un', amount: '4,5 su bardağı' },
      { name: 'Yoğurt', amount: 'yarım su bardağı' },
      { name: 'Sıvı yağ', amount: 'yarım su bardağı' },
      { name: 'Eritilmiş tereyağı', amount: 'yarım su bardağı' },
      { name: 'Yumurta', amount: '2 adet (1\'i üste)' },
      { name: 'Kabartma tozu', amount: '1 paket' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Beyaz peynir', amount: '200 g' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Susam, çörek otu', amount: 'serpmek için' },
    ],
    steps: [
      'Bir kapta yoğurt, yağ, tereyağı, 1 yumurta ve tuzu karıştırın.',
      'Un ve kabartma tozunu ekleyip ele yapışmayan hamur yoğurun; 15 dakika dinlendirin.',
      'İç harç için peynir + maydanozu karıştırın.',
      'Hamuru 12 bezeye ayırın; her birini açıp içine harç koyup kapatın.',
      'Tepsiye dizin; üzerlerine sarısı ayrılmış yumurta sarısı sürüp susam/çörek otu serpin.',
      '180°C fırında 20-25 dakika, üstü kızarana dek pişirin.',
    ],
    nutritionPerServing: { kcal: 280, proteinG: 8, carbsG: 26, fatG: 16 },
  },
  {
    id: 'ispanakli-borek',
    nameTr: 'Ispanaklı Tepsi Böreği',
    nameEn: 'Spinach Börek Tray',
    category: 'pastry',
    cuisine: 'turkish',
    servings: 6,
    prepMinutes: 20,
    cookMinutes: 40,
    difficulty: 'medium',
    tags: ['vegetarian', 'traditional', 'family'],
    ingredients: [
      { name: 'Yufka', amount: '3 yaprak' },
      { name: 'Ispanak', amount: '500 g' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Beyaz peynir (opsiyonel)', amount: '100 g' },
      { name: 'Yumurta', amount: '2 adet' },
      { name: 'Süt', amount: '1 su bardağı' },
      { name: 'Yoğurt', amount: 'yarım su bardağı' },
      { name: 'Sıvı yağ', amount: 'yarım su bardağı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Ispanağı yıkayıp kıyın; yağda soğan ve ıspanağı kavurun, suyunu çekirin.',
      'Karışım için yumurta, süt, yoğurt ve sıvı yağı çırpın.',
      'Yağlanmış tepsiye 1 yufka yayıp karışımla ıslatın; üstüne bir miktar ıspanak yayın.',
      'İkinci yufkayı buruşturarak üzerine yerleştirin; karışımdan serpin.',
      'Üçüncü yufkayı kapatın; üstüne kalan karışımın tamamını ve yumurta sarısı dökün.',
      '180°C fırında 35-40 dakika kızarana dek pişirin.',
      'Bir miktar soğuttuktan sonra dilimleyin.',
    ],
    nutritionPerServing: { kcal: 420, proteinG: 12, carbsG: 45, fatG: 22 },
  },
  {
    id: 'kiymali-borek',
    nameTr: 'Kıymalı Kol Böreği',
    nameEn: 'Ground Beef Börek Roll',
    category: 'pastry',
    cuisine: 'turkish',
    servings: 6,
    prepMinutes: 25,
    cookMinutes: 30,
    difficulty: 'medium',
    tags: ['traditional', 'family'],
    ingredients: [
      { name: 'Yufka', amount: '3 yaprak' },
      { name: 'Dana kıyma', amount: '250 g' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sıvı yağ', amount: 'yarım su bardağı' },
      { name: 'Süt', amount: 'yarım su bardağı' },
      { name: 'Yumurta', amount: '1 adet' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Kıymayı soğanla suyunu çekene kadar kavurun; maydanoz ve baharatlarla soğutun.',
      'Yağ, süt ve yumurta sarısını karıştırarak sos yapın.',
      'Yufkayı dörde bölün; her dilime sostan sürüp kenarına harç koyup sıkı sarın.',
      'Yağlanmış tepsiye rulo şeklinde dizin.',
      'Üzerine yumurta akını ve kalan sosu sürün.',
      '180°C fırında 25-30 dakika kızarana dek pişirin.',
    ],
    nutritionPerServing: { kcal: 520, proteinG: 18, carbsG: 48, fatG: 26 },
  },
  {
    id: 'pide',
    nameTr: 'Kıymalı Pide',
    nameEn: 'Turkish Pide with Ground Beef',
    category: 'pastry',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 90,
    cookMinutes: 15,
    difficulty: 'medium',
    tags: ['traditional'],
    ingredients: [
      { name: 'Un', amount: '4 su bardağı' },
      { name: 'Ilık su', amount: '1,5 su bardağı' },
      { name: 'Kuru maya', amount: '1 paket' },
      { name: 'Zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Tuz, şeker', amount: '1\'er çay kaşığı' },
      { name: 'Dana kıyma', amount: '300 g' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sivri biber', amount: '2 adet' },
      { name: 'Domates', amount: '2 adet' },
      { name: 'Domates + biber salçası', amount: '1\'er tatlı kaşığı' },
      { name: 'Yumurta sarısı (üst)', amount: '1 adet' },
      { name: 'Tuz, karabiber, kekik, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Hamur: ılık suya maya + şeker; 5 dk bekletin. Un, tuz, yağ ve su karışımını yoğurun. 1 saat mayalandırın.',
      'Harç: kıyma, ince doğranmış soğan-biber-domates, salçalar ve baharatları çiğ halde karıştırın.',
      'Mayalanan hamuru 4 bezeye bölün; her birini uzun oval açın.',
      'Ortasına harcı yayın; kenarları kıvırıp uçlardan sıkıştırın (kayık şekli).',
      'Üstüne yumurta sarısı sürün.',
      '250°C fırında 12-15 dakika kızarana dek pişirin.',
      'Tereyağı sürüp servis edin.',
    ],
    nutritionPerServing: { kcal: 620, proteinG: 25, carbsG: 82, fatG: 22 },
  },
  {
    id: 'lahmacun',
    nameTr: 'Lahmacun',
    nameEn: 'Turkish Flat Pizza',
    category: 'pastry',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 60,
    cookMinutes: 10,
    difficulty: 'medium',
    tags: ['traditional'],
    ingredients: [
      { name: 'Un', amount: '3 su bardağı' },
      { name: 'Ilık su', amount: '1 su bardağı' },
      { name: 'Maya', amount: 'yarım paket' },
      { name: 'Tuz, şeker', amount: '1\'er çay kaşığı' },
      { name: 'Dana kıyma', amount: '250 g' },
      { name: 'Kırmızı soğan', amount: '1 adet' },
      { name: 'Kapya biber', amount: '1 adet' },
      { name: 'Domates', amount: '1 adet' },
      { name: 'Sarımsak', amount: '3 diş' },
      { name: 'Domates + biber salçası', amount: '1\'er yemek kaşığı' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Tuz, karabiber, kimyon, pul biber', amount: 'tatmınıza göre' },
      { name: 'Limon', amount: '1 adet (servis için)' },
    ],
    steps: [
      'Hamuru yoğurup 45 dakika mayalandırın.',
      'Harç için tüm sebzeleri rondodan geçirip kıyma, salça, baharatlar ve yağla karıştırın.',
      'Hamurdan mandalina büyüklüğünde bezeler alın; ince daireler açın.',
      'Her daireye kaşıkla harcı ince yayın; kenarlar görünsün.',
      '250°C fırında 7-10 dakika kızartın.',
      'Maydanoz, limon, roka ile servis edin; isterseniz sarın.',
    ],
    nutritionPerServing: { kcal: 480, proteinG: 20, carbsG: 62, fatG: 16 },
  },
  {
    id: 'bazlama',
    nameTr: 'Bazlama',
    nameEn: 'Turkish Flatbread',
    category: 'pastry',
    cuisine: 'turkish',
    servings: 6,
    prepMinutes: 60,
    cookMinutes: 20,
    difficulty: 'easy',
    tags: ['traditional', 'vegetarian', 'vegan'],
    ingredients: [
      { name: 'Un', amount: '4 su bardağı' },
      { name: 'Ilık su', amount: '1,5 su bardağı' },
      { name: 'Maya', amount: 'yarım paket' },
      { name: 'Şeker', amount: '1 çay kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
    ],
    steps: [
      'Ilık suya maya ve şekeri eklyeip 5 dakika bekletin.',
      'Un ve tuzla yumuşak hamur yoğurup 45 dakika mayalandırın.',
      'Hamurdan 6 beze alın; her birini 1 cm kalınlıkta açın.',
      'Döküm tavayı iyice ısıtın, yağsız olarak bazlamaları her iki yüzü kızarana dek 3-4 dakika pişirin.',
      'Tereyağıyla ve peynirle servis edin.',
    ],
    nutritionPerServing: { kcal: 280, proteinG: 8, carbsG: 58, fatG: 1 },
  },
  {
    id: 'acma',
    nameTr: 'Ev Yapımı Açma',
    nameEn: 'Soft Turkish Rolls',
    category: 'pastry',
    cuisine: 'turkish',
    servings: 12,
    prepMinutes: 90,
    cookMinutes: 25,
    difficulty: 'medium',
    tags: ['traditional', 'breakfast', 'vegetarian'],
    ingredients: [
      { name: 'Un', amount: '5 su bardağı' },
      { name: 'Süt', amount: '1,5 su bardağı' },
      { name: 'Yumurta', amount: '1 adet (ek 1 tane üst için)' },
      { name: 'Sıvı yağ', amount: 'yarım su bardağı' },
      { name: 'Tereyağı (yumuşak)', amount: '100 g' },
      { name: 'Yaş maya', amount: '30 g' },
      { name: 'Tuz, şeker', amount: '1\'er çay kaşığı' },
      { name: 'Susam', amount: 'serpmek için' },
    ],
    steps: [
      'Ilık süt, şeker, maya ile mayayı çözün; 10 dk bekletin.',
      'Un, yumurta, yağ, tuz ve maya karışımını yumuşak hamur olana dek yoğurun; 1 saat mayalandırın.',
      'Hamuru 12 bezeye bölün; her birini ince açıp tereyağı sürüp rulo sarın, çember yapın, ucu altına sıkıştırın.',
      'Tepsiye dizip 30 dakika daha mayalandırın.',
      'Üstlerine yumurta sarısı sürüp susam serpin.',
      '170°C fırında 20-25 dakika kızartın.',
    ],
    nutritionPerServing: { kcal: 340, proteinG: 8, carbsG: 42, fatG: 16 },
  },
];
