import type { RecipeSeed } from './_types.js';

export const pasta: RecipeSeed[] = [
  {
    id: 'kiymali-makarna',
    nameTr: 'Kıymalı Makarna',
    nameEn: 'Turkish Ground Beef Pasta',
    category: 'pasta',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['comfort', 'student_friendly', 'budget'],
    ingredients: [
      { name: 'Makarna (spagetti veya burgu)', amount: '400 g' },
      { name: 'Dana kıyma', amount: '300 g' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Domates', amount: '2 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Kaşar / beyaz peynir', amount: 'rende için' },
      { name: 'Tuz, karabiber, kekik', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Makarnayı bol tuzlu suda paket üstündeki süreden 1 dakika az haşlayıp süzün.',
      'Yağda soğan-sarımsağı kavurun; kıymayı ekleyip suyunu çekirin.',
      'Salçayı ekleyin; rende domates ve baharatları ilave edip 10 dakika pişirin.',
      'Makarnayı sosa ekleyip 1 kepçe haşlama suyu ile karıştırın.',
      'Servis anında üzerine rende kaşar veya beyaz peynir ekleyin.',
    ],
    nutritionPerServing: { kcal: 560, proteinG: 28, carbsG: 65, fatG: 20 },
  },
  {
    id: 'yogurtlu-makarna',
    nameTr: 'Yoğurtlu Makarna',
    nameEn: 'Pasta with Garlic Yogurt',
    category: 'pasta',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 15,
    difficulty: 'easy',
    tags: ['comfort', 'student_friendly', 'quick', 'vegetarian'],
    ingredients: [
      { name: 'Makarna (fiyonk/burgu)', amount: '400 g' },
      { name: 'Süzme yoğurt', amount: '2 su bardağı' },
      { name: 'Sarımsak', amount: '3 diş' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Domates salçası', amount: '1 tatlı kaşığı' },
      { name: 'Pul biber, kuru nane', amount: 'tatmınıza göre' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
    ],
    steps: [
      'Makarnayı bol tuzlu suda haşlayıp süzün.',
      'Yoğurdu ezilmiş sarımsak ve tuzla karıştırın.',
      'Makarnayı servis tabağına alın; üzerine sarımsaklı yoğurdu dökün.',
      'Tavada tereyağını eritip salça, pul biber ve naneyi 15 saniye kavurun.',
      'Acılı yağı makarnanın üstüne gezdirin; servis edin.',
    ],
    nutritionPerServing: { kcal: 520, proteinG: 18, carbsG: 75, fatG: 16 },
  },
  {
    id: 'firin-makarna',
    nameTr: 'Fırın Makarna',
    nameEn: 'Baked Béchamel Pasta',
    category: 'pasta',
    cuisine: 'turkish',
    servings: 5,
    prepMinutes: 15,
    cookMinutes: 30,
    difficulty: 'medium',
    tags: ['comfort', 'family'],
    ingredients: [
      { name: 'Makarna (boru veya burgu)', amount: '500 g' },
      { name: 'Süt', amount: '3 su bardağı' },
      { name: 'Un', amount: '3 yemek kaşığı' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Kaşar peyniri (rende)', amount: '200 g' },
      { name: 'Yumurta', amount: '2 adet' },
      { name: 'Muskat (rende)', amount: '1 tutam' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Makarnayı al dente haşlayıp süzün, biraz suyla yağlayıp yapışmasını önleyin.',
      'Beşamel: tereyağını eritin, unu ekleyip kavurun; sıcak sütü yavaşça ekleyerek çırpın.',
      'Pürüzsüz sosa tuz, karabiber ve muskat ekleyin; ocaktan alıp ılıtın, yumurtaları katın.',
      'Tepsiye yağ sürün; makarna + sos + rende kaşar karıştırıp yayın.',
      'Üzerine kalan kaşarı serpin; 200°C fırında 20-25 dakika kızartın.',
    ],
    nutritionPerServing: { kcal: 640, proteinG: 27, carbsG: 75, fatG: 27 },
  },
  {
    id: 'makarna-alfredo',
    nameTr: 'Alfredo Makarna',
    nameEn: 'Alfredo Pasta',
    category: 'pasta',
    cuisine: 'italian',
    servings: 3,
    prepMinutes: 5,
    cookMinutes: 15,
    difficulty: 'easy',
    tags: ['quick', 'comfort', 'student_friendly', 'vegetarian'],
    ingredients: [
      { name: 'Fettuccine makarna', amount: '300 g' },
      { name: 'Krema', amount: '1 su bardağı' },
      { name: 'Parmesan (rende)', amount: 'yarım su bardağı' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Maydanoz', amount: '1 dal' },
    ],
    steps: [
      'Makarnayı al dente haşlayın; kepçenin biriyle haşlama suyunu ayırın.',
      'Tavada tereyağını eritin; ezilmiş sarımsağı 30 saniye çevirin.',
      'Kremayı ekleyip ısıtın; rende parmesanı azar azar katıp eritin.',
      'Tuz, karabiber; gerekiyorsa haşlama suyu ile kıvam ayarlayın.',
      'Makarnayı sosa ekleyip karıştırın; maydanozla servis edin.',
    ],
    nutritionPerServing: { kcal: 620, proteinG: 20, carbsG: 70, fatG: 29 },
  },
  {
    id: 'pesto-makarna',
    nameTr: 'Pestolu Makarna',
    nameEn: 'Pesto Pasta',
    category: 'pasta',
    cuisine: 'italian',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 12,
    difficulty: 'easy',
    tags: ['quick', 'vegetarian', 'student_friendly'],
    ingredients: [
      { name: 'Penne makarna', amount: '300 g' },
      { name: 'Fesleğen', amount: '1 demet' },
      { name: 'Ceviz veya çam fıstığı', amount: 'yarım su bardağı' },
      { name: 'Parmesan', amount: 'yarım su bardağı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Zeytinyağı', amount: 'yarım su bardağı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Limon suyu', amount: '1 tatlı kaşığı' },
    ],
    steps: [
      'Pesto için fesleğen, ceviz, sarımsak, peynir ve yağı rondoda çekin; tuz ve limon ekleyin.',
      'Makarnayı al dente haşlayıp süzün; 1 kepçe suyunu ayırın.',
      'Makarnayı pestoyla karıştırın; kıvamı için biraz haşlama suyu ekleyin.',
      'Üzerine fazla parmesan serpip servis edin.',
    ],
    nutritionPerServing: { kcal: 620, proteinG: 18, carbsG: 60, fatG: 35 },
  },
  {
    id: 'mantar-soslu-makarna',
    nameTr: 'Kremalı Mantarlı Makarna',
    nameEn: 'Creamy Mushroom Pasta',
    category: 'pasta',
    cuisine: 'turkish',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 20,
    difficulty: 'easy',
    tags: ['vegetarian', 'comfort', 'quick'],
    ingredients: [
      { name: 'Penne makarna', amount: '300 g' },
      { name: 'Mantar', amount: '300 g' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Krema', amount: 'yarım su bardağı' },
      { name: 'Süt', amount: 'yarım su bardağı' },
      { name: 'Parmesan (opsiyonel)', amount: '3 yemek kaşığı' },
      { name: 'Zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Tuz, karabiber, kekik', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Makarnayı al dente haşlayıp süzün.',
      'Tavada yağda soğan-sarımsağı kavurun; mantarları ekleyip suyunu çekirin.',
      'Krema ve sütü ekleyip 3-4 dakika pişirin.',
      'Tuz, karabiber, kekik; isterseniz parmesanı ekleyin.',
      'Makarnayı sosa ekleyip karıştırın; hemen servis edin.',
    ],
    nutritionPerServing: { kcal: 580, proteinG: 18, carbsG: 72, fatG: 22 },
  },
];
