import type { RecipeSeed } from './_types.js';

export const rice: RecipeSeed[] = [
  {
    id: 'tereyagli-pirinc-pilavi',
    nameTr: 'Tereyağlı Pirinç Pilavı',
    nameEn: 'Turkish Butter Rice',
    category: 'rice',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['traditional', 'student_friendly', 'vegetarian'],
    ingredients: [
      { name: 'Baldo pirinç', amount: '2 su bardağı', grams: 360 },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Sıvı yağ', amount: '1 yemek kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Sıcak su', amount: '3,5 su bardağı' },
    ],
    steps: [
      'Pirinci 10 dakika sıcak tuzlu suda bekletin; süzüp yıkayın.',
      'Tencerede tereyağı + sıvı yağı eritin; pirinci 3-4 dakika kavurun.',
      'Sıcak su ve tuzu ekleyip kaynatın.',
      'Kapak kapalı kısık ateşte 15 dakika, su çekilene dek pişirin.',
      'Ocaktan alıp ağzına havlu peçete koyup 10 dakika demlendirin.',
    ],
    nutritionPerServing: { kcal: 380, proteinG: 6, carbsG: 62, fatG: 11 },
  },
  {
    id: 'sehriyeli-pilav',
    nameTr: 'Şehriyeli Pirinç Pilavı',
    nameEn: 'Rice Pilaf with Orzo',
    category: 'rice',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['traditional', 'vegetarian', 'student_friendly'],
    ingredients: [
      { name: 'Baldo pirinç', amount: '2 su bardağı' },
      { name: 'Arpa şehriye', amount: 'yarım su bardağı' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Sıcak tavuk suyu veya su', amount: '3,5 su bardağı' },
    ],
    steps: [
      'Pirinci ılık tuzlu suda 10 dk bekletip süzün.',
      'Tencerede tereyağını eritin; şehriyeyi pembeleşene kadar kavurun.',
      'Pirinci ekleyip 2 dakika çevirin.',
      'Sıcak su ve tuzu ekleyin; kaynayınca kısık ateşe alın.',
      'Kapak kapalı 15 dakika pişirin; 10 dakika demlendirin.',
    ],
    nutritionPerServing: { kcal: 410, proteinG: 7, carbsG: 70, fatG: 11 },
  },
  {
    id: 'bulgur-pilavi',
    nameTr: 'Bulgur Pilavı',
    nameEn: 'Bulgur Pilaf',
    category: 'rice',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['traditional', 'vegetarian', 'healthy', 'budget'],
    ingredients: [
      { name: 'Pilavlık bulgur', amount: '2 su bardağı' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Yeşil biber', amount: '1 adet' },
      { name: 'Domates', amount: '1 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Biber salçası', amount: '1 tatlı kaşığı' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Sıvı yağ', amount: '2 yemek kaşığı' },
      { name: 'Tuz, pul biber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '3 su bardağı' },
    ],
    steps: [
      'Tencerede yağ ve tereyağını eritin; doğranmış soğanı kavurun.',
      'İnce doğranmış biber ve domatesi ekleyip 2 dakika pişirin.',
      'Salçaları ekleyip 1 dakika çevirin.',
      'Bulguru ekleyip 2 dakika kavurun.',
      'Sıcak su ve tuzu ilave edin; kaynayınca kısık ateşe alın.',
      'Kapak kapalı 15 dakika pişirin; 10 dakika demlendirip servis edin.',
    ],
    nutritionPerServing: { kcal: 390, proteinG: 9, carbsG: 65, fatG: 11 },
  },
  {
    id: 'nohutlu-pirinc-pilavi',
    nameTr: 'Nohutlu Pilav',
    nameEn: 'Chickpea Rice',
    category: 'rice',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['vegetarian', 'high_protein'],
    ingredients: [
      { name: 'Baldo pirinç', amount: '2 su bardağı' },
      { name: 'Haşlanmış nohut', amount: '1 su bardağı' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Sıcak su', amount: '3,5 su bardağı' },
    ],
    steps: [
      'Pirinci ılık tuzlu suda 10 dk bekletip süzün.',
      'Tencerede tereyağı ile pirinci 2 dakika kavurun.',
      'Haşlanmış nohut, sıcak su ve tuzu ekleyin.',
      'Kaynayınca kısık ateşte 15 dakika pişirin.',
      '10 dakika demlendirip servis edin.',
    ],
    nutritionPerServing: { kcal: 430, proteinG: 11, carbsG: 70, fatG: 11 },
  },
  {
    id: 'ic-pilav',
    nameTr: 'İç Pilav',
    nameEn: 'Stuffing Rice Pilaf',
    category: 'rice',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 30,
    difficulty: 'medium',
    tags: ['traditional', 'festive'],
    ingredients: [
      { name: 'Baldo pirinç', amount: '2 su bardağı' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Çam fıstığı', amount: '2 yemek kaşığı' },
      { name: 'Kuş üzümü', amount: '2 yemek kaşığı' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Sıvı yağ', amount: '2 yemek kaşığı' },
      { name: 'Tarçın, yenibahar, karabiber', amount: 'tatmınıza göre' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Dereotu, maydanoz', amount: '2 dal' },
      { name: 'Sıcak su', amount: '3,5 su bardağı' },
    ],
    steps: [
      'Pirinci sıcak tuzlu suda 10 dakika bekletip süzün.',
      'Tencerede yağ + tereyağını eritin; çam fıstığını hafif kavurun.',
      'İnce doğranmış soğanı ekleyin, pembeleşene dek çevirin.',
      'Pirinci ekleyip 3 dakika kavurun.',
      'Kuş üzümü ve baharatları ekleyin; sıcak su ve tuz ile kaynatın.',
      'Kısık ateşte 15 dakika pişirin; 10 dakika demlendirin.',
      'Kıyılmış dereotu ve maydanoz serpip servis edin.',
    ],
    nutritionPerServing: { kcal: 460, proteinG: 8, carbsG: 72, fatG: 15 },
  },
  {
    id: 'ezilmis-mercimek-pilavi',
    nameTr: 'Mercimekli Bulgur Pilavı',
    nameEn: 'Lentil Bulgur Pilaf',
    category: 'rice',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 40,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'high_protein', 'healthy', 'budget'],
    ingredients: [
      { name: 'Yeşil mercimek', amount: 'yarım su bardağı' },
      { name: 'Pilavlık bulgur', amount: '1,5 su bardağı' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '3 su bardağı' },
    ],
    steps: [
      'Mercimeği ayrı tencerede yarım haşlayın (15 dk), süzün.',
      'Başka tencerede yağ ile soğanı kavurun; salçayı ekleyin.',
      'Bulgur ve mercimeği ekleyin; 2 dakika çevirin.',
      'Sıcak su ve baharatları ekleyin; kaynatın.',
      'Kısık ateşte 15 dakika pişirin; 10 dakika demlendirip servis edin.',
    ],
    nutritionPerServing: { kcal: 360, proteinG: 13, carbsG: 60, fatG: 9 },
  },
  {
    id: 'domatesli-bulgur',
    nameTr: 'Domatesli Bulgur',
    nameEn: 'Tomato Bulgur',
    category: 'rice',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 20,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'quick', 'student_friendly', 'budget'],
    ingredients: [
      { name: 'Pilavlık bulgur', amount: '2 su bardağı' },
      { name: 'Domates salçası', amount: '2 yemek kaşığı' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Sıcak su', amount: '3 su bardağı' },
    ],
    steps: [
      'Tencerede yağı ısıtın; salçayı ekleyip 30 saniye kavurun.',
      'Bulguru ekleyip 2 dakika çevirin.',
      'Sıcak su ve tuzu ekleyin; kaynayınca kısık ateşe alın.',
      'Kapak kapalı 15 dakika pişirin; 5 dakika demlendirin.',
    ],
    nutritionPerServing: { kcal: 340, proteinG: 9, carbsG: 60, fatG: 9 },
  },
  {
    id: 'meyhane-pilavi',
    nameTr: 'Meyhane Pilavı',
    nameEn: 'Barley & Chickpea Pilaf',
    category: 'rice',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['vegetarian', 'high_fiber'],
    ingredients: [
      { name: 'Baldo pirinç', amount: '1,5 su bardağı' },
      { name: 'Arpa şehriye', amount: 'yarım su bardağı' },
      { name: 'Haşlanmış nohut', amount: 'yarım su bardağı' },
      { name: 'Kuş üzümü', amount: '2 yemek kaşığı' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Çam fıstığı', amount: '2 yemek kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Dereotu', amount: '2 dal' },
      { name: 'Sıcak su', amount: '3,5 su bardağı' },
    ],
    steps: [
      'Tereyağında çam fıstığını ve şehriyeyi kızartın.',
      'Yıkanmış pirinci ekleyin, 2 dakika çevirin.',
      'Nohut, kuş üzümü, sıcak su ve tuzu ekleyin.',
      'Kısık ateşte 15 dakika pişirin; 10 dakika demlendirin.',
      'Dereotu serperek servis edin.',
    ],
    nutritionPerServing: { kcal: 440, proteinG: 9, carbsG: 72, fatG: 13 },
  },
];
