import type { RecipeSeed } from './_types.js';

export const salads: RecipeSeed[] = [
  {
    id: 'coban-salata',
    nameTr: 'Çoban Salata',
    nameEn: 'Shepherd Salad',
    category: 'salad',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'raw', 'quick', 'healthy', 'student_friendly'],
    ingredients: [
      { name: 'Domates', amount: '3 adet' },
      { name: 'Salatalık', amount: '2 adet' },
      { name: 'Sivri biber', amount: '1 adet' },
      { name: 'Kırmızı soğan', amount: '1 adet' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Limon suyu veya sirke', amount: '2 yemek kaşığı' },
      { name: 'Tuz, karabiber, sumak', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Tüm sebzeleri küçük küpler halinde doğrayın; maydanozu kıyın.',
      'Kasede karıştırın, tuz ekleyip bırakın (suyu çıkaracaksa süzün).',
      'Servis anında limon, yağ ve baharatları ekleyip karıştırın.',
    ],
    nutritionPerServing: { kcal: 130, proteinG: 2, carbsG: 10, fatG: 10 },
  },
  {
    id: 'gavurdagi-salatasi',
    nameTr: 'Gavurdağı Salatası',
    nameEn: 'Gavurdagi Salad',
    category: 'salad',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'raw', 'traditional'],
    ingredients: [
      { name: 'Domates', amount: '3 adet' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sivri biber', amount: '2 adet' },
      { name: 'Ceviz içi', amount: 'yarım su bardağı' },
      { name: 'Maydanoz', amount: '1 demet' },
      { name: 'Nar ekşisi', amount: '2 yemek kaşığı' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Sumak, tuz, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Tüm sebzeleri ince küp doğrayın, ceviz ve maydanozu kıyın.',
      'Bir kasede birleştirin.',
      'Nar ekşisi, zeytinyağı, sumak, pul biber ve tuzu ekleyip harmanlayın.',
      'Isırılmış ekmekle servis edin.',
    ],
    nutritionPerServing: { kcal: 220, proteinG: 5, carbsG: 12, fatG: 18 },
  },
  {
    id: 'mevsim-salata',
    nameTr: 'Mevsim Salata',
    nameEn: 'Mixed Green Salad',
    category: 'salad',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'raw', 'quick', 'healthy'],
    ingredients: [
      { name: 'Marul', amount: '1 baş' },
      { name: 'Roka', amount: '1 avuç' },
      { name: 'Domates', amount: '2 adet' },
      { name: 'Salatalık', amount: '1 adet' },
      { name: 'Havuç', amount: '1 adet' },
      { name: 'Mısır', amount: '3 yemek kaşığı' },
      { name: 'Limon, zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Marul ve rokayı yıkayıp iri doğrayın.',
      'Diğer sebzeleri dilim veya küpleyin.',
      'Kasede hepsini birleştirin; servis anında limon + yağ + tuz + karabiber ekleyin.',
    ],
    nutritionPerServing: { kcal: 110, proteinG: 2, carbsG: 12, fatG: 6 },
  },
  {
    id: 'mercimek-salatasi',
    nameTr: 'Yeşil Mercimek Salatası',
    nameEn: 'Green Lentil Salad',
    category: 'salad',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'high_protein', 'healthy', 'student_friendly'],
    ingredients: [
      { name: 'Yeşil mercimek', amount: '1 su bardağı' },
      { name: 'Salatalık', amount: '1 adet' },
      { name: 'Domates', amount: '1 adet' },
      { name: 'Kırmızı soğan', amount: '1 adet' },
      { name: 'Maydanoz, nane', amount: '1 demet' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Limon / nar ekşisi', amount: '2 yemek kaşığı' },
      { name: 'Tuz, karabiber, sumak', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Mercimeği yıkayıp 20-25 dakika al dente haşlayın; süzüp soğutun.',
      'Tüm sebzeleri ince küp doğrayın; yeşilliği kıyın.',
      'Mercimekle birleştirip yağ, limon ve baharatlarla karıştırın.',
      'Soğuk servis edin.',
    ],
    nutritionPerServing: { kcal: 240, proteinG: 12, carbsG: 30, fatG: 9 },
  },
  {
    id: 'piyaz',
    nameTr: 'Piyaz',
    nameEn: 'White Bean Salad',
    category: 'salad',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'traditional', 'high_protein'],
    ingredients: [
      { name: 'Haşlanmış kuru fasulye', amount: '2 su bardağı' },
      { name: 'Kırmızı soğan', amount: '1 adet' },
      { name: 'Yeşil biber', amount: '1 adet' },
      { name: 'Haşlanmış yumurta', amount: '2 adet' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Sumak, tuz', amount: 'tatmınıza göre' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Limon', amount: '1 adet' },
    ],
    steps: [
      'Fasulyeleri, doğranmış soğan ve biberi kaseye alın.',
      'Sumak ve tuzu soğanla ovup ekşitme yapın.',
      'Yağ ve limonu ekleyip karıştırın.',
      'Üzerine dilimlenmiş yumurta ve maydanozla servis edin.',
    ],
    nutritionPerServing: { kcal: 280, proteinG: 14, carbsG: 28, fatG: 13 },
  },
  {
    id: 'karisik-turlu-salata',
    nameTr: 'Mısırlı Ton Balıklı Salata',
    nameEn: 'Tuna & Corn Salad',
    category: 'salad',
    cuisine: 'international',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['high_protein', 'quick', 'student_friendly', 'omega3'],
    ingredients: [
      { name: 'Ton balığı konservesi', amount: '2 adet' },
      { name: 'Haşlanmış mısır', amount: '1 su bardağı' },
      { name: 'Marul', amount: '1 baş' },
      { name: 'Cherry domates', amount: '10 adet' },
      { name: 'Kırmızı soğan', amount: 'yarım adet' },
      { name: 'Zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Limon', amount: 'yarım adet' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Ton balığını süzüp dağıtın.',
      'Marulu doğrayın; cherry domatesleri ikiye bölün; soğanı dilimleyin.',
      'Hepsini kasede birleştirin; yağ, limon ve baharatlarla karıştırın.',
    ],
    nutritionPerServing: { kcal: 320, proteinG: 25, carbsG: 22, fatG: 14 },
  },
  {
    id: 'havuc-tarator',
    nameTr: 'Havuç Tarator',
    nameEn: 'Carrot Tarator',
    category: 'salad',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 10,
    difficulty: 'easy',
    tags: ['vegetarian', 'healthy', 'traditional'],
    ingredients: [
      { name: 'Havuç', amount: '3 adet' },
      { name: 'Süzme yoğurt', amount: '1,5 su bardağı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Ceviz', amount: 'yarım çay bardağı' },
      { name: 'Tuz', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Havuçları rendeleyin.',
      'Tavada yağda 8 dk kadar yumuşayana dek pişirip soğutun.',
      'Yoğurt, ezilmiş sarımsak ve tuzu karıştırın; havuçlarla birleştirin.',
      'Üstüne ceviz serpip servis edin.',
    ],
    nutritionPerServing: { kcal: 180, proteinG: 5, carbsG: 10, fatG: 13 },
  },
  {
    id: 'kisir',
    nameTr: 'Kısır',
    nameEn: 'Turkish Bulgur Salad',
    category: 'salad',
    cuisine: 'turkish',
    servings: 6,
    prepMinutes: 20,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'traditional'],
    ingredients: [
      { name: 'İnce bulgur', amount: '2 su bardağı' },
      { name: 'Sıcak su', amount: '1,5 su bardağı' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Biber salçası', amount: '1 yemek kaşığı' },
      { name: 'Taze soğan', amount: '1 demet' },
      { name: 'Maydanoz, nane', amount: '1 demet' },
      { name: 'Marul', amount: 'servis için' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Nar ekşisi', amount: '3 yemek kaşığı' },
      { name: 'Limon', amount: '1 adet' },
      { name: 'Tuz, karabiber, pul biber, kimyon', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Bulguru sıcak suya ekleyip 15 dk ağzı kapalı bekletin; şişene dek.',
      'Salçaları yağla ovup bulgurla karıştırın.',
      'Doğranmış yeşillikleri ve baharatları ekleyin.',
      'Limon ve nar ekşisini ilave edip iyice yoğurun.',
      'Marul yaprakları ile servis edin.',
    ],
    nutritionPerServing: { kcal: 280, proteinG: 7, carbsG: 50, fatG: 8 },
  },
];
