import type { RecipeSeed } from './_types.js';

export const soups: RecipeSeed[] = [
  {
    id: 'mercimek-corbasi',
    nameTr: 'Kırmızı Mercimek Çorbası',
    nameEn: 'Red Lentil Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    difficulty: 'easy',
    tags: ['vegetarian', 'traditional', 'budget', 'student_friendly'],
    ingredients: [
      { name: 'Kırmızı mercimek', amount: '1 su bardağı', grams: 180 },
      { name: 'Soğan', amount: '1 adet orta boy', grams: 120 },
      { name: 'Havuç', amount: '1 adet', grams: 80 },
      { name: 'Patates', amount: '1 adet küçük', grams: 100 },
      { name: 'Tereyağı', amount: '2 yemek kaşığı', grams: 30 },
      { name: 'Domates salçası', amount: '1 tatlı kaşığı' },
      { name: 'Un', amount: '1 yemek kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Karabiber', amount: '1 çimdik' },
      { name: 'Kimyon', amount: '1 çay kaşığı' },
      { name: 'Su', amount: '6 su bardağı' },
      { name: 'Limon', amount: 'yarım adet' },
    ],
    steps: [
      'Mercimeği iyice yıkayıp süzün.',
      'Soğanı, havucu ve patatesi küçük küpler halinde doğrayın.',
      'Tencerede tereyağını eritin; soğanı pembeleşene dek kavurun.',
      'Unu ekleyip bir dakika kadar kavurun, ardından salçayı ilave edin.',
      'Mercimek, havuç, patates ve suyu ekleyin; kaynayınca altını kısın.',
      'Yaklaşık 25 dakika, sebzeler dağılıp çorba koyulaşana dek pişirin.',
      'Blender ile pürüzsüz hale getirin; tuz, karabiber ve kimyonu ekleyin.',
      'Kaselerde üzerine limon sıkarak servis edin.',
    ],
    nutritionPerServing: { kcal: 220, proteinG: 11, carbsG: 32, fatG: 6 },
  },
  {
    id: 'ezogelin-corbasi',
    nameTr: 'Ezogelin Çorbası',
    nameEn: 'Ezogelin Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 35,
    difficulty: 'easy',
    tags: ['vegetarian', 'traditional', 'budget'],
    ingredients: [
      { name: 'Kırmızı mercimek', amount: 'yarım su bardağı', grams: 90 },
      { name: 'Bulgur (ince)', amount: '2 yemek kaşığı', grams: 30 },
      { name: 'Pirinç', amount: '1 yemek kaşığı', grams: 15 },
      { name: 'Soğan', amount: '1 adet', grams: 120 },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Biber salçası', amount: '1 tatlı kaşığı' },
      { name: 'Nane', amount: '1 çay kaşığı' },
      { name: 'Pul biber', amount: '1 çay kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Su', amount: '6 su bardağı' },
    ],
    steps: [
      'Mercimek, bulgur ve pirinci yıkayıp süzün.',
      'Tencerede tereyağını eritip ince doğranmış soğanı kavurun.',
      'Salçaları ekleyip 1 dakika çevirin.',
      'Yıkanmış tahılları ve suyu ekleyin, kaynatın.',
      'Kısık ateşte 25-30 dakika, mercimekler dağılana dek pişirin.',
      'Nane, pul biber ve tuzu ekleyip 2 dakika daha kaynatın.',
      'İsteğe göre blenderdan geçirin ya da taneli bırakın; sıcak servis edin.',
    ],
    nutritionPerServing: { kcal: 205, proteinG: 9, carbsG: 33, fatG: 5 },
  },
  {
    id: 'yayla-corbasi',
    nameTr: 'Yayla Çorbası',
    nameEn: 'Yogurt & Rice Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    difficulty: 'easy',
    tags: ['vegetarian', 'traditional'],
    ingredients: [
      { name: 'Pirinç', amount: '2 yemek kaşığı', grams: 30 },
      { name: 'Yoğurt', amount: '2 su bardağı', grams: 400 },
      { name: 'Yumurta sarısı', amount: '1 adet' },
      { name: 'Un', amount: '1 yemek kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Kuru nane', amount: '1 tatlı kaşığı' },
      { name: 'Pul biber', amount: '1 çay kaşığı' },
      { name: 'Su', amount: '5 su bardağı' },
    ],
    steps: [
      'Pirinci yıkayıp tencerede su ile kaynatın; 15 dakika haşlayın.',
      'Bir kasede yoğurt, un ve yumurta sarısını pürüzsüz olana kadar çırpın.',
      'Yoğurt karışımına yarım kepçe sıcak su azar azar ekleyerek ılıştırın (kesilmesin).',
      'Ilınan yoğurdu kaynayan pirince yavaşça, sürekli karıştırarak ilave edin.',
      'Tuzu ekleyip 5 dakika kısık ateşte kaynatın.',
      'Ayrı tavada tereyağını eritin; nane ve pul biberi ekleyip 15 saniye kavurun.',
      'Çorbayı kaselere alıp üzerine naneli tereyağını gezdirin.',
    ],
    nutritionPerServing: { kcal: 230, proteinG: 11, carbsG: 22, fatG: 11 },
  },
  {
    id: 'tarhana-corbasi',
    nameTr: 'Tarhana Çorbası',
    nameEn: 'Tarhana Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 5,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['vegetarian', 'traditional', 'budget'],
    ingredients: [
      { name: 'Tarhana', amount: '4 yemek kaşığı', grams: 60 },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Pul biber', amount: 'yarım çay kaşığı' },
      { name: 'Su veya et suyu', amount: '5 su bardağı' },
    ],
    steps: [
      'Tarhanayı 1 su bardağı ılık suda 10 dakika bekletip ezin.',
      'Tencerede tereyağını eritin, salçayı ekleyip kavurun.',
      'Tarhana karışımını ekleyip 2 dakika karıştırın.',
      'Kalan suyu ekleyip topaklanmaması için çırparak kaynatın.',
      'Kaynadıktan sonra kısık ateşte 15 dakika, sık sık karıştırarak pişirin.',
      'Tuz ve pul biberi ekleyip servis edin.',
    ],
    nutritionPerServing: { kcal: 180, proteinG: 6, carbsG: 22, fatG: 7 },
  },
  {
    id: 'domates-corbasi',
    nameTr: 'Domates Çorbası',
    nameEn: 'Tomato Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['vegetarian', 'student_friendly', 'quick'],
    ingredients: [
      { name: 'Olgun domates', amount: '4 adet', grams: 600 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Un', amount: '2 yemek kaşığı' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Süt', amount: '1 su bardağı' },
      { name: 'Kaşar peyniri (rende)', amount: 'yarım su bardağı', grams: 50 },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Su', amount: '4 su bardağı' },
    ],
    steps: [
      'Domateslerin kabuklarını soyup rendeleyin.',
      'Tereyağını tencerede eritin; ince doğranmış soğanı kavurun.',
      'Unu ekleyip 1 dakika çevirin; sütü yavaşça ilave edip topaklanmamasına dikkat edin.',
      'Domates ve suyu ekleyip kaynatın.',
      'Kısık ateşte 15 dakika pişirin; tuz ve karabiberi ekleyin.',
      'Kaselere alıp üzerine rendelenmiş kaşar serperek servis edin.',
    ],
    nutritionPerServing: { kcal: 215, proteinG: 8, carbsG: 20, fatG: 12 },
  },
  {
    id: 'tavuk-suyu-sehriye',
    nameTr: 'Tavuk Suyuna Şehriye Çorbası',
    nameEn: 'Chicken Noodle Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 40,
    difficulty: 'easy',
    tags: ['traditional', 'comfort', 'student_friendly'],
    ingredients: [
      { name: 'Tavuk göğsü', amount: '1 adet', grams: 200 },
      { name: 'Arpa şehriye', amount: 'yarım su bardağı', grams: 80 },
      { name: 'Havuç', amount: '1 adet' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Maydanoz', amount: '1 tutam' },
      { name: 'Limon', amount: 'yarım adet' },
      { name: 'Su', amount: '6 su bardağı' },
    ],
    steps: [
      'Tavuğu suda soğan ve havuçla birlikte 25 dakika haşlayın.',
      'Tavuğu çıkarıp didikleyin; suyu süzüp tenceresine alın.',
      'Tereyağını ayrı tencerede eritip şehriyeyi pembeleşene dek kavurun.',
      'Süzülmüş tavuk suyunu kavrulmuş şehriyeye ekleyin.',
      '10 dakika kaynatın; didiklenmiş tavukları ekleyin.',
      'Tuz, karabiber ve ince doğranmış maydanozu ekleyin; limon sıkarak servis edin.',
    ],
    nutritionPerServing: { kcal: 245, proteinG: 20, carbsG: 22, fatG: 8 },
  },
  {
    id: 'kremali-mantar-corbasi',
    nameTr: 'Kremalı Mantar Çorbası',
    nameEn: 'Creamy Mushroom Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['vegetarian', 'comfort'],
    ingredients: [
      { name: 'Kültür mantarı', amount: '400 g', grams: 400 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Un', amount: '2 yemek kaşığı' },
      { name: 'Süt', amount: '2 su bardağı' },
      { name: 'Krema', amount: 'yarım su bardağı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Su', amount: '3 su bardağı' },
    ],
    steps: [
      'Mantarları ince doğrayın; soğanı ve sarımsağı kıyın.',
      'Tencerede tereyağını eritip soğan-sarımsağı kavurun.',
      'Mantarları ekleyip suyunu çekene kadar pişirin.',
      'Unu ekleyip 1 dakika çevirin, ardından sütü yavaşça döküp karıştırın.',
      'Suyu ekleyin; kaynayınca 10 dakika pişirin.',
      'Bir kısmını blenderdan geçirip tekrar tencereye alın.',
      'Kremayı, tuzu ve karabiberi ekleyip 2 dakika daha ısıtın; servis edin.',
    ],
    nutritionPerServing: { kcal: 260, proteinG: 9, carbsG: 18, fatG: 17 },
  },
  {
    id: 'iskembe-corbasi',
    nameTr: 'İşkembe Çorbası',
    nameEn: 'Tripe Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 90,
    difficulty: 'medium',
    tags: ['traditional'],
    ingredients: [
      { name: 'Haşlanmış işkembe', amount: '500 g', grams: 500 },
      { name: 'Un', amount: '2 yemek kaşığı' },
      { name: 'Yumurta sarısı', amount: '1 adet' },
      { name: 'Limon', amount: '1 adet' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Sarımsak', amount: '4 diş' },
      { name: 'Sirke', amount: '2 yemek kaşığı' },
      { name: 'Kırmızı pul biber', amount: '1 çay kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Su', amount: '6 su bardağı' },
    ],
    steps: [
      'İşkembeleri küçük küpler halinde doğrayın.',
      'Tencerede tereyağını eritip unu 1 dakika kavurun.',
      'Suyu yavaşça ekleyip topak kalmayana kadar çırpın.',
      'İşkembeleri ekleyin ve 30 dakika kaynatın.',
      'Yumurta sarısını limon suyu ile çırpıp 1 kepçe sıcak çorba ile ılıştırın.',
      'Terbiye karışımını tencereye yavaşça ekleyin, 2 dakika daha ısıtın.',
      'Sosu hazırlayın: bir kasede ezilmiş sarımsak + sirke; başka kasede eritilmiş tereyağı + pul biber.',
      'Çorbayı kaselere alın; isteğe göre sarımsaklı sirke ve acılı yağ ile servis edin.',
    ],
    nutritionPerServing: { kcal: 290, proteinG: 22, carbsG: 10, fatG: 18 },
  },
  {
    id: 'dugun-corbasi',
    nameTr: 'Düğün Çorbası',
    nameEn: 'Wedding Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 60,
    difficulty: 'medium',
    tags: ['traditional'],
    ingredients: [
      { name: 'Kuzu kuşbaşı', amount: '250 g', grams: 250 },
      { name: 'Un', amount: '2 yemek kaşığı' },
      { name: 'Yumurta sarısı', amount: '1 adet' },
      { name: 'Yoğurt', amount: '1 su bardağı' },
      { name: 'Limon', amount: '1 adet' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Pul biber', amount: '1 tatlı kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Su', amount: '6 su bardağı' },
    ],
    steps: [
      'Kuzu etini suyla tencereye alın; köpüğünü alıp 40 dakika haşlayın.',
      'Eti çıkarın, suyu süzün; eti küçük parçalara ayırıp suya geri ekleyin.',
      'Bir kasede yoğurt, un ve yumurta sarısını pürüzsüz çırpın.',
      'Karışıma azar azar sıcak et suyu ekleyerek ılıştırın.',
      'Ilınan terbiyeyi çorbaya yavaşça dökerek karıştırın; 10 dakika kaynatın.',
      'Ayrı tavada tereyağını eritin, pul biberi ekleyin.',
      'Çorbayı kaselere alıp üzerine acılı yağı ve limon suyunu gezdirerek servis edin.',
    ],
    nutritionPerServing: { kcal: 310, proteinG: 22, carbsG: 12, fatG: 19 },
  },
  {
    id: 'brokoli-corbasi',
    nameTr: 'Brokoli Çorbası',
    nameEn: 'Broccoli Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['vegetarian', 'healthy'],
    ingredients: [
      { name: 'Brokoli', amount: '1 adet orta', grams: 500 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Patates', amount: '1 adet' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Süt', amount: '1 su bardağı' },
      { name: 'Kaşar peyniri', amount: '50 g', grams: 50 },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Su', amount: '4 su bardağı' },
    ],
    steps: [
      'Brokoliyi çiçeklerine ayırın, yıkayın; patatesi küpleyin.',
      'Tencerede tereyağını eritip soğanı kavurun.',
      'Patates ve suyu ekleyip 10 dakika pişirin.',
      'Brokoliyi ekleyip 8 dakika daha haşlayın.',
      'Tenceredeki içeriği blenderdan geçirin, sütü ilave edin.',
      'Tuz, karabiber ile tatlandırın; rende kaşarla servis edin.',
    ],
    nutritionPerServing: { kcal: 195, proteinG: 10, carbsG: 20, fatG: 9 },
  },
  {
    id: 'balkabagi-corbasi',
    nameTr: 'Balkabağı Çorbası',
    nameEn: 'Pumpkin Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    difficulty: 'easy',
    tags: ['vegetarian', 'healthy', 'autumn'],
    ingredients: [
      { name: 'Balkabağı', amount: '500 g', grams: 500 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Zencefil (rende)', amount: '1 çay kaşığı' },
      { name: 'Zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Süt', amount: '1 su bardağı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Su', amount: '4 su bardağı' },
    ],
    steps: [
      'Balkabağını kabuklarından ayırıp küp doğrayın.',
      'Zeytinyağında soğan ve sarımsağı kavurun.',
      'Balkabağı, zencefil ve suyu ekleyip kapak kapalı 20 dakika pişirin.',
      'Karışımı blenderdan pürüzsüz hale getirin.',
      'Sütü ekleyip 3 dakika daha ısıtın; tuz ve karabiber ekleyin.',
      'Üzerine kabak çekirdeği ile servis edebilirsiniz.',
    ],
    nutritionPerServing: { kcal: 165, proteinG: 5, carbsG: 22, fatG: 7 },
  },
  {
    id: 'kuru-fasulye-corbasi',
    nameTr: 'Kuru Fasulye Çorbası',
    nameEn: 'White Bean Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 480,
    cookMinutes: 60,
    difficulty: 'easy',
    tags: ['vegetarian', 'budget', 'high_protein'],
    ingredients: [
      { name: 'Kuru fasulye (gece suda)', amount: '1 su bardağı', grams: 180 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Domates', amount: '1 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Kuru nane', amount: '1 çay kaşığı' },
      { name: 'Su', amount: '6 su bardağı' },
    ],
    steps: [
      'Fasulyeleri bir gece önceden ılık suda ıslatın, ertesi gün süzün.',
      'Tencerede zeytinyağını ısıtıp soğan ve sarımsağı kavurun.',
      'Salçayı ekleyin; ardından rende domates ve suyu ilave edin.',
      'Fasulyeleri ekleyip kapak kapalı 45 dakika pişirin (düdüklüde 20 dk).',
      'Yumuşayan fasulyelerin yarısını ezin, çorbayı koyulaştırın.',
      'Tuz, karabiber ve naneyi ekleyip servis edin.',
    ],
    nutritionPerServing: { kcal: 275, proteinG: 14, carbsG: 34, fatG: 10 },
  },
  {
    id: 'mantar-salcali',
    nameTr: 'Salçalı Mantar Çorbası',
    nameEn: 'Mushroom Tomato Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    difficulty: 'easy',
    tags: ['vegetarian', 'quick', 'student_friendly'],
    ingredients: [
      { name: 'Kültür mantarı', amount: '300 g', grams: 300 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Biber salçası', amount: '1 tatlı kaşığı' },
      { name: 'Zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Un', amount: '1 yemek kaşığı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Su', amount: '5 su bardağı' },
    ],
    steps: [
      'Mantarları ve soğanı ince kıyın.',
      'Yağda soğanı kavurun; mantarları ekleyip suyunu çekene dek pişirin.',
      'Salçaları ekleyin, 1 dakika çevirin; unu da ekleyip bir dakika daha kavurun.',
      'Suyu yavaş yavaş döküp topak kalmadan karıştırın.',
      'Kaynayınca 10 dakika pişirin; baharatları ekleyerek servis edin.',
    ],
    nutritionPerServing: { kcal: 150, proteinG: 6, carbsG: 15, fatG: 8 },
  },
  {
    id: 'analı-kızlı',
    nameTr: 'Analı Kızlı Çorba',
    nameEn: 'Meatball & Chickpea Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 5,
    prepMinutes: 30,
    cookMinutes: 50,
    difficulty: 'medium',
    tags: ['traditional', 'high_protein'],
    ingredients: [
      { name: 'Dana kıyma', amount: '250 g', grams: 250 },
      { name: 'İnce bulgur', amount: '1 su bardağı', grams: 180 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Haşlanmış nohut', amount: '1 su bardağı', grams: 180 },
      { name: 'Domates salçası', amount: '2 yemek kaşığı' },
      { name: 'Biber salçası', amount: '1 yemek kaşığı' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Kuru nane', amount: '1 tatlı kaşığı' },
      { name: 'Pul biber', amount: '1 tatlı kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Su', amount: '7 su bardağı' },
    ],
    steps: [
      'Büyük köfteler için: ince bulguru sıcak suda 10 dk bekletin, kıyma, ezme soğan ve tuzla yoğurun; ceviz büyüklüğünde köfteler yapın.',
      'Küçük köfteler için (içli köfte gibi): ince bulguru biraz suyla yoğurup minik toplar yapın.',
      'Tencerede tereyağında salçaları kavurun.',
      'Suyu ekleyip kaynatın; büyük kıymalı köfteleri ekleyip 20 dakika pişirin.',
      'Haşlanmış nohut ve küçük köfteleri ilave edin; 15 dakika daha pişirin.',
      'Nane, pul biber ve tuzu ekleyin; servis edin.',
    ],
    nutritionPerServing: { kcal: 350, proteinG: 22, carbsG: 35, fatG: 14 },
  },
  {
    id: 'sebze-corbasi',
    nameTr: 'Sebze Çorbası',
    nameEn: 'Mixed Vegetable Soup',
    category: 'soup',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['vegetarian', 'healthy', 'budget'],
    ingredients: [
      { name: 'Havuç', amount: '1 adet' },
      { name: 'Patates', amount: '1 adet' },
      { name: 'Kabak', amount: '1 adet' },
      { name: 'Kereviz sapı', amount: '1 sap' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Domates', amount: '1 adet' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Su', amount: '6 su bardağı' },
    ],
    steps: [
      'Tüm sebzeleri küçük küpler halinde doğrayın.',
      'Tencerede yağı ısıtıp soğanı kavurun.',
      'Havuç, patates ve kerevizi ekleyip 5 dakika çevirin.',
      'Rende domates ve suyu ekleyin; kaynatın.',
      'Kabak ve baharatları ilave edip 15 dakika daha pişirin.',
      'İsteğe göre bir kısmını pürüzsüz hale getirip servis edin.',
    ],
    nutritionPerServing: { kcal: 140, proteinG: 3, carbsG: 20, fatG: 6 },
  },
];
