import type { RecipeSeed } from './_types.js';

/**
 * Recipes aimed at students and busy professionals: minimal equipment,
 * short prep, affordable ingredients. Most of these are done in <20 min.
 */
export const student: RecipeSeed[] = [
  {
    id: 'tuzlu-makarna',
    nameTr: 'Kalıp Tuzlu Makarna',
    nameEn: 'Butter & Cheese Pasta',
    category: 'student',
    cuisine: 'turkish',
    servings: 2,
    prepMinutes: 2,
    cookMinutes: 12,
    difficulty: 'easy',
    tags: ['quick', 'budget', 'student_friendly', 'vegetarian'],
    ingredients: [
      { name: 'Spagetti', amount: '200 g' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Kaşar veya beyaz peynir', amount: '60 g' },
      { name: 'Tuz', amount: 'tatmınıza göre' },
      { name: 'Karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Makarnayı tuzlu suda paket süresince haşlayıp süzün.',
      'Tencereye tekrar alın; tereyağını ekleyip karıştırın.',
      'Rende peynir ve karabiberle servis edin.',
    ],
    nutritionPerServing: { kcal: 420, proteinG: 14, carbsG: 60, fatG: 14 },
  },
  {
    id: 'karisik-tost',
    nameTr: 'Karışık Tost',
    nameEn: 'Turkish Grilled Sandwich',
    category: 'student',
    cuisine: 'turkish',
    servings: 2,
    prepMinutes: 3,
    cookMinutes: 5,
    difficulty: 'easy',
    tags: ['quick', 'student_friendly', 'budget'],
    ingredients: [
      { name: 'Tost ekmeği', amount: '4 dilim' },
      { name: 'Kaşar peyniri', amount: '4 dilim' },
      { name: 'Sucuk veya salam', amount: '4 dilim' },
      { name: 'Domates (dilim)', amount: '2 dilim' },
      { name: 'Tereyağı', amount: '1 yemek kaşığı' },
    ],
    steps: [
      'Ekmeklere tereyağı sürün.',
      'Aralarına sucuk, peynir ve domates dilimlerini yerleştirin.',
      'Tost makinesinde veya tavada her iki yüzü 2-3 dakika kızartın.',
    ],
    nutritionPerServing: { kcal: 440, proteinG: 22, carbsG: 32, fatG: 24 },
  },
  {
    id: 'sahanda-yumurta',
    nameTr: 'Sahanda Yumurta',
    nameEn: 'Sunny-Side Egg',
    category: 'student',
    cuisine: 'turkish',
    servings: 1,
    prepMinutes: 1,
    cookMinutes: 3,
    difficulty: 'easy',
    tags: ['quick', 'student_friendly', 'budget', 'vegetarian'],
    ingredients: [
      { name: 'Yumurta', amount: '2 adet' },
      { name: 'Tereyağı', amount: '1 yemek kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Küçük tavada tereyağını eritin.',
      'Yumurtaları kırın.',
      'Kısık ateşte beyazı kuruyana dek 2-3 dakika pişirin; tuz ve karabiber.',
    ],
    nutritionPerServing: { kcal: 220, proteinG: 12, carbsG: 1, fatG: 18 },
  },
  {
    id: 'tuna-makarna',
    nameTr: 'Ton Balıklı Makarna',
    nameEn: 'Tuna Pasta',
    category: 'student',
    cuisine: 'international',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 15,
    difficulty: 'easy',
    tags: ['quick', 'student_friendly', 'high_protein'],
    ingredients: [
      { name: 'Makarna', amount: '200 g' },
      { name: 'Ton balığı konservesi', amount: '1 adet' },
      { name: 'Zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Cherry domates', amount: '8 adet' },
      { name: 'Limon', amount: 'yarım adet' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Maydanoz', amount: '2 dal' },
    ],
    steps: [
      'Makarnayı al dente haşlayın; 1 kepçe suyunu ayırıp süzün.',
      'Tavada yağda sarımsağı kavurun; cherry domatesleri ekleyip 2 dk pişirin.',
      'Süzülmüş ton balığını ekleyin; makarnayı ve bir miktar haşlama suyunu ekleyin.',
      'Limon, baharatlar ve maydanozu ekleyip servis edin.',
    ],
    nutritionPerServing: { kcal: 510, proteinG: 28, carbsG: 62, fatG: 16 },
  },
  {
    id: 'firinda-tavuk-gogsu-tek-tepsi',
    nameTr: 'Tek Tepsi Fırın Tavuk + Sebze',
    nameEn: 'Sheet Pan Chicken & Vegetables',
    category: 'student',
    cuisine: 'international',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    difficulty: 'easy',
    tags: ['one_pan', 'healthy', 'high_protein', 'student_friendly'],
    ingredients: [
      { name: 'Tavuk göğüs', amount: '500 g' },
      { name: 'Brokoli', amount: '1 demet' },
      { name: 'Patates', amount: '2 adet' },
      { name: 'Havuç', amount: '2 adet' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Sarımsak', amount: '3 diş' },
      { name: 'Limon', amount: '1 adet' },
      { name: 'Tuz, karabiber, kekik', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Fırını 200°C\'ye ısıtın.',
      'Sebzeleri benzer boyda doğrayın.',
      'Tavuk göğsünü küp doğrayın.',
      'Hepsini tepsiye alın; yağ, ezilmiş sarımsak, limon ve baharatlarla karıştırın.',
      'Tek katta yayın; 25-30 dakika, sebzeler kızarana dek pişirin.',
    ],
    nutritionPerServing: { kcal: 380, proteinG: 32, carbsG: 30, fatG: 14 },
  },
  {
    id: 'bulgur-kahvalti-kasesi',
    nameTr: 'Baharatlı Pirinç Kase',
    nameEn: 'Spiced Rice Bowl',
    category: 'student',
    cuisine: 'international',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 20,
    difficulty: 'easy',
    tags: ['quick', 'student_friendly', 'vegetarian', 'budget'],
    ingredients: [
      { name: 'Pirinç veya bulgur', amount: '1 su bardağı' },
      { name: 'Haşlanmış nohut veya fasulye', amount: '1 su bardağı' },
      { name: 'Avokado', amount: 'yarım adet' },
      { name: 'Domates', amount: '1 adet' },
      { name: 'Haşlanmış yumurta (opsiyonel)', amount: '2 adet' },
      { name: 'Zeytinyağı, limon', amount: '1\'er yemek kaşığı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Pirinç/bulguru paket üzerindeki süreye göre haşlayın.',
      'Domatesi küp, avokadoyu dilim doğrayın; yumurtayı iki bölün.',
      'Tahılı kaseye alıp baklagil, sebzeler ve yumurtayı yerleştirin.',
      'Yağ, limon ve baharatları üzerine dökün.',
    ],
    nutritionPerServing: { kcal: 520, proteinG: 20, carbsG: 70, fatG: 17 },
  },
  {
    id: 'chili-con-carne',
    nameTr: 'Acılı Kıymalı Fasulye (Chili con Carne)',
    nameEn: 'Chili con Carne',
    category: 'student',
    cuisine: 'international',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 35,
    difficulty: 'easy',
    tags: ['one_pot', 'high_protein', 'spicy', 'comfort'],
    ingredients: [
      { name: 'Dana kıyma', amount: '400 g' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sarımsak', amount: '3 diş' },
      { name: 'Konserve kırmızı fasulye', amount: '1 kutu' },
      { name: 'Konserve domates (doğranmış)', amount: '1 kutu' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Kapya biber', amount: '1 adet' },
      { name: 'Sıvı yağ', amount: '2 yemek kaşığı' },
      { name: 'Kimyon, pul biber, kekik', amount: 'tatmınıza göre' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Tencerede yağ ile soğan ve sarımsağı kavurun.',
      'Kıymayı ekleyip suyunu çekene dek pişirin.',
      'Doğranmış biberi ve salçayı ekleyip 1 dk çevirin.',
      'Konserve fasulye ve domatesi ekleyin; baharatları ilave edin.',
      'Kısık ateşte 25 dakika kaynatın.',
      'Pirinç pilavı, nachos veya ekmekle servis edin.',
    ],
    nutritionPerServing: { kcal: 420, proteinG: 28, carbsG: 26, fatG: 22 },
  },
  {
    id: 'basit-domatesli-pirinc-corbasi',
    nameTr: 'Hızlı Salçalı Pirinç Çorbası',
    nameEn: 'Quick Tomato Rice Soup',
    category: 'student',
    cuisine: 'turkish',
    servings: 3,
    prepMinutes: 3,
    cookMinutes: 20,
    difficulty: 'easy',
    tags: ['quick', 'budget', 'student_friendly', 'vegetarian'],
    ingredients: [
      { name: 'Pirinç', amount: 'yarım su bardağı' },
      { name: 'Tereyağı', amount: '2 yemek kaşığı' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Su', amount: '5 su bardağı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Kuru nane', amount: '1 çay kaşığı' },
    ],
    steps: [
      'Tencerede tereyağını eritip salçayı 30 saniye kavurun.',
      'Yıkanmış pirinci ekleyin, 1 dk çevirin.',
      'Suyu ekleyip kaynatın; pirinç pişene dek 15 dk kısık ateşte pişirin.',
      'Tuz, karabiber, nane ekleyip servis edin.',
    ],
    nutritionPerServing: { kcal: 180, proteinG: 3, carbsG: 30, fatG: 6 },
  },
  {
    id: 'patates-wedges',
    nameTr: 'Fırında Baharatlı Patates',
    nameEn: 'Spiced Potato Wedges',
    category: 'student',
    cuisine: 'international',
    servings: 3,
    prepMinutes: 10,
    cookMinutes: 30,
    difficulty: 'easy',
    tags: ['vegetarian', 'student_friendly', 'oven', 'budget'],
    ingredients: [
      { name: 'Patates', amount: '4 adet' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Kekik, pul biber', amount: '1\'er çay kaşığı' },
      { name: 'Toz sarımsak', amount: '1 çay kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Parmesan (opsiyonel)', amount: '2 yemek kaşığı' },
    ],
    steps: [
      'Patatesleri yıkayıp kabuklu dilim dilim kesin.',
      'Yağ ve baharatlarla karıştırıp tepsiye dizin.',
      '210°C fırında 25-30 dakika, altın rengi olana dek pişirin.',
      'Üzerine parmesan serperek servis edin.',
    ],
    nutritionPerServing: { kcal: 300, proteinG: 5, carbsG: 45, fatG: 12 },
  },
  {
    id: 'kiymali-pizza-tost',
    nameTr: 'Lavaş Pizza',
    nameEn: 'Lavash Pizza',
    category: 'student',
    cuisine: 'turkish',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 10,
    difficulty: 'easy',
    tags: ['quick', 'student_friendly'],
    ingredients: [
      { name: 'Lavaş', amount: '2 adet' },
      { name: 'Domates sos veya salça', amount: '3 yemek kaşığı' },
      { name: 'Kaşar peyniri', amount: '150 g' },
      { name: 'Sucuk veya salam', amount: '6 dilim' },
      { name: 'Kapya biber, mantar', amount: 'yeterince' },
      { name: 'Kekik, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Lavaşları tepsiye serip üzerine salçayı/sosu sürün.',
      'Rende kaşar, kıyılmış biber, mantar ve sucuğu yerleştirin.',
      '200°C fırında 8-10 dakika kızartın.',
      'Üzerine kekik ve pul biber serpip dilimleyin.',
    ],
    nutritionPerServing: { kcal: 520, proteinG: 22, carbsG: 45, fatG: 28 },
  },
  {
    id: 'sade-omlet-peynirli-ekmek',
    nameTr: 'Peynirli Yumurta Roll',
    nameEn: 'Cheese Egg Wrap',
    category: 'student',
    cuisine: 'international',
    servings: 1,
    prepMinutes: 3,
    cookMinutes: 5,
    difficulty: 'easy',
    tags: ['quick', 'student_friendly', 'vegetarian'],
    ingredients: [
      { name: 'Yumurta', amount: '2 adet' },
      { name: 'Lavaş / tortilla', amount: '1 adet' },
      { name: 'Beyaz veya krem peynir', amount: '2 yemek kaşığı' },
      { name: 'Ispanak yaprağı veya maydanoz', amount: '1 tutam' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Tereyağı', amount: '1 tatlı kaşığı' },
    ],
    steps: [
      'Yumurtaları çırpın; tereyağlı tavada yumurta perdesi yapın.',
      'Omleti lavaşın üstüne koyun; peynir ve ıspanağı ekleyin.',
      'Baharatları serpin, sıkıca sarın ve ortadan kesin.',
    ],
    nutritionPerServing: { kcal: 360, proteinG: 22, carbsG: 22, fatG: 20 },
  },
  {
    id: 'sebzeli-noodle',
    nameTr: 'Sebzeli Noodle',
    nameEn: 'Vegetable Noodles',
    category: 'student',
    cuisine: 'asian',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 12,
    difficulty: 'easy',
    tags: ['quick', 'vegetarian', 'student_friendly'],
    ingredients: [
      { name: 'Noodle (erişte)', amount: '200 g' },
      { name: 'Havuç', amount: '1 adet' },
      { name: 'Kapya biber', amount: '1 adet' },
      { name: 'Soğan', amount: 'yarım adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Soya sosu', amount: '2 yemek kaşığı' },
      { name: 'Susam yağı veya sıvı yağ', amount: '2 yemek kaşığı' },
      { name: 'Zencefil (rende)', amount: '1 çay kaşığı' },
      { name: 'Taze soğan', amount: '2 dal' },
    ],
    steps: [
      'Noodle\'ları paket üzerindeki süreyle haşlayıp süzün.',
      'Wok veya tavada yağı kızdırın; sarımsak ve zencefili ekleyin.',
      'Julyen doğranmış havuç, biber ve soğanı 4-5 dakika çevirin.',
      'Noodle\'ları, soya sosunu ekleyip 2 dk daha soteleyin.',
      'Üzerine taze soğan serperek servis edin.',
    ],
    nutritionPerServing: { kcal: 420, proteinG: 10, carbsG: 68, fatG: 12 },
  },
  {
    id: 'salatalik-sandvic',
    nameTr: 'Peynirli Salatalık Sandviç',
    nameEn: 'Cucumber Cheese Sandwich',
    category: 'student',
    cuisine: 'international',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['quick', 'no_cook', 'vegetarian', 'student_friendly'],
    ingredients: [
      { name: 'Tam buğday ekmeği', amount: '2 dilim' },
      { name: 'Krem peynir veya labne', amount: '2 yemek kaşığı' },
      { name: 'Salatalık (dilim)', amount: '1 adet' },
      { name: 'Domates', amount: 'yarım adet' },
      { name: 'Roka', amount: '1 avuç' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Ekmeklere labne sürün.',
      'Salatalık, domates ve rokayı yerleştirin.',
      'Tuz ve karabiber ekleyip kapatıp servis edin.',
    ],
    nutritionPerServing: { kcal: 290, proteinG: 10, carbsG: 32, fatG: 14 },
  },
  {
    id: 'patates-salatasi',
    nameTr: 'Patates Salatası',
    nameEn: 'Potato Salad',
    category: 'student',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    difficulty: 'easy',
    tags: ['vegetarian', 'student_friendly', 'budget'],
    ingredients: [
      { name: 'Patates', amount: '4 adet' },
      { name: 'Haşlanmış yumurta', amount: '2 adet' },
      { name: 'Kornişon turşu', amount: 'yarım su bardağı' },
      { name: 'Maydanoz', amount: '1 demet' },
      { name: 'Taze soğan', amount: '2 dal' },
      { name: 'Zeytinyağı', amount: '3 yemek kaşığı' },
      { name: 'Limon', amount: '1 adet' },
      { name: 'Tuz, karabiber, sumak', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Patatesleri haşlayıp soyun, küp doğrayın; soğutun.',
      'Yumurtaları da küp doğrayın.',
      'Kıyılmış maydanoz, taze soğan ve turşuyu ekleyin.',
      'Yağ, limon, tuz, karabiber ve sumakla karıştırın.',
      'Soğuk servis edin.',
    ],
    nutritionPerServing: { kcal: 260, proteinG: 8, carbsG: 35, fatG: 10 },
  },
  {
    id: 'basit-chia-pudding',
    nameTr: 'Chia Pudding',
    nameEn: 'Chia Pudding',
    category: 'student',
    cuisine: 'international',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['quick', 'healthy', 'make_ahead', 'vegetarian', 'vegan'],
    ingredients: [
      { name: 'Chia tohumu', amount: '3 yemek kaşığı' },
      { name: 'Süt veya bitkisel süt', amount: '1 su bardağı' },
      { name: 'Bal veya akçaağaç şurubu', amount: '1 tatlı kaşığı' },
      { name: 'Vanilya', amount: '1 tutam' },
      { name: 'Meyve (muz, çilek vb.)', amount: 'servis için' },
    ],
    steps: [
      'Kavanozda chia, süt, bal ve vanilyayı karıştırın.',
      'Buzdolabında en az 4 saat (veya gece) bekletin.',
      'Üstüne meyve ekleyerek servis edin.',
    ],
    nutritionPerServing: { kcal: 280, proteinG: 8, carbsG: 32, fatG: 13 },
  },
  {
    id: 'yogurtlu-meyve-granola',
    nameTr: 'Yoğurt Granola Kasesi',
    nameEn: 'Yogurt Granola Bowl',
    category: 'student',
    cuisine: 'international',
    servings: 1,
    prepMinutes: 3,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['quick', 'healthy', 'no_cook', 'vegetarian', 'student_friendly'],
    ingredients: [
      { name: 'Yoğurt veya süzme yoğurt', amount: '1 su bardağı' },
      { name: 'Granola veya yulaf', amount: '3 yemek kaşığı' },
      { name: 'Muz', amount: '1 adet' },
      { name: 'Çilek veya yaban mersini', amount: '1 avuç' },
      { name: 'Bal', amount: '1 tatlı kaşığı' },
      { name: 'Chia veya keten', amount: '1 tatlı kaşığı' },
    ],
    steps: [
      'Kaseye yoğurdu alın.',
      'Üzerine granola, meyve ve tohumları serpin.',
      'Balı gezdirip servis edin.',
    ],
    nutritionPerServing: { kcal: 360, proteinG: 15, carbsG: 55, fatG: 8 },
  },
  {
    id: 'tavuk-wrap',
    nameTr: 'Tavuk Wrap',
    nameEn: 'Chicken Wrap',
    category: 'student',
    cuisine: 'international',
    servings: 2,
    prepMinutes: 10,
    cookMinutes: 10,
    difficulty: 'easy',
    tags: ['quick', 'high_protein', 'student_friendly'],
    ingredients: [
      { name: 'Tavuk göğüs (şerit)', amount: '250 g' },
      { name: 'Lavaş', amount: '2 adet' },
      { name: 'Yoğurtlu sos veya mayonez', amount: '3 yemek kaşığı' },
      { name: 'Marul', amount: '4 yaprak' },
      { name: 'Domates', amount: '1 adet' },
      { name: 'Turşu', amount: '2 adet' },
      { name: 'Zeytinyağı', amount: '1 yemek kaşığı' },
      { name: 'Tuz, karabiber, kekik', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Tavukları baharatlarla marine edin; tavada yağda 6-7 dk soteleyin.',
      'Lavaşları hafif ısıtın; sosu sürün.',
      'Marul, domates, turşu ve tavukları yerleştirin.',
      'Sıkıca sarın, ortadan kesin.',
    ],
    nutritionPerServing: { kcal: 480, proteinG: 32, carbsG: 42, fatG: 18 },
  },
  {
    id: 'haslanmis-yumurta-avokado',
    nameTr: 'Avokadolu Yumurta Tabağı',
    nameEn: 'Avocado Egg Plate',
    category: 'student',
    cuisine: 'international',
    servings: 1,
    prepMinutes: 5,
    cookMinutes: 8,
    difficulty: 'easy',
    tags: ['quick', 'healthy', 'high_protein', 'vegetarian', 'student_friendly'],
    ingredients: [
      { name: 'Haşlanmış yumurta', amount: '2 adet' },
      { name: 'Avokado', amount: 'yarım adet' },
      { name: 'Cherry domates', amount: '5 adet' },
      { name: 'Limon', amount: 'yarım adet' },
      { name: 'Tam buğday ekmeği', amount: '1 dilim' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Yumurtaları 8 dk haşlayıp soğuk suya alın, soyup ikiye bölün.',
      'Avokadoyu dilim dilim kesip limon sıkın.',
      'Tabağa avokado, yumurta ve ikiye kesilmiş domatesleri dizin.',
      'Tuz, karabiber ve pul biber serpin; ekmekle servis edin.',
    ],
    nutritionPerServing: { kcal: 420, proteinG: 20, carbsG: 25, fatG: 28 },
  },
  {
    id: 'kofte-durum',
    nameTr: 'Köfte Dürüm (Hazır Köfteyle)',
    nameEn: 'Meatball Wrap',
    category: 'student',
    cuisine: 'turkish',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 10,
    difficulty: 'easy',
    tags: ['quick', 'student_friendly'],
    ingredients: [
      { name: 'Hazır köfte veya kalan ızgara köfte', amount: '8 adet' },
      { name: 'Lavaş', amount: '2 adet' },
      { name: 'Domates, soğan, marul', amount: 'yeterince' },
      { name: 'Sumak', amount: '1 çay kaşığı' },
      { name: 'Yoğurtlu sos', amount: '3 yemek kaşığı' },
    ],
    steps: [
      'Köfteleri tavada 5 dk ısıtın.',
      'Lavaşı hafif ısıtıp sos sürün.',
      'Marul, domates, sumaklı soğan ve köfteleri yerleştirin.',
      'Dürüm yapıp ortasından kesin.',
    ],
    nutritionPerServing: { kcal: 520, proteinG: 26, carbsG: 48, fatG: 24 },
  },
  {
    id: 'fasulye-kekigi-salata',
    nameTr: '5 Dakikalık Konserve Fasulye Salatası',
    nameEn: '5-Minute Bean Salad',
    category: 'student',
    cuisine: 'international',
    servings: 2,
    prepMinutes: 5,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['quick', 'no_cook', 'student_friendly', 'vegetarian', 'vegan', 'high_protein'],
    ingredients: [
      { name: 'Konserve barbunya veya beyaz fasulye', amount: '1 kutu' },
      { name: 'Kırmızı soğan', amount: 'yarım adet' },
      { name: 'Cherry domates', amount: '10 adet' },
      { name: 'Maydanoz', amount: '1 avuç' },
      { name: 'Zeytinyağı, limon', amount: '2\'şer yemek kaşığı' },
      { name: 'Tuz, sumak, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Fasulyeleri süzüp durulayın.',
      'Soğan, domates ve maydanozu doğrayın.',
      'Hepsini karıştırıp yağ, limon ve baharatları ekleyin.',
    ],
    nutritionPerServing: { kcal: 280, proteinG: 12, carbsG: 32, fatG: 12 },
  },
];
