import type { RecipeSeed } from './_types.js';

export const vegMains: RecipeSeed[] = [
  {
    id: 'imambayildi',
    nameTr: 'İmambayıldı',
    nameEn: 'Imam Bayildi',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 45,
    difficulty: 'medium',
    tags: ['vegetarian', 'vegan', 'olive_oil', 'traditional'],
    ingredients: [
      { name: 'Uzun patlıcan', amount: '4 adet' },
      { name: 'Soğan', amount: '2 adet' },
      { name: 'Domates', amount: '3 adet' },
      { name: 'Sarımsak', amount: '4 diş' },
      { name: 'Zeytinyağı', amount: 'yarım su bardağı' },
      { name: 'Şeker', amount: '1 çay kaşığı' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '1 su bardağı' },
    ],
    steps: [
      'Patlıcanların kabuklarını alaca soyup tuzlu suda 15 dakika bekletin; kurulayın.',
      'Tavada az yağla patlıcanları her tarafı hafif kızartın.',
      'İç harç için: soğanı ince yarım ay, sarımsakları dilim doğrayın; zeytinyağında kavurun.',
      'Doğranmış domates ve maydanozu ekleyip 5 dakika pişirin; tuz, karabiber, şeker.',
      'Patlıcanları tepsiye yan dizip üzerlerine uzunlamasına yarık açın.',
      'Her yarık içine harçtan bolca doldurun; üstte birer domates dilimi yerleştirin.',
      'Sıcak su ve zeytinyağı ekleyip 180°C fırında 30-35 dakika pişirin.',
      'Oda sıcaklığında servis edin.',
    ],
    nutritionPerServing: { kcal: 280, proteinG: 4, carbsG: 22, fatG: 20 },
  },
  {
    id: 'taze-fasulye',
    nameTr: 'Zeytinyağlı Taze Fasulye',
    nameEn: 'Green Beans in Olive Oil',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 30,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'olive_oil', 'healthy'],
    ingredients: [
      { name: 'Taze fasulye', amount: '500 g', grams: 500 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Domates', amount: '2 adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Zeytinyağı', amount: '5 yemek kaşığı' },
      { name: 'Şeker', amount: '1 çay kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Sıcak su', amount: '1 su bardağı' },
    ],
    steps: [
      'Fasulyelerin uçlarını kırın, kılçıklarını alın, ikiye bölün.',
      'Tencerede zeytinyağında ince doğranmış soğanı kavurun.',
      'Fasulyeleri ekleyip 2-3 dakika çevirin.',
      'Doğranmış sarımsak, rende domates, şeker, tuz ve sıcak suyu ekleyin.',
      'Kapağı kapalı kısık ateşte 25-30 dakika pişirin.',
      'Soğuk servis edin.',
    ],
    nutritionPerServing: { kcal: 210, proteinG: 4, carbsG: 16, fatG: 15 },
  },
  {
    id: 'zeytinyagli-barbunya',
    nameTr: 'Zeytinyağlı Barbunya',
    nameEn: 'Borlotti Beans in Olive Oil',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 480,
    cookMinutes: 60,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'olive_oil', 'high_protein'],
    ingredients: [
      { name: 'Kuru barbunya (gece suda)', amount: '1,5 su bardağı', grams: 270 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Havuç', amount: '1 adet' },
      { name: 'Domates', amount: '1 adet' },
      { name: 'Domates salçası', amount: '1 tatlı kaşığı' },
      { name: 'Zeytinyağı', amount: 'yarım su bardağı' },
      { name: 'Şeker', amount: '1 çay kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Sıcak su', amount: '3 su bardağı' },
    ],
    steps: [
      'Barbunyayı bir gece öncesinden suda bekletin; ertesi gün süzün.',
      'Tencerede zeytinyağını ısıtıp ince soğanı kavurun.',
      'Küp havuç ve salçayı ekleyip 1 dakika çevirin.',
      'Barbunya, domates ve sıcak suyu ekleyin; 45-55 dakika (düdüklüde 20 dk) pişirin.',
      'Şeker ve tuzu son 10 dakikada ekleyin.',
      'Soğuk olarak limon ve maydanozla servis edin.',
    ],
    nutritionPerServing: { kcal: 340, proteinG: 13, carbsG: 42, fatG: 14 },
  },
  {
    id: 'sebze-turlusu',
    nameTr: 'Sebze Türlüsü',
    nameEn: 'Mixed Vegetable Stew',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 5,
    prepMinutes: 20,
    cookMinutes: 50,
    difficulty: 'easy',
    tags: ['vegetarian', 'healthy', 'traditional'],
    ingredients: [
      { name: 'Patlıcan', amount: '2 adet' },
      { name: 'Patates', amount: '2 adet' },
      { name: 'Kabak', amount: '2 adet' },
      { name: 'Taze fasulye', amount: '200 g' },
      { name: 'Kapya biber', amount: '1 adet' },
      { name: 'Domates', amount: '3 adet' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sarımsak', amount: '3 diş' },
      { name: 'Zeytinyağı', amount: '5 yemek kaşığı' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Tüm sebzeleri iri küpler halinde doğrayın; patlıcanları tuzlu suda 10 dk bekletin.',
      'Tencerede yağı ısıtıp soğan ve sarımsağı kavurun.',
      'Salça ve rende domatesleri ekleyip 2 dakika çevirin.',
      'Sebzeleri sırasıyla ekleyip karıştırın (patates, fasulye önce; patlıcan, kabak sonra).',
      'Kapağı kapalı kendi suyunda 40 dakika pişirin.',
      'Tuz ve karabiberi ekleyip servis edin.',
    ],
    nutritionPerServing: { kcal: 240, proteinG: 5, carbsG: 28, fatG: 13 },
  },
  {
    id: 'mucver',
    nameTr: 'Kabak Mücveri',
    nameEn: 'Zucchini Fritters',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    difficulty: 'easy',
    tags: ['vegetarian', 'quick', 'student_friendly'],
    ingredients: [
      { name: 'Kabak (rende)', amount: '3 adet', grams: 500 },
      { name: 'Yumurta', amount: '3 adet' },
      { name: 'Un', amount: 'yarım su bardağı' },
      { name: 'Beyaz peynir', amount: '100 g' },
      { name: 'Dereotu', amount: 'yarım demet' },
      { name: 'Maydanoz', amount: '2 dal' },
      { name: 'Taze soğan', amount: '3 dal' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Sıvı yağ (kızartma için)', amount: 'yeterince' },
    ],
    steps: [
      'Rende kabağı tuzlayıp 10 dakika bekletin; suyunu iyice sıkın.',
      'Yumurtaları çırpın; ufalanmış peynir ve yeşillikleri ekleyin.',
      'Unu ve baharatları ilave edip karıştırın; kabakları ekleyin.',
      'Tavada yağı kızdırın; kaşıklarla yağa harç koyup pişirin.',
      'Her yüzü 2-3 dakika altın rengine gelince çıkarın.',
      'Sarımsaklı yoğurt ile servis edin.',
    ],
    nutritionPerServing: { kcal: 310, proteinG: 14, carbsG: 20, fatG: 20 },
  },
  {
    id: 'karniyarik',
    nameTr: 'Karnıyarık',
    nameEn: 'Stuffed Eggplants',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 25,
    cookMinutes: 40,
    difficulty: 'medium',
    tags: ['traditional', 'comfort'],
    ingredients: [
      { name: 'Uzun patlıcan', amount: '6 adet' },
      { name: 'Dana kıyma', amount: '300 g', grams: 300 },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Domates', amount: '3 adet' },
      { name: 'Sivri biber', amount: '6 adet' },
      { name: 'Maydanoz', amount: 'yarım demet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Sıvı yağ', amount: 'kızartma için' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Patlıcanları alaca soyup tuzlu suda 15 dk bekletin; kurulayın, yağda kızartın.',
      'İç harç için: soğanı yağda kavurun, kıymayı ekleyin.',
      'Doğranmış sarımsak, küp domates, salça, maydanoz ve baharatları ekleyip 10 dakika pişirin.',
      'Patlıcanları tepsiye dizip ortalarına uzunlamasına yarık açın.',
      'Her yarık içine harç doldurun; üstüne birer domates ve biber dilimi koyun.',
      '180°C fırında 25-30 dakika pişirin.',
    ],
    nutritionPerServing: { kcal: 420, proteinG: 18, carbsG: 22, fatG: 28 },
  },
  {
    id: 'kabak-kalyesi',
    nameTr: 'Kabak Kalye',
    nameEn: 'Zucchini Stew',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'olive_oil', 'quick'],
    ingredients: [
      { name: 'Sakız kabağı', amount: '4 adet', grams: 600 },
      { name: 'Kuru soğan', amount: '1 adet' },
      { name: 'Domates', amount: '2 adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Zeytinyağı', amount: '4 yemek kaşığı' },
      { name: 'Şeker', amount: '1 çay kaşığı' },
      { name: 'Kuru nane', amount: '1 çay kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Kabakları kalın dilimler halinde doğrayın.',
      'Tencerede zeytinyağında ince soğanı kavurun.',
      'Sarımsak ve domatesi ekleyip 2 dakika pişirin.',
      'Kabakları, şeker ve yarım bardak suyu ekleyin.',
      'Kapağı kapalı 15 dakika pişirin; nane ve baharatları ekleyin.',
    ],
    nutritionPerServing: { kcal: 180, proteinG: 3, carbsG: 12, fatG: 13 },
  },
  {
    id: 'zeytinyagli-enginar',
    nameTr: 'Zeytinyağlı Enginar',
    nameEn: 'Artichokes in Olive Oil',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 35,
    difficulty: 'medium',
    tags: ['vegetarian', 'vegan', 'olive_oil'],
    ingredients: [
      { name: 'Enginar (taze veya dondurulmuş)', amount: '6 adet' },
      { name: 'Havuç', amount: '2 adet' },
      { name: 'Bezelye', amount: '1 su bardağı' },
      { name: 'Patates (küp)', amount: '1 adet' },
      { name: 'Kuru soğan', amount: '1 adet' },
      { name: 'Zeytinyağı', amount: 'yarım su bardağı' },
      { name: 'Şeker', amount: '1 çay kaşığı' },
      { name: 'Un', amount: '1 yemek kaşığı' },
      { name: 'Limon', amount: '1 adet' },
      { name: 'Dereotu', amount: 'yarım demet' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Sıcak su', amount: '2 su bardağı' },
    ],
    steps: [
      'Tencerede zeytinyağını ısıtıp ince doğranmış soğanı kavurun.',
      'Küp havuç ve patatesi ekleyip 3 dakika çevirin.',
      'Enginarları, bezelyeleri, sıcak suyu, limon suyunu, şekeri, tuzu ve unu ekleyin.',
      'Kapağı kapalı kısık ateşte 25-30 dakika pişirin.',
      'Son olarak kıyılmış dereotunu ekleyin; soğuk servis edin.',
    ],
    nutritionPerServing: { kcal: 290, proteinG: 6, carbsG: 26, fatG: 18 },
  },
  {
    id: 'kiymali-bamya',
    nameTr: 'Kıymalı Bamya',
    nameEn: 'Okra with Ground Beef',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 30,
    difficulty: 'easy',
    tags: ['traditional', 'comfort'],
    ingredients: [
      { name: 'Bamya (taze veya kuru)', amount: '400 g' },
      { name: 'Dana kıyma', amount: '250 g' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Domates', amount: '2 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Sıvı yağ', amount: '3 yemek kaşığı' },
      { name: 'Limon', amount: 'yarım adet' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '1,5 su bardağı' },
    ],
    steps: [
      'Bamyaların saplarını konik şekilde yontun; sirke-limon karışımında 5 dakika bekletin.',
      'Tencerede yağ ile kıymayı kavurun; soğanı ekleyin.',
      'Salça ve domatesleri ekleyip 2 dakika çevirin.',
      'Bamyayı, sıcak suyu ve limon suyunu ekleyin.',
      'Kısık ateşte 20-25 dakika, kapağı kapalı pişirin.',
      'Pilav ile servis edin.',
    ],
    nutritionPerServing: { kcal: 280, proteinG: 18, carbsG: 15, fatG: 16 },
  },
  {
    id: 'ispanak-yemegi',
    nameTr: 'Ispanak Yemeği (Zeytinyağlı)',
    nameEn: 'Spinach in Olive Oil',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'olive_oil', 'iron_rich', 'quick'],
    ingredients: [
      { name: 'Ispanak', amount: '750 g' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Pirinç', amount: '2 yemek kaşığı' },
      { name: 'Domates salçası', amount: '1 tatlı kaşığı' },
      { name: 'Zeytinyağı', amount: '4 yemek kaşığı' },
      { name: 'Şeker', amount: '1 çay kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '1 su bardağı' },
    ],
    steps: [
      'Ispanakları iyice yıkayıp iri doğrayın.',
      'Tencerede yağda ince soğanı kavurun.',
      'Salçayı ekleyin; pirinç ve sıcak suyu ilave edin.',
      'Ispanakları ekleyip karıştırın; 15 dakika kısık ateşte pişirin.',
      'Şeker, tuz ve karabiberi ekleyin; soğuk servis edin.',
    ],
    nutritionPerServing: { kcal: 180, proteinG: 5, carbsG: 14, fatG: 12 },
  },
  {
    id: 'yaprak-sarma',
    nameTr: 'Zeytinyağlı Yaprak Sarma',
    nameEn: 'Stuffed Grape Leaves',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 5,
    prepMinutes: 45,
    cookMinutes: 50,
    difficulty: 'hard',
    tags: ['vegetarian', 'vegan', 'olive_oil', 'traditional'],
    ingredients: [
      { name: 'Salamura asma yaprağı', amount: '400 g' },
      { name: 'Baldo pirinç', amount: '2 su bardağı' },
      { name: 'Soğan', amount: '2 adet' },
      { name: 'Zeytinyağı', amount: '1 su bardağı' },
      { name: 'Kuş üzümü', amount: '2 yemek kaşığı' },
      { name: 'Çam fıstığı', amount: '2 yemek kaşığı' },
      { name: 'Nane (kuru)', amount: '1 tatlı kaşığı' },
      { name: 'Dereotu, maydanoz', amount: 'yarım demet' },
      { name: 'Limon', amount: '1 adet' },
      { name: 'Tuz, karabiber, yenibahar', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '2 su bardağı' },
    ],
    steps: [
      'Yaprakları sıcak suda 5 dk bekletip durulayın; sert sapları kesin.',
      'Harç için: yağda ince soğanı kavurun, çam fıstığını ekleyin; pirinci ilave edin.',
      'Baharatlar, kuş üzümü, yeşillikler ve 1 su bardağı suyu ekleyip pirinç yarı pişene dek pişirin.',
      'Yaprağın mat yüzü üste gelecek şekilde tezgâha yayın; sapa 1 tatlı kaşığı harç koyun.',
      'Kenarları katlayarak sıkıca sarın.',
      'Tencerenin dibine yıpranmış yaprak serin; sarmaları sıkı sıkı dizin.',
      'Üzerine limon dilimleri, zeytinyağı ve sıcak su ekleyip tabak baskısı koyun.',
      'Kısık ateşte 40-45 dakika pişirin; soğuk servis edin.',
    ],
    nutritionPerServing: { kcal: 360, proteinG: 6, carbsG: 45, fatG: 17 },
  },
  {
    id: 'patlican-musakka',
    nameTr: 'Musakka',
    nameEn: 'Eggplant Moussaka',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 35,
    difficulty: 'medium',
    tags: ['traditional'],
    ingredients: [
      { name: 'Patlıcan', amount: '3 adet' },
      { name: 'Dana kıyma', amount: '250 g' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Domates', amount: '2 adet' },
      { name: 'Biber', amount: '2 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Sıvı yağ', amount: 'yarım su bardağı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '1 su bardağı' },
    ],
    steps: [
      'Patlıcanları soyup parmak kalınlığında kesin; tuzda 10 dk bekletip kurulayın.',
      'Az yağda kızartın (veya fırında 200°C\'de 20 dk).',
      'Tencerede kıymayı kavurun; soğan ve sarımsağı ekleyin.',
      'Doğranmış biber, domates ve salçayı ekleyip 5 dakika pişirin.',
      'Patlıcanları ekleyip karıştırın; sıcak suyu, baharatları ilave edin.',
      '10-15 dakika daha pişirin; pilav ile servis edin.',
    ],
    nutritionPerServing: { kcal: 380, proteinG: 16, carbsG: 20, fatG: 28 },
  },
  {
    id: 'firin-sebzeli',
    nameTr: 'Fırında Sebzeli',
    nameEn: 'Roasted Vegetables',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 45,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'healthy', 'oven', 'student_friendly'],
    ingredients: [
      { name: 'Patates', amount: '3 adet' },
      { name: 'Havuç', amount: '2 adet' },
      { name: 'Kabak', amount: '2 adet' },
      { name: 'Kapya biber', amount: '2 adet' },
      { name: 'Patlıcan', amount: '1 adet' },
      { name: 'Kırmızı soğan', amount: '1 adet' },
      { name: 'Sarımsak', amount: '4 diş' },
      { name: 'Zeytinyağı', amount: '4 yemek kaşığı' },
      { name: 'Kekik, biberiye', amount: '1 tatlı kaşığı' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Tüm sebzeleri benzer boyda iri parçalara doğrayın.',
      'Tepsiye alıp yağ, ezilmiş sarımsak, baharatlar ile iyice karıştırın.',
      '200°C fırında 40-45 dakika, ortasında karıştırarak pişirin.',
      'Üzerine taze maydanoz veya balzamik sos ile servis edin.',
    ],
    nutritionPerServing: { kcal: 260, proteinG: 5, carbsG: 32, fatG: 13 },
  },
  {
    id: 'semizotu-salatasi-yemegi',
    nameTr: 'Yoğurtlu Semizotu',
    nameEn: 'Purslane with Yogurt',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 0,
    difficulty: 'easy',
    tags: ['vegetarian', 'quick', 'raw'],
    ingredients: [
      { name: 'Semizotu', amount: '1 demet' },
      { name: 'Yoğurt', amount: '2 su bardağı' },
      { name: 'Sarımsak', amount: '2 diş' },
      { name: 'Zeytinyağı', amount: '2 yemek kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
    ],
    steps: [
      'Semizotunun yapraklarını yıkayıp doğrayın.',
      'Yoğurt, ezilmiş sarımsak ve tuzu karıştırın.',
      'Semizotunu yoğurtla karıştırın; üstüne zeytinyağı gezdirin.',
      'Soğuk servis edin.',
    ],
    nutritionPerServing: { kcal: 160, proteinG: 6, carbsG: 8, fatG: 11 },
  },
  {
    id: 'kiymali-patates',
    nameTr: 'Kıymalı Patates Yemeği',
    nameEn: 'Potato & Ground Beef Stew',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    difficulty: 'easy',
    tags: ['comfort', 'budget', 'student_friendly'],
    ingredients: [
      { name: 'Patates', amount: '4 adet', grams: 600 },
      { name: 'Dana kıyma', amount: '250 g' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Sivri biber', amount: '2 adet' },
      { name: 'Domates', amount: '2 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Sıvı yağ', amount: '3 yemek kaşığı' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '2 su bardağı' },
    ],
    steps: [
      'Yağda kıymayı suyunu çekene dek kavurun.',
      'Doğranmış soğan ve biberleri ekleyin; yumuşatın.',
      'Salça ve küp domatesi ekleyip 2 dakika çevirin.',
      'Küp patatesleri, sıcak suyu ve baharatları ilave edin.',
      'Kapağı kapalı 20-25 dakika pişirin.',
    ],
    nutritionPerServing: { kcal: 340, proteinG: 16, carbsG: 35, fatG: 15 },
  },
  {
    id: 'zeytinyagli-pirasa',
    nameTr: 'Zeytinyağlı Pırasa',
    nameEn: 'Leeks in Olive Oil',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 35,
    difficulty: 'easy',
    tags: ['vegetarian', 'vegan', 'olive_oil'],
    ingredients: [
      { name: 'Pırasa', amount: '4 adet', grams: 500 },
      { name: 'Havuç', amount: '1 adet' },
      { name: 'Pirinç', amount: '2 yemek kaşığı' },
      { name: 'Zeytinyağı', amount: '4 yemek kaşığı' },
      { name: 'Şeker', amount: '1 çay kaşığı' },
      { name: 'Limon suyu', amount: '2 yemek kaşığı' },
      { name: 'Tuz', amount: '1 çay kaşığı' },
      { name: 'Sıcak su', amount: '1,5 su bardağı' },
    ],
    steps: [
      'Pırasaları 2 cm dilimleyip iyice yıkayın.',
      'Havucu yarım ay şeklinde doğrayın.',
      'Tencerede zeytinyağını ısıtıp havuç ve pırasayı 3-4 dakika çevirin.',
      'Pirinç, şeker, tuz, limon suyu ve sıcak suyu ekleyin.',
      'Kapak kapalı kısık ateşte 25-30 dakika pişirin.',
      'Soğuk servis edin.',
    ],
    nutritionPerServing: { kcal: 210, proteinG: 4, carbsG: 24, fatG: 12 },
  },
  {
    id: 'kabak-dolmasi',
    nameTr: 'Kabak Dolması',
    nameEn: 'Stuffed Zucchini',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 25,
    cookMinutes: 50,
    difficulty: 'medium',
    tags: ['traditional'],
    ingredients: [
      { name: 'Sakız kabağı (büyük)', amount: '6 adet' },
      { name: 'Dana kıyma', amount: '250 g' },
      { name: 'Pirinç', amount: 'yarım su bardağı' },
      { name: 'Soğan', amount: '1 adet' },
      { name: 'Domates', amount: '1 adet' },
      { name: 'Domates salçası', amount: '1 yemek kaşığı' },
      { name: 'Nane, maydanoz', amount: 'yarım demet' },
      { name: 'Tuz, karabiber', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '2 su bardağı' },
    ],
    steps: [
      'Kabakları dilim dilim olmayacak şekilde kazıyıp oyun, içi boşaltın.',
      'Harç: rende soğan, kıyma, pirinç, rende domates, salça, yeşillikler, baharatlar karıştırın.',
      'Kabakların içini harçla doldurun.',
      'Tencerede dik dizip sıcak suyu ekleyin; tuz atın.',
      '45-50 dakika kapağı kapalı kısık ateşte pişirin.',
      'Sarımsaklı yoğurt ile servis edin.',
    ],
    nutritionPerServing: { kcal: 320, proteinG: 16, carbsG: 30, fatG: 14 },
  },
  {
    id: 'mantar-sote',
    nameTr: 'Tereyağında Mantar Sote',
    nameEn: 'Buttery Mushroom Sauté',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 3,
    prepMinutes: 5,
    cookMinutes: 15,
    difficulty: 'easy',
    tags: ['vegetarian', 'quick', 'student_friendly'],
    ingredients: [
      { name: 'Kültür mantarı', amount: '400 g' },
      { name: 'Tereyağı', amount: '3 yemek kaşığı' },
      { name: 'Sarımsak', amount: '3 diş' },
      { name: 'Taze kekik', amount: '1 dal' },
      { name: 'Maydanoz', amount: '2 dal' },
      { name: 'Tuz, karabiber, pul biber', amount: 'tatmınıza göre' },
    ],
    steps: [
      'Mantarları temizleyip dörde bölün.',
      'Tavada tereyağını köpürtün; ezilmiş sarımsakları ekleyin.',
      'Mantarları yüksek ateşte 5-7 dakika, suyunu çekirip hafif kızarana dek çevirin.',
      'Kekik, maydanoz ve baharatları ekleyin; 1 dakika daha pişirin.',
      'Ekmek üzerinde veya yanında pilav ile servis edin.',
    ],
    nutritionPerServing: { kcal: 200, proteinG: 6, carbsG: 6, fatG: 16 },
  },
  {
    id: 'pazı-sarma',
    nameTr: 'Pazı Sarma',
    nameEn: 'Stuffed Chard Leaves',
    category: 'main_veg',
    cuisine: 'turkish',
    servings: 4,
    prepMinutes: 30,
    cookMinutes: 45,
    difficulty: 'medium',
    tags: ['vegetarian', 'traditional'],
    ingredients: [
      { name: 'Pazı', amount: '1 demet' },
      { name: 'Baldo pirinç', amount: '1 su bardağı' },
      { name: 'Soğan', amount: '2 adet' },
      { name: 'Domates salçası', amount: '1 tatlı kaşığı' },
      { name: 'Zeytinyağı', amount: 'yarım su bardağı' },
      { name: 'Nane, dereotu', amount: 'yarım demet' },
      { name: 'Limon', amount: '1 adet' },
      { name: 'Tuz, karabiber, nane', amount: 'tatmınıza göre' },
      { name: 'Sıcak su', amount: '1,5 su bardağı' },
    ],
    steps: [
      'Pazı yapraklarını yıkayıp kaynayan suda 1-2 dakika diri diri haşlayın; soğuk suya alın.',
      'Yağda ince doğranmış soğanı kavurun; pirinci ilave edin.',
      'Salça, yeşillikler, baharatlar ve yarım bardak suyla harcı pişirin (pirinç yarı pişsin).',
      'Pazıların sapını kesin; 1 tatlı kaşığı harcı koyup sıkıca sarın.',
      'Tencerenin dibine yaprak serin; sarmaları dizin.',
      'Limon dilimleri, zeytinyağı ve sıcak suyu ekleyin; tabak baskısı koyun.',
      '35-40 dakika kısık ateşte pişirin; soğuk servis edin.',
    ],
    nutritionPerServing: { kcal: 300, proteinG: 6, carbsG: 36, fatG: 15 },
  },
];
