import type { ExerciseSeedInput } from '@fittrack/shared';

// Futbola özel egzersiz kütüphanesi (alt lig + akademi odaklı).
// Engine bu havuzdan kategori, ekipman, mevki ve yaşa göre filtreleyerek seçer.
// Yeni egzersiz eklerken: slug benzersiz olmalı, requiredEquipment AND mantığında.

export const FOOTBALL_EXERCISES: ExerciseSeedInput[] = [
  // --- WARMUP ---
  {
    slug: 'wu-dynamic-mobility',
    nameTr: 'Dinamik Mobilite Rutini',
    nameEn: 'Dynamic Mobility Routine',
    category: 'warmup',
    description: 'Kalça açıcı, lunge with twist, leg swing kombinasyonu — antrenman öncesi 8 dk.',
    primaryMuscles: ['hip', 'glute', 'hamstring'],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultDurationSeconds: 480,
  },
  {
    slug: 'wu-fifa-11-plus',
    nameTr: 'FIFA 11+ Isınma',
    nameEn: 'FIFA 11+ Warmup',
    category: 'warmup',
    description: 'Sakatlık önleyici, koşu + güç + denge bloğu, 15-20 dk.',
    primaryMuscles: ['full_body'],
    positionsTargeted: [],
    minAge: 12,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 2,
    defaultDurationSeconds: 1200,
  },
  {
    slug: 'wu-jog-progressive',
    nameTr: 'Tempo Artıran Koşu',
    nameEn: 'Progressive Jog',
    category: 'warmup',
    description: 'Yavaş başlayıp tempoyu artıran 6-8 dk koşu.',
    primaryMuscles: ['cardio'],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultDurationSeconds: 480,
  },

  // --- ENDURANCE ---
  {
    slug: 'end-interval-4x4',
    nameTr: 'Norveç 4x4 Aralıklı Koşu',
    nameEn: '4x4 Interval Run',
    category: 'endurance',
    description: '4 dk yüksek tempo + 3 dk aktif dinlenme x 4 set. VO2max odaklı.',
    primaryMuscles: ['cardio', 'quadriceps', 'calf'],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field'],
    difficulty: 4,
    defaultSets: 4,
    defaultDurationSeconds: 240,
    defaultRestSeconds: 180,
  },
  {
    slug: 'end-fartlek-30min',
    nameTr: 'Fartlek 30 dk',
    nameEn: 'Fartlek 30min',
    category: 'endurance',
    description: 'Değişken tempolu 30 dk koşu. Saha kenarındaki ağaç/koniler tempo işareti.',
    primaryMuscles: ['cardio'],
    positionsTargeted: [],
    minAge: 13,
    requiredEquipment: [],
    locations: ['field', 'bodyweight_anywhere'],
    difficulty: 3,
    defaultDurationSeconds: 1800,
  },
  {
    slug: 'end-tempo-run-20min',
    nameTr: 'Sürekli Tempo Koşusu 20 dk',
    nameEn: 'Tempo Run 20min',
    category: 'endurance',
    description: 'Eşik altı sabit tempo, konuşamayacak kadar zor değil.',
    primaryMuscles: ['cardio'],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field'],
    difficulty: 3,
    defaultDurationSeconds: 1200,
  },
  {
    slug: 'end-shuttle-bleep',
    nameTr: 'Mekik Koşusu (20m)',
    nameEn: '20m Shuttle Run',
    category: 'endurance',
    description: '20m mesafe arası gidip gelme, tempo artımlı.',
    primaryMuscles: ['cardio', 'quadriceps'],
    positionsTargeted: [],
    minAge: 12,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultDurationSeconds: 600,
    defaultDistanceMeters: 20,
  },

  // --- SPRINT & AGILITY ---
  {
    slug: 'sa-sprint-30m',
    nameTr: '30m Sprint',
    nameEn: '30m Sprint',
    category: 'sprint_agility',
    description: 'Maksimal hızda 30m sprint, tam dinlenme.',
    primaryMuscles: ['hamstring', 'glute', 'calf'],
    positionsTargeted: [],
    minAge: 13,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 6,
    defaultDistanceMeters: 30,
    defaultRestSeconds: 90,
  },
  {
    slug: 'sa-sprint-10m',
    nameTr: '10m Patlayıcı Sprint',
    nameEn: '10m Acceleration',
    category: 'sprint_agility',
    description: 'İlk 10 metrede ivme — top kapma anına özgü.',
    primaryMuscles: ['glute', 'quadriceps'],
    positionsTargeted: [],
    minAge: 12,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 2,
    defaultSets: 8,
    defaultDistanceMeters: 10,
    defaultRestSeconds: 45,
  },
  {
    slug: 'sa-shuttle-505',
    nameTr: '5-0-5 Yön Değiştirme',
    nameEn: '5-0-5 Agility',
    category: 'sprint_agility',
    description: '5m sprint + 180° dönüş + 5m sprint. Yön değiştirme kabiliyeti.',
    primaryMuscles: ['quadriceps', 'calf', 'core'],
    positionsTargeted: [],
    minAge: 12,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 6,
    defaultRestSeconds: 60,
  },
  {
    slug: 'sa-ladder-quickfeet',
    nameTr: 'Çeviklik Merdiveni Ayak Hızı',
    nameEn: 'Agility Ladder Quick Feet',
    category: 'sprint_agility',
    description: 'Merdiven üstünde hızlı ayak desenleri (in-in-out-out, lateral).',
    primaryMuscles: ['calf', 'hip'],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['agility_ladder'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 2,
    defaultSets: 5,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 30,
  },
  {
    slug: 'sa-t-test',
    nameTr: 'T-Test Çevikliği',
    nameEn: 'T-Test Agility',
    category: 'sprint_agility',
    description: 'T şeklinde 4 koni etrafında çoklu yön değiştirme.',
    primaryMuscles: ['quadriceps', 'core'],
    positionsTargeted: [],
    minAge: 13,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 4,
    defaultRestSeconds: 90,
  },
  {
    slug: 'sa-hill-sprint',
    nameTr: 'Yokuş Sprintleri',
    nameEn: 'Hill Sprints',
    category: 'sprint_agility',
    description: '15-20m eğimde maksimal sprint. Patlayıcı güç + sakatlık riski düşük.',
    primaryMuscles: ['glute', 'hamstring', 'calf'],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere'],
    difficulty: 4,
    defaultSets: 8,
    defaultDistanceMeters: 20,
    defaultRestSeconds: 90,
  },

  // --- STRENGTH (gym) ---
  {
    slug: 'st-back-squat',
    nameTr: 'Arka Squat (Halter)',
    nameEn: 'Back Squat',
    category: 'strength',
    description: 'Bacak gücü temeli. 5x5 veya 3x8.',
    primaryMuscles: ['quadriceps', 'glute', 'core'],
    positionsTargeted: [],
    minAge: 15,
    requiredEquipment: ['barbell', 'squat_rack'],
    locations: ['gym'],
    difficulty: 4,
    defaultSets: 5,
    defaultReps: 5,
    defaultRestSeconds: 180,
  },
  {
    slug: 'st-romanian-deadlift',
    nameTr: 'Romen Deadlift',
    nameEn: 'Romanian Deadlift',
    category: 'strength',
    description: 'Hamstring ve glute zinciri — sprint gücü için kritik.',
    primaryMuscles: ['hamstring', 'glute', 'lower_back'],
    positionsTargeted: [],
    minAge: 15,
    requiredEquipment: ['barbell'],
    locations: ['gym'],
    difficulty: 4,
    defaultSets: 4,
    defaultReps: 6,
    defaultRestSeconds: 150,
  },
  {
    slug: 'st-bench-press',
    nameTr: 'Bench Press',
    nameEn: 'Bench Press',
    category: 'strength',
    description: 'Üst gövde itiş, hava topu mücadelesi için faydalı.',
    primaryMuscles: ['chest', 'triceps', 'shoulder'],
    positionsTargeted: [],
    minAge: 15,
    requiredEquipment: ['barbell', 'bench'],
    locations: ['gym'],
    difficulty: 3,
    defaultSets: 4,
    defaultReps: 8,
    defaultRestSeconds: 120,
  },
  {
    slug: 'st-bulgarian-split-squat',
    nameTr: 'Bulgar Split Squat (DB)',
    nameEn: 'Bulgarian Split Squat (DB)',
    category: 'strength',
    description: 'Tek bacak güç + denge. Asimetrik yük telafisi.',
    primaryMuscles: ['quadriceps', 'glute'],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['dumbbell', 'bench'],
    locations: ['gym'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 90,
  },
  {
    slug: 'st-pull-up',
    nameTr: 'Barfiks (Pull-Up)',
    nameEn: 'Pull-Up',
    category: 'strength',
    description: 'Sırt ve kavrama gücü.',
    primaryMuscles: ['back', 'biceps'],
    positionsTargeted: [],
    minAge: 13,
    requiredEquipment: ['pull_up_bar'],
    locations: ['gym', 'home', 'bodyweight_anywhere'],
    difficulty: 3,
    defaultSets: 4,
    defaultReps: 6,
    defaultRestSeconds: 120,
  },

  // --- STRENGTH (bodyweight - tesis fakir kulüpler için) ---
  {
    slug: 'stb-bodyweight-squat',
    nameTr: 'Vücut Ağırlığı Squat',
    nameEn: 'Bodyweight Squat',
    category: 'strength',
    description: 'Yüksek tekrarla bacak dayanıklılığı. Genç oyuncular için ideal.',
    primaryMuscles: ['quadriceps', 'glute'],
    positionsTargeted: [],
    minAge: 8,
    requiredEquipment: [],
    locations: ['field', 'home', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultSets: 3,
    defaultReps: 20,
    defaultRestSeconds: 60,
  },
  {
    slug: 'stb-pushup',
    nameTr: 'Şınav',
    nameEn: 'Push-Up',
    category: 'strength',
    description: 'Üst gövde itiş — temel.',
    primaryMuscles: ['chest', 'triceps', 'core'],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'field'],
    difficulty: 1,
    defaultSets: 4,
    defaultReps: 15,
    defaultRestSeconds: 60,
  },
  {
    slug: 'stb-glute-bridge',
    nameTr: 'Glute Bridge',
    nameEn: 'Glute Bridge',
    category: 'strength',
    description: 'Kalça ekstansiyonu + posterior chain aktivasyonu.',
    primaryMuscles: ['glute', 'hamstring'],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'field'],
    difficulty: 1,
    defaultSets: 3,
    defaultReps: 15,
    defaultRestSeconds: 45,
  },
  {
    slug: 'stb-nordic-hamstring',
    nameTr: 'Nordic Hamstring Curl',
    nameEn: 'Nordic Hamstring Curl',
    category: 'strength',
    description: 'Hamstring eksantrik gücü — sakatlık önleyici altın standart.',
    primaryMuscles: ['hamstring'],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'gym', 'home'],
    difficulty: 4,
    defaultSets: 3,
    defaultReps: 6,
    defaultRestSeconds: 90,
  },
  {
    slug: 'stb-copenhagen-adductor',
    nameTr: 'Copenhagen Adductor',
    nameEn: 'Copenhagen Adductor',
    category: 'strength',
    description: 'Kasık koruyucu — adductor kuvveti.',
    primaryMuscles: ['adductor', 'core'],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['bench'],
    locations: ['gym', 'field', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 8,
    defaultRestSeconds: 60,
  },
  {
    slug: 'stb-plank',
    nameTr: 'Plank',
    nameEn: 'Plank',
    category: 'strength',
    description: 'Core stabilizasyonu, izometrik.',
    primaryMuscles: ['core'],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'field'],
    difficulty: 1,
    defaultSets: 3,
    defaultDurationSeconds: 45,
    defaultRestSeconds: 45,
  },

  // --- PLYOMETRIC ---
  {
    slug: 'pl-box-jump',
    nameTr: 'Kasaya Sıçrama',
    nameEn: 'Box Jump',
    category: 'plyometric',
    description: 'Patlayıcı dikey sıçrama. 40-60cm kutu.',
    primaryMuscles: ['quadriceps', 'glute', 'calf'],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['plyo_box'],
    locations: ['gym', 'field'],
    difficulty: 3,
    defaultSets: 4,
    defaultReps: 6,
    defaultRestSeconds: 90,
  },
  {
    slug: 'pl-broad-jump',
    nameTr: 'Uzun Atlama (Yerinden)',
    nameEn: 'Broad Jump',
    category: 'plyometric',
    description: 'Yatay patlayıcı güç — ilk adım.',
    primaryMuscles: ['glute', 'quadriceps'],
    positionsTargeted: [],
    minAge: 12,
    requiredEquipment: [],
    locations: ['field', 'bodyweight_anywhere'],
    difficulty: 2,
    defaultSets: 4,
    defaultReps: 5,
    defaultRestSeconds: 90,
  },
  {
    slug: 'pl-bounding',
    nameTr: 'Sıçrayarak Koşu (Bounding)',
    nameEn: 'Bounding',
    category: 'plyometric',
    description: 'Geniş adımlarla sıçrayarak ilerleme.',
    primaryMuscles: ['glute', 'hamstring', 'calf'],
    positionsTargeted: [],
    minAge: 13,
    requiredEquipment: [],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 4,
    defaultDistanceMeters: 30,
    defaultRestSeconds: 90,
  },
  {
    slug: 'pl-hurdle-hop',
    nameTr: 'Engel Üstü Sıçrama',
    nameEn: 'Hurdle Hops',
    category: 'plyometric',
    description: 'Düşük engellerin üstünden ardışık sıçrama.',
    primaryMuscles: ['calf', 'quadriceps'],
    positionsTargeted: [],
    minAge: 13,
    requiredEquipment: ['hurdles'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 4,
    defaultReps: 8,
    defaultRestSeconds: 60,
  },

  // --- TECHNICAL ---
  {
    slug: 'tc-passing-square',
    nameTr: 'Pas Karesi (4 Köşe)',
    nameEn: '4-Corner Passing Square',
    category: 'technical',
    description: '4 oyuncu kare köşelerinde, 1-2 dokunuş ile sürekli pas.',
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 2,
    defaultDurationSeconds: 600,
  },
  {
    slug: 'tc-rondo-5v2',
    nameTr: 'Rondo 5v2',
    nameEn: 'Rondo 5v2',
    category: 'technical',
    description: '5 oyuncu pas dolaştırır, 2 oyuncu top kapmaya çalışır. Klasik.',
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 2,
    defaultSets: 3,
    defaultDurationSeconds: 240,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tc-shooting-1v1-keeper',
    nameTr: '1v1 Kaleciye Şut',
    nameEn: 'Shooting 1v1 Keeper',
    category: 'technical',
    description: 'Sırayla sürerek kalecinin önüne gelip şut.',
    primaryMuscles: [],
    positionsTargeted: ['forward', 'midfielder'],
    minAge: 12,
    requiredEquipment: ['goal'],
    locations: ['field'],
    difficulty: 2,
    defaultSets: 4,
    defaultReps: 8,
    defaultRestSeconds: 30,
  },
  {
    slug: 'tc-dribbling-cones',
    nameTr: 'Konilerde Dribling',
    nameEn: 'Cone Dribbling',
    category: 'technical',
    description: 'Sıralı koniler arasında her iki ayakla top sürme.',
    primaryMuscles: [],
    positionsTargeted: ['midfielder', 'forward'],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 2,
    defaultSets: 5,
    defaultDistanceMeters: 20,
    defaultRestSeconds: 30,
  },
  {
    slug: 'tc-juggling',
    nameTr: 'Top Kontrolü (Juggling)',
    nameEn: 'Juggling',
    category: 'technical',
    description: 'Bireysel top kontrolü — ayak/diz/baş.',
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 8,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultDurationSeconds: 600,
  },
  {
    slug: 'tc-long-pass-accuracy',
    nameTr: 'Uzun Pas İsabet',
    nameEn: 'Long Pass Accuracy',
    category: 'technical',
    description: '30-40m hedefe uzun pas — orta saha ve defans için.',
    primaryMuscles: [],
    positionsTargeted: ['defender', 'midfielder', 'goalkeeper'],
    minAge: 13,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 5,
    defaultReps: 10,
    defaultRestSeconds: 30,
  },
  {
    slug: 'tc-first-touch-wall',
    nameTr: 'İlk Dokunuş (Duvar Pası)',
    nameEn: 'First Touch (Wall Pass)',
    category: 'technical',
    description: 'Duvardan gelen topu kontrol + geri pas.',
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 8,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultDurationSeconds: 600,
  },

  // --- TACTICAL ---
  {
    slug: 'ta-positional-rondo',
    nameTr: 'Pozisyonel Rondo (4-3-2)',
    nameEn: 'Positional Rondo',
    category: 'tactical',
    description: 'Mevkiye uygun pozisyonlarda pas — yapısal düşünce.',
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 13,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 3,
    defaultDurationSeconds: 480,
    defaultRestSeconds: 90,
  },
  {
    slug: 'ta-pressing-trigger',
    nameTr: 'Pressing Tetikleyicisi Drill',
    nameEn: 'Pressing Trigger Drill',
    category: 'tactical',
    description: 'Belirli bir pas geldiğinde takım baskıya çıkar — kolektif baskı.',
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones', 'mannequin'],
    locations: ['field'],
    difficulty: 4,
    defaultDurationSeconds: 900,
  },
  {
    slug: 'ta-defensive-line-drill',
    nameTr: 'Defans Hattı Çalışması',
    nameEn: 'Defensive Line Drill',
    category: 'tactical',
    description: 'Defans hattının senkron çıkma/inme + ofsayt pratiği.',
    primaryMuscles: [],
    positionsTargeted: ['defender'],
    minAge: 13,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 3,
    defaultDurationSeconds: 600,
  },

  // --- GOALKEEPER SPECIFIC ---
  {
    slug: 'gk-diving-low',
    nameTr: 'Kaleci Düşük Plonjon',
    nameEn: 'Goalkeeper Low Diving',
    category: 'goalkeeper_specific',
    description: 'Yere yakın gelen toplara plonjon tekniği.',
    primaryMuscles: ['core', 'shoulder'],
    positionsTargeted: ['goalkeeper'],
    minAge: 12,
    requiredEquipment: ['goal'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 4,
    defaultReps: 8,
    defaultRestSeconds: 45,
  },
  {
    slug: 'gk-distribution-throw-roll',
    nameTr: 'Kaleci Dağıtım (Atma + Yuvarlama)',
    nameEn: 'Goalkeeper Distribution',
    category: 'goalkeeper_specific',
    description: 'Hedef konilere atma + yuvarlayarak dağıtım.',
    primaryMuscles: ['shoulder', 'core'],
    positionsTargeted: ['goalkeeper'],
    minAge: 12,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 2,
    defaultSets: 4,
    defaultReps: 10,
    defaultRestSeconds: 30,
  },
  {
    slug: 'gk-footwork-ladder',
    nameTr: 'Kaleci Ayak Hızı (Merdiven)',
    nameEn: 'Goalkeeper Footwork',
    category: 'goalkeeper_specific',
    description: 'Çeviklik merdiveni ile yan adım + öne plonjon.',
    primaryMuscles: ['calf', 'core'],
    positionsTargeted: ['goalkeeper'],
    minAge: 12,
    requiredEquipment: ['agility_ladder'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 5,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 45,
  },
  {
    slug: 'gk-1v1-positioning',
    nameTr: 'Kaleci 1v1 Pozisyon Alma',
    nameEn: 'Goalkeeper 1v1 Positioning',
    category: 'goalkeeper_specific',
    description: 'Forvetin çıkışında pozisyon kapatma + kapanma.',
    primaryMuscles: [],
    positionsTargeted: ['goalkeeper'],
    minAge: 13,
    requiredEquipment: ['goal'],
    locations: ['field'],
    difficulty: 4,
    defaultSets: 5,
    defaultReps: 6,
    defaultRestSeconds: 60,
  },

  // --- SMALL SIDED GAMES ---
  {
    slug: 'ssg-3v3',
    nameTr: '3v3 Mini Maç',
    nameEn: '3v3 Small-Sided Game',
    category: 'small_sided_game',
    description: 'Yoğun temas + sürekli kontrol değişimi. 20x15m alan.',
    primaryMuscles: ['cardio'],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones', 'goal'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 4,
    defaultDurationSeconds: 240,
    defaultRestSeconds: 120,
  },
  {
    slug: 'ssg-5v5-possession',
    nameTr: '5v5 Topa Sahip Olma',
    nameEn: '5v5 Possession',
    category: 'small_sided_game',
    description: 'Skor yok, sadece pas korunumu — 8 pas = 1 puan.',
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 11,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 3,
    defaultDurationSeconds: 900,
  },
  {
    slug: 'ssg-7v7-tactical',
    nameTr: '7v7 Taktiksel Maç',
    nameEn: '7v7 Tactical Match',
    category: 'small_sided_game',
    description: 'Yarı saha, pozisyonel oyun + skor.',
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 13,
    requiredEquipment: ['goal', 'cones'],
    locations: ['field'],
    difficulty: 3,
    defaultDurationSeconds: 1800,
  },

  // --- SET PIECE ---
  {
    slug: 'sp-corner-attack',
    nameTr: 'Korner Atağı (Hücum)',
    nameEn: 'Corner Attack',
    category: 'set_piece',
    description: 'Belirlenen koşu desenleri ile korner sonrası şut.',
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 12,
    requiredEquipment: ['goal'],
    locations: ['field'],
    difficulty: 2,
    defaultDurationSeconds: 900,
  },
  {
    slug: 'sp-free-kick-shooting',
    nameTr: 'Serbest Vuruş Çalışması',
    nameEn: 'Free Kick Shooting',
    category: 'set_piece',
    description: 'Bariyer önünde 18-25m mesafelerden serbest vuruş.',
    primaryMuscles: [],
    positionsTargeted: ['midfielder', 'forward'],
    minAge: 13,
    requiredEquipment: ['goal', 'mannequin'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 4,
    defaultReps: 6,
    defaultRestSeconds: 30,
  },

  // --- RECOVERY ---
  {
    slug: 'rc-light-jog',
    nameTr: 'Hafif Tempolu Toparlanma Koşusu',
    nameEn: 'Light Recovery Jog',
    category: 'recovery',
    description: 'Konuşulabilen tempoda 20 dk koşu — laktatı temizler.',
    primaryMuscles: ['cardio'],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultDurationSeconds: 1200,
  },
  {
    slug: 'rc-foam-roll',
    nameTr: 'Foam Roller Çalışması',
    nameEn: 'Foam Rolling',
    category: 'recovery',
    description: 'Quadriceps, IT band, hamstring, sırt — 60sn/bölge.',
    primaryMuscles: ['quadriceps', 'hamstring', 'back'],
    positionsTargeted: [],
    minAge: 12,
    requiredEquipment: [],
    locations: ['gym', 'home'],
    difficulty: 1,
    defaultDurationSeconds: 600,
  },
  {
    slug: 'rc-pool-recovery',
    nameTr: 'Havuzda Toparlanma',
    nameEn: 'Pool Recovery',
    category: 'recovery',
    description: 'Hafif yüzme + dinamik su yürüyüşü, 20 dk.',
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 12,
    requiredEquipment: [],
    locations: ['pool'],
    difficulty: 1,
    defaultDurationSeconds: 1200,
  },

  // --- COOLDOWN ---
  {
    slug: 'cd-static-stretch',
    nameTr: 'Statik Esneme Rutini',
    nameEn: 'Static Stretch Routine',
    category: 'cooldown',
    description: 'Antrenman sonrası 8-10 dk statik esneme — büyük kas grupları.',
    primaryMuscles: ['hamstring', 'quadriceps', 'calf', 'hip'],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultDurationSeconds: 600,
  },
  {
    slug: 'cd-breathing-down-regulation',
    nameTr: 'Nefes Çalışması (Down-Regulation)',
    nameEn: 'Breathing Down-Regulation',
    category: 'cooldown',
    description: '4-7-8 nefes paterni, 5 dk — parasempatik aktivasyon.',
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home'],
    difficulty: 1,
    defaultDurationSeconds: 300,
  },
  // --- PHYSICAL (FIFA 11+ + strength + plyometric + balance) (football-db merge) ---
  {
    slug: 'fifa11p-1-running-straight',
    nameTr: "Düz Koşu",
    nameEn: "Running Straight Ahead",
    category: 'warmup',
    description: "Genel ısınma — Sahada paralel iki sıra oluşturulur, her sıra arasında ~6m mesafe. İpucu: Diz yumuşak, gövde dik",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 2,
    defaultRestSeconds: 30,
  },
  {
    slug: 'fifa11p-2-running-hip-out',
    nameTr: "Kalça Dışa Açma Koşusu",
    nameEn: "Running Hip Out",
    category: 'warmup',
    description: "Kalça mobilitesi — Düz koşu yolunda yürüyerek/kontrollü koşarak ilerleyin. İpucu: Üst beden sabit",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 2,
    defaultRestSeconds: 30,
  },
  {
    slug: 'fifa11p-3-running-hip-in',
    nameTr: "Kalça İçe Çekme Koşusu",
    nameEn: "Running Hip In",
    category: 'warmup',
    description: "Kalça iç rotasyon mobilitesi — Konilerde dizi yana açıp gövdenin önünden içe çekin. İpucu: Sırt dik",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 2,
    defaultRestSeconds: 30,
  },
  {
    slug: 'fifa11p-4-circling-partner',
    nameTr: "Partner Etrafında Dönme",
    nameEn: "Running Circling Partner",
    category: 'warmup',
    description: "Yön değiştirme — Çiftler birlikte koşar, ortadaki konide bir oyuncu durur, diğeri etrafında tam tur atar. İpucu: Düşük çıkış pozisyonu",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 2,
    defaultRestSeconds: 30,
  },
  {
    slug: 'fifa11p-5-shoulder-contact',
    nameTr: "Omuz Teması",
    nameEn: "Running Shoulder Contact",
    category: 'warmup',
    description: "İkili mücadele dengesi — Çiftler kontrollü koşar; her konide birlikte sıçrayıp havada omuz teması kurar. İpucu: İniş tek bacakta değil",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 2,
    defaultRestSeconds: 30,
  },
  {
    slug: 'fifa11p-6-quick-fwd-back',
    nameTr: "Hızlı İleri-Geri",
    nameEn: "Running Quick Forwards and Backwards",
    category: 'warmup',
    description: "Akselerasyon-deselerasyon — İki konige hızlı sprint, sonra iki kıçça geri koşu. İpucu: Geri koşuda gövde öne",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 2,
    defaultRestSeconds: 30,
  },
  {
    slug: 'fifa11p-7-bench-l1',
    nameTr: "Plank (Seviye 1)",
    nameEn: "The Bench (Level 1)",
    category: 'warmup',
    description: "Core stabilizasyonu — Dirsekler omuz altında, ayak parmakları yerde. İpucu: Bel çukuru çökmesin",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 3,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 30,
  },
  {
    slug: 'fifa11p-8-side-bench-l1',
    nameTr: "Yan Plank (Seviye 1)",
    nameEn: "Sideways Bench (Level 1)",
    category: 'warmup',
    description: "Yan core stabilizasyonu — Yan yatın, dirsek omuz altında, dizler bükük. İpucu: Kalça arkaya/öne kaymasın",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 3,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 30,
  },
  {
    slug: 'fifa11p-9-nordic-hamstring',
    nameTr: "Nordic Hamstring",
    nameEn: "Nordic Hamstrings",
    category: 'warmup',
    description: "Hamstring eksantrik kuvveti — Diz çökerek partner ayak bileklerinizi yere bastırır. İpucu: Kalça düz, fold yapmayın",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 1,
    defaultReps: 5,
    defaultRestSeconds: 60,
  },
  {
    slug: 'fifa11p-10-single-leg-stance',
    nameTr: "Tek Bacak Duruş",
    nameEn: "Single-Leg Stance",
    category: 'warmup',
    description: "Ayak bileği propriyosepsiyonu — Tek ayak üzerinde dururken partnerle topu pas alın-verin. İpucu: Diz hafif bükük",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 2,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 30,
  },
  {
    slug: 'fifa11p-11-squats-l1',
    nameTr: "Squat (Seviye 1)",
    nameEn: "Squats (Level 1)",
    category: 'warmup',
    description: "Alt vücut kuvveti — Ayaklar omuz genişliğinde, ayak parmakları hafif dışa. İpucu: Diz içe kaymasın",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 2,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 30,
  },
  {
    slug: 'fifa11p-12-jumping-l1',
    nameTr: "Sıçramalar (Seviye 1)",
    nameEn: "Jumping (Level 1)",
    category: 'warmup',
    description: "Plyometric güç — Dikey sıçrama: çift bacak çömelip patlayıcı yukarı sıçrayın. İpucu: İniş sessiz olsun",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 2,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 30,
  },
  {
    slug: 'fifa11p-13-running-across',
    nameTr: "Çapraz Saha Koşusu",
    nameEn: "Running Across the Pitch",
    category: 'warmup',
    description: "Tempolu koşu — Saha boyunca %75-80 tempoda koşun, dönüşte yürüyerek dinlenin. İpucu: Kollar omuzla aktif",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 2,
    defaultRestSeconds: 60,
  },
  {
    slug: 'fifa11p-14-bounding',
    nameTr: "Geyik Koşusu (Bounding)",
    nameEn: "Running Bounding",
    category: 'warmup',
    description: "Adım gücü — Yüksek diz çekişiyle uzun adımlar halinde sahayı geçin. İpucu: Havadaki süre maksimum",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 2,
    defaultRestSeconds: 60,
  },
  {
    slug: 'fifa11p-15-plant-cut',
    nameTr: "Yön Değiştirme (Plant & Cut)",
    nameEn: "Running Plant and Cut",
    category: 'warmup',
    description: "Yön değiştirme tekniği — 4-5 adım sprint sonrası dış ayağa basıp keskin yön değiştirin. İpucu: Diz ayak burnu üstünde",
    primaryMuscles: ["full_body"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 2,
    defaultRestSeconds: 60,
  },
  {
    slug: 'warmup-leg-swings',
    nameTr: "Bacak Salınımı",
    nameEn: "Leg Swings",
    category: 'warmup',
    description: "Kalça mobilitesi — Bir el desteğiyle tek bacağı düz öne-arkaya sallayın (10x). İpucu: Salınım kontrollü, fırlatma yok",
    primaryMuscles: ["hip","glute","hamstring"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultSets: 1,
    defaultReps: 10,
  },
  {
    slug: 'warmup-world-greatest-stretch',
    nameTr: "Dünyanın En İyi Esnemesi",
    nameEn: "World's Greatest Stretch",
    category: 'warmup',
    description: "Tam vücut dinamik mobilite — Hamle (lunge) pozisyonuna girin, ön ayağın iç kısmına aynı taraf eli yerleştirin. İpucu: Arka diz uzun",
    primaryMuscles: ["hip","glute","hamstring"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 3,
    defaultSets: 1,
    defaultReps: 5,
  },
  {
    slug: 'warmup-a-skip',
    nameTr: "A-Skip",
    nameEn: "A-Skip",
    category: 'warmup',
    description: "Koşu mekaniği — Yerde kısa bir hop, ardından diz 90° çekilir. İpucu: Topuklar kalçaya",
    primaryMuscles: ["hip","glute","hamstring"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultSets: 2,
    defaultDistanceMeters: 20,
    defaultRestSeconds: 30,
  },
  {
    slug: 'warmup-carioca',
    nameTr: "Karioka (Çapraz Adım)",
    nameEn: "Carioca",
    category: 'warmup',
    description: "Kalça mobilitesi — Yan ilerleyin, dış bacak iç bacağın önünden ve arkasından geçer. İpucu: Kalça rotasyonu büyük",
    primaryMuscles: ["hip","glute","hamstring"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultSets: 2,
    defaultDistanceMeters: 20,
  },
  {
    slug: 'strength-goblet-squat',
    nameTr: "Goblet Squat",
    nameEn: "Goblet Squat",
    category: 'strength',
    description: "Quadriceps/glute kuvveti — Sağlık topu/dumbell göğsünüzde tutun. İpucu: Topuk yerde",
    primaryMuscles: ["quadriceps","glute","hamstring"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['medicine_ball'],
    locations: ['field', 'gym', 'bodyweight_anywhere', 'home'],
    difficulty: 1,
    defaultSets: 4,
    defaultReps: 10,
    defaultRestSeconds: 90,
  },
  {
    slug: 'strength-rdl-single-leg',
    nameTr: "Tek Bacak Romen Deadlift",
    nameEn: "Single-Leg Romanian Deadlift",
    category: 'strength',
    description: "Hamstring/glute kuvveti — Tek bacak üstünde durun, kalçadan menteşe yapın. İpucu: Kalçalar yere paralel",
    primaryMuscles: ["quadriceps","glute","hamstring"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'gym', 'bodyweight_anywhere', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 8,
    defaultRestSeconds: 60,
  },
  {
    slug: 'strength-bulgarian-split-squat',
    nameTr: "Bulgar Split Squat",
    nameEn: "Bulgarian Split Squat",
    category: 'strength',
    description: "Tek bacak kuvveti — Arka ayağı banka koyun, ön bacakla derin lunge'a inin. İpucu: Gövde dik",
    primaryMuscles: ["quadriceps","glute","hamstring"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'gym', 'bodyweight_anywhere', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 60,
  },
  {
    slug: 'strength-band-pullapart',
    nameTr: "Bant Açma (Band Pull-Apart)",
    nameEn: "Band Pull-Apart",
    category: 'strength',
    description: "Üst sırt aktivasyonu — Bant kollar düz öne, omuz seviyesinde tutulur. İpucu: Omuzlar düşük",
    primaryMuscles: ["chest","back","shoulder"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['resistance_band'],
    locations: ['gym', 'bodyweight_anywhere', 'home'],
    difficulty: 1,
    defaultSets: 3,
    defaultReps: 15,
    defaultRestSeconds: 30,
  },
  {
    slug: 'strength-medball-rotational-throw',
    nameTr: "Rotasyonel Top Atışı",
    nameEn: "Rotational Med-Ball Throw",
    category: 'strength',
    description: "Rotasyonel güç — Yan duruşta sağlık topunu duvara rotasyonla fırlatın. İpucu: Önce kalça döner, sonra gövde",
    primaryMuscles: ["chest","back","shoulder"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['medicine_ball'],
    locations: ['gym', 'bodyweight_anywhere', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 8,
    defaultRestSeconds: 60,
  },
  {
    slug: 'core-deadbug',
    nameTr: "Dead Bug",
    nameEn: "Dead Bug",
    category: 'strength',
    description: "Anti-ekstansiyon core kontrolü — Sırtüstü yatın, kollar tavana, dizler 90°. İpucu: Bel yere yapışık kalsın",
    primaryMuscles: ["core"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'gym', 'bodyweight_anywhere', 'home'],
    difficulty: 1,
    defaultSets: 3,
    defaultReps: 8,
    defaultRestSeconds: 30,
  },
  {
    slug: 'core-pallof-press',
    nameTr: "Pallof Press",
    nameEn: "Pallof Press",
    category: 'strength',
    description: "Anti-rotasyon core stabilitesi — Bantı yan tarafa sabitleyin, göğüs hizasında iki elle tutun. İpucu: Kalça sabit",
    primaryMuscles: ["core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['resistance_band'],
    locations: ['field', 'gym', 'bodyweight_anywhere', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 45,
  },
  {
    slug: 'core-bird-dog',
    nameTr: "Bird Dog",
    nameEn: "Bird Dog",
    category: 'strength',
    description: "Lumbar stabilite — Dört ayak pozisyonu. Karşıt kol-bacak uzatın, 2 sn tutun. İpucu: Kalça yere paralel",
    primaryMuscles: ["core"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'gym', 'bodyweight_anywhere', 'home'],
    difficulty: 1,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 30,
  },
  {
    slug: 'core-hollow-hold',
    nameTr: "Hollow Hold",
    nameEn: "Hollow Body Hold",
    category: 'strength',
    description: "Anti-ekstansiyon dayanıklılık — Sırtüstü yatın, kollar yukarı, bacaklar düz havada. İpucu: Bel açıklığını kapatın",
    primaryMuscles: ["core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'gym', 'bodyweight_anywhere', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 30,
  },
  {
    slug: 'core-mcgill-curlup',
    nameTr: "McGill Curl-Up",
    nameEn: "McGill Curl-Up",
    category: 'strength',
    description: "Bele güvenli abdominal aktivasyon — Sırtüstü yatın, bir bacak bükük diğer düz. İpucu: Bel düzleşmesin",
    primaryMuscles: ["core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'gym', 'bodyweight_anywhere', 'home'],
    difficulty: 1,
    defaultSets: 3,
    defaultReps: 5,
    defaultDurationSeconds: 8,
  },
  {
    slug: 'core-suitcase-carry',
    nameTr: "Bavul Taşıma",
    nameEn: "Suitcase Carry",
    category: 'strength',
    description: "Lateral core dayanıklılık — Tek elinizde ağır bir nesneyle 20m yürüyün, gövde yan eğilmesin. İpucu: Omuzlar yere paralel",
    primaryMuscles: ["core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['medicine_ball'],
    locations: ['field', 'gym', 'bodyweight_anywhere', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultDistanceMeters: 20,
    defaultRestSeconds: 45,
  },
  {
    slug: 'plyo-squat-jump',
    nameTr: "Squat Sıçrama",
    nameEn: "Squat Jump",
    category: 'plyometric',
    description: "Patlayıcı bacak gücü — Squat pozisyonundan dikey olarak patlayıcı sıçrayın. İpucu: İniş diz ayak burnu hizasında",
    primaryMuscles: ["quadriceps","glute","calf"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'gym'],
    difficulty: 1,
    defaultSets: 4,
    defaultReps: 8,
    defaultRestSeconds: 90,
  },
  {
    slug: 'plyo-tuck-jump',
    nameTr: "Tuck Jump",
    nameEn: "Tuck Jump",
    category: 'plyometric',
    description: "Reaktif güç — Yerden patlayıcı sıçrarken dizleri göğsünüze çekin. İpucu: İniş gürültüsüz",
    primaryMuscles: ["quadriceps","glute","calf"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'gym'],
    difficulty: 5,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 90,
  },
  {
    slug: 'plyo-lateral-bound',
    nameTr: "Yan Sıçrama (Skater)",
    nameEn: "Lateral Bound (Skater)",
    category: 'plyometric',
    description: "Lateral güç — Tek bacak üzerinden yana sıçrayıp diğer bacakta inin, dengeyi koruyun. İpucu: İniş dizi içe çevirmesin",
    primaryMuscles: ["quadriceps","glute","calf"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'gym'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 60,
  },
  {
    slug: 'plyo-depth-jump',
    nameTr: "Derinlik Sıçraması",
    nameEn: "Depth Jump",
    category: 'plyometric',
    description: "Reaktif kuvvet (SSC) — 30-40cm yükseklikten ayağa düşüp anında dikey sıçrayın. İpucu: Eğer iniş çok derinleşiyorsa kutu yüksekliğini düşürün",
    primaryMuscles: ["quadriceps","glute","calf"],
    positionsTargeted: [],
    minAge: 18,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'gym'],
    difficulty: 5,
    defaultSets: 4,
    defaultReps: 5,
    defaultRestSeconds: 120,
  },
  {
    slug: 'balance-single-leg-romanian-reach',
    nameTr: "Tek Bacak Reach",
    nameEn: "Single-Leg Reach",
    category: 'strength',
    description: "Ayak bileği/diz/kalça stabilitesi — Bir bacak üstünde durun, etrafa yerleştirilen 5 koniye sırayla uzanın. İpucu: Diz hafif bükük",
    primaryMuscles: ["core","hip"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'gym', 'home'],
    difficulty: 1,
    defaultSets: 3,
    defaultReps: 5,
    defaultRestSeconds: 30,
  },
  {
    slug: 'balance-bosu-squat',
    nameTr: "BOSU Squat",
    nameEn: "BOSU Squat",
    category: 'strength',
    description: "Dengesiz zeminde alt vücut kontrolü — BOSU yastık tarafı yere ters dururken üzerine basın. İpucu: Çekirdek sıkı",
    primaryMuscles: ["core","hip"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['bosu'],
    locations: ['field', 'gym', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 45,
  },
  {
    slug: 'balance-y-balance-test-drill',
    nameTr: "Y-Balance Çalışması",
    nameEn: "Y-Balance Drill",
    category: 'strength',
    description: "Dinamik denge — Bir bacak üstünde durun, diğer ayakla Y şeklinde 3 yöne uzanın (öne, yan-arka, çapraz arka). İpucu: Yavaş kontrollü hareket",
    primaryMuscles: ["core","hip"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'gym', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 5,
    defaultRestSeconds: 30,
  },
  {
    slug: 'balance-airplane',
    nameTr: "Uçak Pozisyonu",
    nameEn: "Airplane Hold",
    category: 'strength',
    description: "Tek bacak stabilite — Tek bacak üstünde durun, gövdeyi 90° öne eğin, kollar yanlara açık (uçak pozisyonu). İpucu: Sırt nötr",
    primaryMuscles: ["core","hip"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'gym', 'home'],
    difficulty: 1,
    defaultSets: 2,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 30,
  },
  {
    slug: 'balance-ankle-hops',
    nameTr: "Ayak Bileği Hop",
    nameEn: "Ankle Hops",
    category: 'strength',
    description: "Ayak bileği sertliği — Düşük seviyede sürekli mini sıçramalar yapın, sadece ayak bileği esner. İpucu: Diz neredeyse düz",
    primaryMuscles: ["core","hip"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'gym', 'home'],
    difficulty: 1,
    defaultSets: 3,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 30,
  },
  {
    slug: 'balance-single-leg-medball-catch',
    nameTr: "Tek Bacak Sağlık Topu Yakalama",
    nameEn: "Single-Leg Med-Ball Catch",
    category: 'strength',
    description: "Reaktif denge — Tek bacak üstünde dururken partnerle topu öne ve yana yakalayın. İpucu: Topu öngörerek hizalanın",
    primaryMuscles: ["core","hip"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['medicine_ball'],
    locations: ['field', 'gym', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 45,
  },
  // --- SPEED & CONDITIONING (sprint + agility + HIIT + SSG + rondo) (football-db merge) ---
  {
    slug: 'sprint-20m-flying',
    nameTr: "20m Uçan Sprint",
    nameEn: "20m Flying Sprint",
    category: 'sprint_agility',
    description: "Maksimum hız — 20m boyunca akselere edip, sonraki 20m'de maksimum hızda tutun (timing 20m). İpucu: Gövde dik",
    primaryMuscles: ["hamstring","glute","calf"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 5,
    defaultDistanceMeters: 20,
    defaultRestSeconds: 180,
  },
  {
    slug: 'sprint-resisted-sled',
    nameTr: "Kızak Çekme Sprint",
    nameEn: "Sled Push Sprint",
    category: 'sprint_agility',
    description: "Akselerasyon kuvveti — Vücut ağırlığının %20-30'u kadar yüklü kızağı 15m boyunca itin/çekin. İpucu: Gövde 45° öne yatık",
    primaryMuscles: ["glute","quadriceps","calf"],
    positionsTargeted: [],
    minAge: 18,
    requiredEquipment: [],
    locations: ['field'],
    difficulty: 5,
    defaultSets: 5,
    defaultDistanceMeters: 15,
    defaultRestSeconds: 120,
  },
  {
    slug: 'sprint-uphill',
    nameTr: "Yokuş Yukarı Sprint",
    nameEn: "Uphill Sprint",
    category: 'sprint_agility',
    description: "Akselerasyon mekaniği — %5-10 eğimli kısa yokuşta 15-20m sprint. İpucu: Yüksek diz",
    primaryMuscles: ["glute","quadriceps","calf"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 8,
    defaultDistanceMeters: 20,
    defaultRestSeconds: 90,
  },
  {
    slug: 'sprint-reactive-start',
    nameTr: "Reaktif Çıkış",
    nameEn: "Reactive Start",
    category: 'sprint_agility',
    description: "Reaksiyon zamanı — Oyuncular sırtüstü/karın üstü/oturarak başlar. İpucu: Hızlı yer-bırakma",
    primaryMuscles: ["glute","quadriceps","calf"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 8,
    defaultDistanceMeters: 10,
    defaultRestSeconds: 60,
  },
  {
    slug: 'decel-stop-and-go',
    nameTr: "Dur-Kalk Deselerasyon",
    nameEn: "Stop-and-Go",
    category: 'sprint_agility',
    description: "Yüklü deselerasyon — 10m sprintten sonra 2m içinde tam durun. İpucu: Düşük gövde, geniş duruş",
    primaryMuscles: ["quadriceps","glute","core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 6,
    defaultDistanceMeters: 20,
    defaultRestSeconds: 90,
  },
  {
    slug: 'decel-180-turn',
    nameTr: "180° Dönüş",
    nameEn: "180° Turn",
    category: 'sprint_agility',
    description: "Tam ters yön değiştirme — 10m sprint, koniyle dön ve geri 10m sprint. İpucu: Dönüş için iç ayağa adım",
    primaryMuscles: ["quadriceps","glute","core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 5,
    defaultDistanceMeters: 20,
    defaultRestSeconds: 90,
  },
  {
    slug: 'agility-t-drill',
    nameTr: "T Drill",
    nameEn: "T-Drill",
    category: 'sprint_agility',
    description: "Çok yönlü çeviklik — T şeklinde 4 koni: A başlangıç, 10m ileri B, ondan 5m sağa C, 10m sola D, B'ye geri, A'ya geri. İpucu: Lateral shuffle'da bacak çaprazlamayın",
    primaryMuscles: ["quadriceps","calf","core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 5,
    defaultRestSeconds: 90,
  },
  {
    slug: 'agility-505',
    nameTr: "5-0-5 Test",
    nameEn: "5-0-5 Drill",
    category: 'sprint_agility',
    description: "180° plant & cut hızı — 10m run-up, sonraki 5m'de hız ölçülür, koniden dönüp aynı 5m geri. İpucu: Plant ayağı dış",
    primaryMuscles: ["quadriceps","calf","core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 8,
    defaultRestSeconds: 90,
  },
  {
    slug: 'agility-zigzag-cones',
    nameTr: "Zigzag Koni Slalomu",
    nameEn: "Zigzag Cone Slalom",
    category: 'sprint_agility',
    description: "Lateral cut — 5-6 koni 2m arayla zigzag yerleştirilir. İpucu: Düşük gövde",
    primaryMuscles: ["quadriceps","calf","core"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 6,
    defaultRestSeconds: 60,
  },
  {
    slug: 'agility-pro-agility',
    nameTr: "Pro Agility (5-10-5)",
    nameEn: "Pro Agility (5-10-5)",
    category: 'sprint_agility',
    description: "Yan plant — 3 koni 5m aralıklı. Orta koniden başlayın, 5m sağa, 10m sola, 5m sağa. İpucu: Düşük çıkış",
    primaryMuscles: ["quadriceps","calf","core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 5,
    defaultRestSeconds: 90,
  },
  {
    slug: 'agility-ladder-icky-shuffle',
    nameTr: "Merdiven Icky Shuffle",
    nameEn: "Ladder Icky Shuffle",
    category: 'sprint_agility',
    description: "Ayak hızı — Merdivene yan giriş: sol-sağ kareye, sağ adım merdiven dışına, ardından sıradaki kareye. İpucu: Merdivene basmayın",
    primaryMuscles: ["quadriceps","calf","core"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['agility_ladder'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 4,
    defaultRestSeconds: 30,
  },
  {
    slug: 'agility-ladder-in-out',
    nameTr: "Merdiven In-Out",
    nameEn: "Ladder In-Out",
    category: 'sprint_agility',
    description: "Hızlı ayak değişimi — Her kareye iki ayak (in-in), sonra dışa iki ayak (out-out). İpucu: Karın merkez sıkı",
    primaryMuscles: ["quadriceps","calf","core"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['agility_ladder'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 4,
    defaultRestSeconds: 30,
  },
  {
    slug: 'agility-hexagon',
    nameTr: "Hexagon Drill",
    nameEn: "Hexagon Drill",
    category: 'sprint_agility',
    description: "Çok yönlü hop — Yere altıgen şekilde 6 koni. Merkezde durup her kenara çift bacak sıçrayıp geri dönün. İpucu: Merkeze her seferinde dön",
    primaryMuscles: ["quadriceps","calf","core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 3,
    defaultRestSeconds: 60,
  },
  {
    slug: 'reactive-mirror-drill',
    nameTr: "Aynalama Çalışması",
    nameEn: "Mirror Drill",
    category: 'sprint_agility',
    description: "Reaktif çeviklik — Çiftler 3m arayla yüz yüze. Bir oyuncu lider, diğeri tüm hareketleri aynalar (sağ/sol/öne/geri). İpucu: Düşük duruş, hızlı reaksiyon",
    primaryMuscles: ["calf","core"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 6,
    defaultDurationSeconds: 20,
    defaultRestSeconds: 40,
  },
  {
    slug: 'reactive-color-cone',
    nameTr: "Renkli Koni Reaksiyon",
    nameEn: "Colored Cone Reaction",
    category: 'sprint_agility',
    description: "Görsel-motor reaksiyon — Oyuncunun çevresine 4 farklı renkli koni yerleştirin. İpucu: Düşük çıkış pozisyonu",
    primaryMuscles: ["calf","core"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 6,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 60,
  },
  {
    slug: 'reactive-ball-drop',
    nameTr: "Top Düşürme Reaksiyonu",
    nameEn: "Drop-Ball Reaction",
    category: 'sprint_agility',
    description: "İlk adım reaksiyonu — Oyuncu 4-5m mesafeden top serbest bırakılma anına bakar. İpucu: Düşük gövde, parmak ucu",
    primaryMuscles: ["calf","core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 1,
    defaultReps: 10,
    defaultRestSeconds: 30,
  },
  {
    slug: 'hiit-30-30',
    nameTr: "30-30 İnterval",
    nameEn: "30-30 Intervals",
    category: 'endurance',
    description: "VO2max — 30 sn yüksek tempolu koşu (~%95 VO2max), 30 sn aktif dinlenme (yürüyüş). İpucu: Set kalitesi düşmesin",
    primaryMuscles: ["cardio","quadriceps"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 12,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 30,
  },
  {
    slug: 'hiit-15-15-football',
    nameTr: "15-15 Futbol İntervali",
    nameEn: "15-15 Football Intervals",
    category: 'endurance',
    description: "Anaerobik kapasite — 15 sn maksimum çaba sprint, 15 sn pasif dinlenme. İpucu: Tam çaba korunmalı",
    primaryMuscles: ["cardio","quadriceps"],
    positionsTargeted: [],
    minAge: 18,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 5,
    defaultSets: 8,
    defaultDurationSeconds: 15,
    defaultRestSeconds: 15,
  },
  {
    slug: 'hiit-yoyo-test-style',
    nameTr: "YoYo Tarzı Mekik",
    nameEn: "YoYo-Style Shuttle",
    category: 'endurance',
    description: "Aerobik dayanıklılık — 20m mesafede gidiş-geliş mekik, başlangıçta yavaş tempo, her dk hız artar. İpucu: Bipler kaçırılmamalı",
    primaryMuscles: ["cardio"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'bodyweight_anywhere'],
    difficulty: 3,
  },
  {
    slug: 'rsa-7x40-shuttle',
    nameTr: "7x40m Mekik (RSA)",
    nameEn: "7x40m Shuttle (RSA)",
    category: 'sprint_agility',
    description: "Tekrarlı sprint kabiliyeti — 20m+20m mekik (40m toplam), her 30 sn'de bir başlat, 7 tekrar. İpucu: Düşüş <%5 olmalı",
    primaryMuscles: ["hamstring","glute","cardio"],
    positionsTargeted: [],
    minAge: 18,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 5,
    defaultSets: 7,
    defaultDistanceMeters: 40,
    defaultRestSeconds: 30,
  },
  {
    slug: 'ssg-rondo-4v1',
    nameTr: "Rondo 4v1",
    nameEn: "Rondo 4v1",
    category: 'technical',
    description: "Top koruma — 8x8m alan. 4 oyuncu kenarda, 1 ortada savunma. İpucu: Vücut açısı yarım",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 3,
    defaultDurationSeconds: 300,
    defaultRestSeconds: 90,
  },
  {
    slug: 'ssg-4v4-end-zones',
    nameTr: "4v4 Bitiş Bölgeli",
    nameEn: "4v4 End-Zones",
    category: 'small_sided_game',
    description: "Penetrasyon pasları — 30x20m saha. Her uçta 2m bitiş bölgesi. İpucu: Üçüncü adam koşusu",
    primaryMuscles: ["cardio"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 3,
    defaultDurationSeconds: 300,
    defaultRestSeconds: 120,
  },
  {
    slug: 'ssg-5v5-conditioning',
    nameTr: "5v5 Kondisyon Maçı",
    nameEn: "5v5 Conditioning Game",
    category: 'small_sided_game',
    description: "Aerobik kondisyon — 30x25m saha, 4 mini kale (kalecisiz). İpucu: Yüksek baskı (gegenpressing)",
    primaryMuscles: ["cardio"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['goal'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 4,
    defaultDurationSeconds: 240,
    defaultRestSeconds: 180,
  },
  {
    slug: 'ssg-possession-7v7-2-jokers',
    nameTr: "7v7 + 2 Joker (Pozisyon)",
    nameEn: "7v7 + 2 Jokers (Possession)",
    category: 'technical',
    description: "Top tutuş — 30x30m, 2 joker oyuncu top sahibine yardım eder (her zaman 9v7). İpucu: Joker üçgen oluşturmaya odaklı",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 3,
    defaultDurationSeconds: 300,
    defaultRestSeconds: 120,
  },
  {
    slug: 'ssg-transition-2v2-to-3v3',
    nameTr: "Geçiş 2v2 → 3v3",
    nameEn: "Transition 2v2 to 3v3",
    category: 'small_sided_game',
    description: "Negatif geçiş — Ortada 2v2 başlar, gol/aut sonrası kenarda bekleyen 3. oyuncu sahaya katılır → 3v3. İpucu: Bilinçli pozisyon değişimi",
    primaryMuscles: ["cardio"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['goal'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 1,
    defaultDurationSeconds: 600,
    defaultRestSeconds: 0,
  },
  {
    slug: 'endurance-tempo-run',
    nameTr: "Tempo Koşu",
    nameEn: "Tempo Run",
    category: 'endurance',
    description: "Aerobik baz — %70-75 kalp atış hızında 20-40 dk sabit tempoda koşu. İpucu: Sohbet edebilir tempo",
    primaryMuscles: ["cardio"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'bodyweight_anywhere'],
    difficulty: 1,
  },
  {
    slug: 'endurance-fartlek',
    nameTr: "Fartlek",
    nameEn: "Fartlek",
    category: 'endurance',
    description: "Karışık aerobik-anaerobik — 20-30 dk koşu sırasında oyuncu/antrenör belirlediği süre/mesafelerde tempoyu rastgele değiştirir. İpucu: Çeşitli yoğunluk değişimleri",
    primaryMuscles: ["cardio"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'bodyweight_anywhere'],
    difficulty: 3,
  },
  {
    slug: 'ssg-4v4-4-goals',
    nameTr: "4v4 / 4 Kale",
    nameEn: "4v4 with 4 Goals",
    category: 'small_sided_game',
    description: "Çabuk yön değiştirme — 25x25m alan, her ekibin saldırabileceği 2 mini kale (toplam 4). İpucu: Topu zayıf savunma kalesine yönlendir",
    primaryMuscles: ["cardio"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['goal'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 3,
    defaultDurationSeconds: 300,
    defaultRestSeconds: 120,
  },
  {
    slug: 'rsa-90s-recovery',
    nameTr: "8x40m + 90sn Toparlanma",
    nameEn: "8x40m + 90sec Recovery",
    category: 'sprint_agility',
    description: "Submaks tekrarlı sprint dayanıklılığı — 8 x 40m sprint, aralarda 90 sn aktif dinlenme.",
    primaryMuscles: ["hamstring","glute","cardio"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 8,
    defaultDistanceMeters: 40,
    defaultRestSeconds: 90,
  },
  {
    slug: 'agility-arrowhead',
    nameTr: "Arrowhead Drill",
    nameEn: "Arrowhead Agility",
    category: 'sprint_agility',
    description: "Asimetrik agility — Ok başı şeklinde 5 koni: başlangıç, 10m ileri, sağa-sola koniler, üst nokta. İpucu: Plant ayak dışı zaten",
    primaryMuscles: ["quadriceps","calf","core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 5,
    defaultSets: 8,
    defaultRestSeconds: 60,
  },
  // --- TECHNICAL (passing + dribbling + shooting + heading + set pieces) (football-db merge) ---
  {
    slug: 'tech-pass-square',
    nameTr: "Kare Pas",
    nameEn: "Square Passing",
    category: 'technical',
    description: "Kısa pas tekniği — 10x10m kare, her köşede 1 oyuncu. İpucu: İç ayakla pas",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 600,
  },
  {
    slug: 'tech-pass-y-pattern',
    nameTr: "Y Pas Çalışması",
    nameEn: "Y Passing Pattern",
    category: 'technical',
    description: "Üçgen oluşturma — 3 koniyle Y şekli kurun. A oyuncu B'ye pas, B C'ye duvar pası, C bitirir. İpucu: Pas sonrası harekete geç",
    primaryMuscles: [],
    positionsTargeted: ['midfielder', 'defender'],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 2,
    defaultDurationSeconds: 300,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-pass-gates',
    nameTr: "Kapı (Gate) Pas",
    nameEn: "Pass Through Gates",
    category: 'technical',
    description: "Pas hassasiyeti — 20x20m alana 10 küçük kapı (2 koni 2m arayla) rastgele yerleştirilir. İpucu: Sürekli baş yukarı",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 3,
    defaultDurationSeconds: 120,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-pass-long-diagonal',
    nameTr: "Uzun Çapraz Pas",
    nameEn: "Long Diagonal Pass",
    category: 'technical',
    description: "Uzun pas hassasiyeti — 30-40m diagonal aralarda iki bölge. İpucu: Vücudu hedefe çevir",
    primaryMuscles: [],
    positionsTargeted: ['defender', 'midfielder'],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-pass-and-move',
    nameTr: "Pas-Koş Sirkülasyonu",
    nameEn: "Pass-and-Move Circuit",
    category: 'technical',
    description: "Pas-hareket bağı — 5 koni dağınık yerleştirilir. Pas at, alıcı koniye koştuğunda yeni alıcı olarak hizalanır. İpucu: Topa açılı koş",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 600,
  },
  {
    slug: 'tech-pass-wall',
    nameTr: "Duvarda Pas",
    nameEn: "Wall Pass Technique",
    category: 'technical',
    description: "Tekrarlı pas teması — Duvar/rebounder karşısında 3-4m mesafeden iç ayakla seri pas. İpucu: Ayak iç hareketi temiz",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 3,
    defaultDurationSeconds: 90,
    defaultRestSeconds: 30,
  },
  {
    slug: 'tech-touch-wall-juggle',
    nameTr: "Duvar Jonglörlük",
    nameEn: "Wall Juggling",
    category: 'technical',
    description: "Hava topu kontrolü — Topu duvara serbest at, hava topunu kontrol al, bir vuruşla geri yolla. İpucu: Vücudu topa hizala",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 3,
    defaultSets: 3,
    defaultDurationSeconds: 60,
    defaultRestSeconds: 30,
  },
  {
    slug: 'tech-first-touch-cone-circle',
    nameTr: "Koni Halkası İlk Dokunuş",
    nameEn: "Cone Circle First Touch",
    category: 'technical',
    description: "Yön verici ilk dokunuş — Çevrede 4-5 oyuncu, ortada 1 alıcı. İpucu: Önce omuz üstünden bak",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 3,
    defaultSets: 3,
    defaultDurationSeconds: 120,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-touch-aerial-volley',
    nameTr: "Volle Kontrol",
    nameEn: "Volley Control",
    category: 'technical',
    description: "Hava top amortisörü — Çiftler. Bir oyuncu eliyle topu havadan atar, diğeri göğüs/uyluk/iç ayakla kontrol edip eline verir. İpucu: Yumuşak çekiliş",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 3,
    defaultSets: 1,
    defaultReps: 10,
  },
  {
    slug: 'tech-dribble-cone-slalom',
    nameTr: "Koni Slalomu",
    nameEn: "Cone Slalom Dribbling",
    category: 'technical',
    description: "Yakın top kontrolü — 8-10 koni 1m arayla bir sıraya. Topu sürerek slalom yapın. İpucu: Top yakın",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 3,
    defaultRestSeconds: 30,
  },
  {
    slug: 'tech-dribble-1v1-channel',
    nameTr: "1v1 Kanal",
    nameEn: "1v1 Channel",
    category: 'technical',
    description: "1v1 dripling — 5x15m kanal. Saldıran top sürerek mini kaleyi geçmeyi dener. İpucu: Hız değişimi",
    primaryMuscles: [],
    positionsTargeted: ['forward'],
    minAge: 10,
    requiredEquipment: ['cones', 'goal'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 6,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-dribble-shadow',
    nameTr: "Gölge Dripling",
    nameEn: "Shadow Dribbling",
    category: 'technical',
    description: "Top kontrolü — Çiftler her biri topla. Lider serbest sürerken takipçi tüm hareketleri taklit eder. İpucu: Baş yukarı",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 6,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 30,
  },
  {
    slug: 'tech-dribble-feints',
    nameTr: "Feint Çalışması",
    nameEn: "Feint Practice",
    category: 'technical',
    description: "Vücut aldatma — Maketlere doğru sürüş, her birinde farklı feint uygulayın (step-over, cruyff turn, scissors, drag-back). İpucu: Tam taahhütle aldatma",
    primaryMuscles: [],
    positionsTargeted: ['forward', 'midfielder'],
    minAge: 14,
    requiredEquipment: ['mannequin'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 4,
    defaultReps: 5,
    defaultRestSeconds: 30,
  },
  {
    slug: 'tech-shoot-cone-finish',
    nameTr: "Koni Bitirici",
    nameEn: "Cone Finishing",
    category: 'technical',
    description: "Şut tekniği — Pas alan oyuncu koniyi atlatıp 16-18m mesafeden şut çeker. İpucu: İlk dokunuş şut hizasına",
    primaryMuscles: ["quadriceps"],
    positionsTargeted: ['forward', 'midfielder'],
    minAge: 10,
    requiredEquipment: ['cones', 'goal'],
    locations: ['field'],
    difficulty: 1,
    defaultSets: 1,
    defaultReps: 8,
  },
  {
    slug: 'tech-shoot-cross-finish',
    nameTr: "Orta + Bitirme",
    nameEn: "Cross + Finish",
    category: 'technical',
    description: "Orta hassasiyeti — Kanat oyuncusu çizgiyi süren topla orta atar. İpucu: Orta tipini değiştir (yer-hava-geri)",
    primaryMuscles: [],
    positionsTargeted: ['forward', 'defender'],
    minAge: 14,
    requiredEquipment: ['cones', 'goal'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 1,
    defaultReps: 20,
  },
  {
    slug: 'tech-shoot-1v1-gk',
    nameTr: "1v1 Kaleci",
    nameEn: "1v1 vs Goalkeeper",
    category: 'technical',
    description: "Bitirme kararı — Forvet 25m mesafeden topu önüne çıkarır, kaleci üzerine çıkar. İpucu: Önce şutu kontrol et",
    primaryMuscles: ["quadriceps"],
    positionsTargeted: ['forward'],
    minAge: 14,
    requiredEquipment: ['goal'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 1,
    defaultReps: 8,
  },
  {
    slug: 'tech-shoot-volley',
    nameTr: "Volle Şut",
    nameEn: "Volley Shooting",
    category: 'technical',
    description: "Tek dokunuş hava şutu — Servis eden oyuncu/antrenör 18m'den hava topu atar. İpucu: Vücut yukarı dönmemeli",
    primaryMuscles: ["quadriceps"],
    positionsTargeted: ['forward'],
    minAge: 14,
    requiredEquipment: ['goal'],
    locations: ['field'],
    difficulty: 5,
    defaultSets: 2,
    defaultReps: 10,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-shoot-rebound-finishing',
    nameTr: "Rebound Bitirici",
    nameEn: "Rebound Finishing",
    category: 'technical',
    description: "Reaktif bitirme — Antrenör topu rebounderden geri sektirir. İpucu: Hızlı reaksiyon",
    primaryMuscles: ["quadriceps"],
    positionsTargeted: ['forward'],
    minAge: 14,
    requiredEquipment: ['goal', 'rebounder'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 1,
    defaultReps: 12,
  },
  {
    slug: 'tech-heading-pairs',
    nameTr: "Çiftli Kafa Çalışması",
    nameEn: "Pairs Heading",
    category: 'technical',
    description: "Kafa tekniği — Çiftler 2m mesafeden topu birbirine kafayla iletir. İpucu: Alından vurun",
    primaryMuscles: ["neck","core"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 3,
    defaultReps: 20,
    defaultRestSeconds: 30,
  },
  {
    slug: 'tech-heading-cross-finish',
    nameTr: "Orta + Kafa Bitiricisi",
    nameEn: "Cross + Header Finish",
    category: 'technical',
    description: "Kafa bitirici — Kanat oyuncusu hava topu orta atar. İpucu: Topu kovala, sıçrama açısı geç",
    primaryMuscles: ["neck","core"],
    positionsTargeted: ['forward'],
    minAge: 14,
    requiredEquipment: ['cones', 'goal'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 2,
    defaultReps: 10,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-heading-defensive',
    nameTr: "Savunma Kafa",
    nameEn: "Defensive Heading",
    category: 'technical',
    description: "Yukarı-uzak kafa — Servis eden hava topu kale önüne atar. İpucu: Önce yukarı, sonra uzağa",
    primaryMuscles: ["neck","core"],
    positionsTargeted: ['defender'],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 2,
    defaultReps: 10,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-rondo-3v1',
    nameTr: "Rondo 3v1",
    nameEn: "Rondo 3v1",
    category: 'technical',
    description: "Pas hızı — 6x6m alan. 3 atak ortada bir savunma. İpucu: Üçgen oluşturun",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 2,
    defaultDurationSeconds: 300,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-juggling-progressive',
    nameTr: "Aşamalı Jonglörlük",
    nameEn: "Progressive Juggling",
    category: 'technical',
    description: "Top hakimiyeti — Sırasıyla yapın: 10 sağ uyluk, 10 sol uyluk, 10 sağ ayak, 10 sol ayak, 10 dönüşümlü ayak, 10 kafa. İpucu: Top dik kalsın",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultSets: 3,
    defaultRestSeconds: 30,
  },
  {
    slug: 'tech-set-piece-corner-routine',
    nameTr: "Korner Rutini",
    nameEn: "Corner Kick Routine",
    category: 'set_piece',
    description: "Hava savunması — Saldıran ekip belirli rotalarla ön/arka direk koşusu yapar. İpucu: Korner servisi farklı tipte (in-out, kısa)",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones', 'goal', 'mannequin'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 1,
    defaultReps: 5,
  },
  {
    slug: 'tech-set-piece-free-kick',
    nameTr: "Serbest Vuruş",
    nameEn: "Free Kick Practice",
    category: 'set_piece',
    description: "Direkt serbest vuruş tekniği — 20-25m mesafeden 5 maket bariyer önünde direkt serbest vuruş. İpucu: Vücudu hedefe çevir",
    primaryMuscles: [],
    positionsTargeted: ['midfielder', 'forward'],
    minAge: 14,
    requiredEquipment: ['goal', 'mannequin'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 1,
    defaultReps: 10,
  },
  {
    slug: 'tech-set-piece-throw-in',
    nameTr: "Taç Atışı",
    nameEn: "Throw-In Practice",
    category: 'set_piece',
    description: "Yasal taç tekniği — Çiftler 10-15m arayla taç atışı yapar. İpucu: Hakem atışını kontrol et",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field'],
    difficulty: 1,
    defaultSets: 1,
    defaultReps: 10,
  },
  {
    slug: 'tech-passing-overload-3v2',
    nameTr: "Pas Üstünlük 3v2",
    nameEn: "3v2 Passing Overload",
    category: 'technical',
    description: "Sayısal üstünlük — 20x15m alan. 3 atak 2 savunma. 1 mini kale. İpucu: Hızlı karar",
    primaryMuscles: [],
    positionsTargeted: ['midfielder', 'forward'],
    minAge: 14,
    requiredEquipment: ['cones', 'goal'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 6,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-1v1-defending',
    nameTr: "1v1 Savunma",
    nameEn: "1v1 Defending",
    category: 'technical',
    description: "Savunma duruşu — 10x15m kanal. Atak top alır, savunma 5m'den çıkar. İpucu: Düşük gövde, yan duruş",
    primaryMuscles: [],
    positionsTargeted: ['defender'],
    minAge: 14,
    requiredEquipment: ['cones', 'goal'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 6,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-passing-combination-third-man',
    nameTr: "Üçüncü Adam Kombinasyonu",
    nameEn: "Third-Man Combination",
    category: 'technical',
    description: "Üçüncü adam paterni — 3 oyuncu A-B-C üçgeninde. A B'ye pas, B C'ye duvar pası, C bağlantı pası A'ya. İpucu: Pas atan koşan üçüncü oyuncu olur",
    primaryMuscles: [],
    positionsTargeted: ['midfielder', 'forward'],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 5,
    defaultSets: 1,
    defaultDurationSeconds: 600,
  },
  {
    slug: 'tech-shooting-finishing-circuit',
    nameTr: "Bitiricilik Sirküiti",
    nameEn: "Finishing Circuit",
    category: 'technical',
    description: "Çoklu bitirme türü — 3 istasyon: (1) tek dokunuş bitirme, (2) çalım sonrası bitirme, (3) volle/half-volley. İpucu: Set bitiminde tempo düşmesin",
    primaryMuscles: ["quadriceps"],
    positionsTargeted: ['forward'],
    minAge: 14,
    requiredEquipment: ['cones', 'goal', 'mannequin'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 3,
    defaultDurationSeconds: 240,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-1v1-attack',
    nameTr: "1v1 Atak",
    nameEn: "1v1 Attack",
    category: 'technical',
    description: "1v1 atak çözüm — Atak 25m'den top sürer, savunma yan kanaldan çıkar. İpucu: Hız değişimi",
    primaryMuscles: [],
    positionsTargeted: ['forward'],
    minAge: 10,
    requiredEquipment: ['cones', 'goal'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 3,
    defaultSets: 1,
    defaultReps: 6,
  },
  {
    slug: 'tech-cross-cutback',
    nameTr: "Geri Pas Ortası (Cutback)",
    nameEn: "Cutback Cross",
    category: 'technical',
    description: "Geri pas çekiliş — Kanat oyuncusu kale çizgisine yaklaşıp geriye doğru cutback atar. İpucu: Düşük yatay pas",
    primaryMuscles: [],
    positionsTargeted: ['forward', 'midfielder'],
    minAge: 14,
    requiredEquipment: ['cones', 'goal'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 2,
    defaultReps: 10,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-passing-circle',
    nameTr: "Çember Pas",
    nameEn: "Circle Passing",
    category: 'technical',
    description: "Pas hızı — 10m yarıçaplı çember. 1 oyuncu ortada, kalanı çevrede. İpucu: Sürekli iletişim",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 480,
  },
  {
    slug: 'tech-1v1-gk-handling',
    nameTr: "Kaleci Top Tutuşu (1v1)",
    nameEn: "GK Handling Drill",
    category: 'technical',
    description: "Yer/hava topu tutuş — Antrenör topları sırayla yer-hava-yan atar. İpucu: W veya S pozisyonu",
    primaryMuscles: ["quadriceps"],
    positionsTargeted: ['goalkeeper'],
    minAge: 14,
    requiredEquipment: ['goal'],
    locations: ['field'],
    difficulty: 1,
    defaultSets: 1,
    defaultReps: 30,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-positional-rondo',
    nameTr: "Pozisyonel Rondo (Bölgeli)",
    nameEn: "Positional Rondo (Zoned)",
    category: 'technical',
    description: "Pozisyon disiplini — 20x15m alan 3 dikey bölgeye ayrılır. 6 atak (her bölgede 2) + 4 savunma (orta bölgede 4). İpucu: Genişlik koru",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 5,
    defaultSets: 3,
    defaultDurationSeconds: 300,
    defaultRestSeconds: 120,
  },
  {
    slug: 'tech-shooting-2v2-finish',
    nameTr: "2v2 + Bitirme",
    nameEn: "2v2 + Finish",
    category: 'technical',
    description: "Maç durumlu bitirme — 20x20m alanda 2 atak 2 savunma. Orta hat üstünden başlatılır. İpucu: İletişim ve ikinci atak koşusu",
    primaryMuscles: ["quadriceps"],
    positionsTargeted: ['forward', 'midfielder'],
    minAge: 14,
    requiredEquipment: ['cones', 'goal'],
    locations: ['field'],
    difficulty: 3,
    defaultSets: 6,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 60,
  },
  {
    slug: 'tech-dribble-with-ball-shadow',
    nameTr: "Topla Shadow Sürüş",
    nameEn: "Shadow Dribble (with Ball)",
    category: 'technical',
    description: "Komut tepkisi — Tüm oyuncular topla serbest sürer. İpucu: Hızlı tepki",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: ['cones'],
    locations: ['field', 'indoor_pitch'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 480,
  },
  // --- RECOVERY & MOBILITY (stretching + foam + breathing + injury prevention) (football-db merge) ---
  {
    slug: 'recovery-cooldown-jog',
    nameTr: "Soğuma Joggu",
    nameEn: "Cool-Down Jog",
    category: 'cooldown',
    description: "Kalp atış hızını düşürme — Antrenman sonrası 5-10 dk düşük tempoda jog. İpucu: Sohbet temposu",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 600,
  },
  {
    slug: 'recovery-walking-stretches',
    nameTr: "Yürüyerek Esnemeler",
    nameEn: "Walking Stretches",
    category: 'cooldown',
    description: "Aktif soğuma — Yürüyerek seri esneme: knee hug, leg cradle, hamstring kick, walking quad stretch, lunge with twist. İpucu: Hareket akıcı, dur-kalk yok",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultSets: 1,
    defaultReps: 10,
  },
  {
    slug: 'recovery-static-hamstring',
    nameTr: "Hamstring Statik Esneme",
    nameEn: "Static Hamstring Stretch",
    category: 'recovery',
    description: "Hamstring esnekliği — Otururken bir bacak düz, diğeri bükük. İpucu: Sırt nötr",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym'],
    difficulty: 1,
    defaultSets: 2,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 15,
  },
  {
    slug: 'recovery-static-quad',
    nameTr: "Quadriceps Statik Esneme",
    nameEn: "Static Quad Stretch",
    category: 'recovery',
    description: "Quadriceps esnekliği — Ayakta bir el desteğiyle ayak bileğinizi kavrayıp kalçaya çekin. İpucu: Diz hizada",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym'],
    difficulty: 1,
    defaultSets: 2,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 15,
  },
  {
    slug: 'recovery-static-calf',
    nameTr: "Baldır Esneme",
    nameEn: "Calf Stretch",
    category: 'recovery',
    description: "Gastrocnemius/soleus esnekliği — Duvara karşı bir adım atılır, arka bacak düz tutulur, topuk yere basılır. İpucu: Topuk yerden kalkmasın",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym'],
    difficulty: 1,
    defaultSets: 2,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 15,
  },
  {
    slug: 'recovery-static-piriformis',
    nameTr: "Piriformis (Kalça) Esneme",
    nameEn: "Piriformis Stretch",
    category: 'recovery',
    description: "Glute/piriformis esnekliği — Sırtüstü yatın. Bir bacağın bilkili karşı dize getirin (4 şekli). İpucu: Bel yere yapışık kalsın",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym'],
    difficulty: 1,
    defaultSets: 2,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 15,
  },
  {
    slug: 'recovery-static-adductor',
    nameTr: "Kasık Esneme (Butterfly)",
    nameEn: "Butterfly Adductor Stretch",
    category: 'recovery',
    description: "Adduktor esnekliği — Otururken ayak tabanlarını birleştirin. İpucu: Sırt nötr",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym'],
    difficulty: 1,
    defaultSets: 2,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 15,
  },
  {
    slug: 'recovery-static-hip-flexor',
    nameTr: "Kalça Fleksörü Esneme",
    nameEn: "Hip Flexor Stretch",
    category: 'recovery',
    description: "İliopsoas/rectus femoris esnekliği — Yarım diz çökme pozisyonu (lunge). İpucu: Kalça üstüne öne eğil, gövde dik",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym'],
    difficulty: 1,
    defaultSets: 2,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 15,
  },
  {
    slug: 'recovery-mobility-cat-cow',
    nameTr: "Kedi-Deve",
    nameEn: "Cat-Cow",
    category: 'recovery',
    description: "Omurga mobilitesi — Dört ayak pozisyonu. Nefes alırken sırtı çukurlaştır (deve), ver verirken kambur (kedi). İpucu: Yavaş ve kontrollü",
    primaryMuscles: ["hip","spine"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym', 'field'],
    difficulty: 1,
    defaultSets: 1,
    defaultReps: 12,
  },
  {
    slug: 'recovery-mobility-thoracic-rotation',
    nameTr: "Torasik Rotasyon",
    nameEn: "Thoracic Rotation",
    category: 'recovery',
    description: "Üst sırt mobilitesi — Dört ayak pozisyonu. Bir el başın arkasında. İpucu: Bel hareketsiz, sadece üst sırt döner",
    primaryMuscles: ["hip","spine"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym', 'field'],
    difficulty: 1,
    defaultSets: 1,
    defaultReps: 10,
  },
  {
    slug: 'recovery-mobility-90-90-hip',
    nameTr: "90/90 Kalça Mobilitesi",
    nameEn: "90/90 Hip Mobility",
    category: 'recovery',
    description: "Kalça iç-dış rotasyon mobilitesi — Otururken her iki bacak 90° büküm: bir bacak önde içe rotasyon, diğeri yanda dış rotasyon. İpucu: Sırt nötr",
    primaryMuscles: ["hip","spine"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym', 'field'],
    difficulty: 3,
    defaultSets: 1,
    defaultReps: 10,
  },
  {
    slug: 'recovery-mobility-ankle-rocker',
    nameTr: "Ayak Bileği Rocker",
    nameEn: "Ankle Rocker",
    category: 'recovery',
    description: "Dorsiflexion mobilitesi — Yarım diz çökme; ön bacak ayağı yere düz. İpucu: Topuk asla kalkmasın",
    primaryMuscles: ["hip","spine"],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym', 'field'],
    difficulty: 1,
    defaultSets: 1,
    defaultReps: 10,
  },
  {
    slug: 'recovery-mobility-glute-bridge-march',
    nameTr: "Köprü Marş",
    nameEn: "Bridge March",
    category: 'recovery',
    description: "Glute aktivasyonu — Köprü pozisyonunda kalçayı yukarı kaldırın. İpucu: Kalça düşmesin",
    primaryMuscles: ["hip","spine"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym', 'field'],
    difficulty: 1,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 30,
  },
  {
    slug: 'recovery-foam-roll-quads',
    nameTr: "Foam Roller Quadriceps",
    nameEn: "Foam Roll Quads",
    category: 'recovery',
    description: "Quadriceps myofascial tetik — Yüzükoyun yatın, foam roller bacaklar altında. İpucu: Hassas noktada 10-20 sn dur",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['gym', 'home'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 90,
  },
  {
    slug: 'recovery-foam-roll-it-band',
    nameTr: "Foam Roller IT Band",
    nameEn: "Foam Roll IT Band",
    category: 'recovery',
    description: "Lateral uyluk gevşetme — Yan yatın, üst bacağı yan tarafa çıkarın, alt bacak roller üzerinde. İpucu: Çok ağrılıysa basıncı azalt",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['gym', 'home'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 90,
  },
  {
    slug: 'recovery-foam-roll-back',
    nameTr: "Foam Roller Üst Sırt",
    nameEn: "Foam Roll Upper Back",
    category: 'recovery',
    description: "Torasik mobilite — Sırtüstü, foam roller üst sırtın altında. İpucu: Bele inmeyin",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['gym', 'home'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 60,
  },
  {
    slug: 'recovery-foam-roll-glutes',
    nameTr: "Foam Roller Glute",
    nameEn: "Foam Roll Glutes",
    category: 'recovery',
    description: "Glute/piriformis gevşetme — Foam roller üzerinde otur, bir ayak diğer dizde.",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['gym', 'home'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 90,
  },
  {
    slug: 'recovery-foam-roll-calves',
    nameTr: "Foam Roller Baldır",
    nameEn: "Foam Roll Calves",
    category: 'recovery',
    description: "Baldır gevşetme — Otururken bir baldır roller üstünde, diğeri üstüne çapraz.",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['gym', 'home'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 60,
  },
  {
    slug: 'injury-prevention-nordic-low-volume',
    nameTr: "Düşük Yoğunluk Nordic",
    nameEn: "Low-Volume Nordic",
    category: 'strength',
    description: "Hamstring eksantrik korumalı doz — Haftada 1-2 kez, antrenman sonu 2 set x 4 tekrar Nordic. İpucu: Kalça düz",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'gym', 'home'],
    difficulty: 3,
    defaultSets: 2,
    defaultReps: 4,
    defaultRestSeconds: 60,
  },
  {
    slug: 'injury-prevention-copenhagen-protocol',
    nameTr: "Copenhagen Protokolü",
    nameEn: "Copenhagen Protocol",
    category: 'strength',
    description: "Adduktor kuvvet — Haftada 2-3 kez Copenhagen adduktor yapın (yan plank pozisyonu, üst bacak desteklendiği için). İpucu: Kontrollü tempo",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'gym', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 60,
  },
  {
    slug: 'injury-prevention-ankle-band',
    nameTr: "Ayak Bileği Bantla 4 Yön",
    nameEn: "Ankle 4-Way Band",
    category: 'strength',
    description: "Ayak bileği stabilite — Bantı ayağa sabitleyip 4 yönde (dorsifleksiyon, plantarfleksiyon, eversiyon, inversiyon) direnç altında çalıştırın. İpucu: Yavaş kontrol",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: ['resistance_band'],
    locations: ['field', 'gym', 'home'],
    difficulty: 1,
    defaultSets: 3,
    defaultReps: 15,
    defaultRestSeconds: 30,
  },
  {
    slug: 'injury-prevention-knee-vmo',
    nameTr: "VMO Step-Up",
    nameEn: "VMO Step-Up",
    category: 'strength',
    description: "VMO aktivasyonu — Düşük basamak (15-20cm) öne, ön ayağı basamağa koy. İpucu: Diz ayak burnu üstünde",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'gym', 'home'],
    difficulty: 3,
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSeconds: 45,
  },
  {
    slug: 'injury-prevention-shoulder-band',
    nameTr: "Omuz Bantla External Rotation",
    nameEn: "Shoulder Band External Rotation",
    category: 'strength',
    description: "Rotator cuff kuvveti — Dirseği gövdeye sabit, bant elinizde. İpucu: Dirsek sabit",
    primaryMuscles: [],
    positionsTargeted: ['goalkeeper'],
    minAge: 14,
    requiredEquipment: ['resistance_band'],
    locations: ['field', 'gym', 'home'],
    difficulty: 1,
    defaultSets: 3,
    defaultReps: 15,
    defaultRestSeconds: 30,
  },
  {
    slug: 'recovery-breathing-box',
    nameTr: "Kutu Nefesi (Box Breathing)",
    nameEn: "Box Breathing",
    category: 'recovery',
    description: "Parasempatik aktivasyon — 4 sn nefes al → 4 sn tut → 4 sn ver → 4 sn tut. İpucu: Burun nefesi tercih",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home'],
    difficulty: 1,
    defaultSets: 1,
    defaultReps: 10,
  },
  {
    slug: 'recovery-breathing-diaphragmatic',
    nameTr: "Diyafram Nefesi",
    nameEn: "Diaphragmatic Breathing",
    category: 'recovery',
    description: "Toparlanma hızlandırma — Sırtüstü yatın, bir el karında. İpucu: Veriş daha uzun",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 300,
  },
  {
    slug: 'recovery-pnf-hamstring-partner',
    nameTr: "PNF Hamstring (Partnerli)",
    nameEn: "PNF Hamstring (Partner)",
    category: 'recovery',
    description: "İleri esneklik kazancı — Sırtüstü yatın, partner bir bacağı yukarı kaldırır. İpucu: Kalça yere yapışık",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym'],
    difficulty: 3,
    defaultSets: 4,
    defaultDurationSeconds: 15,
    defaultRestSeconds: 5,
  },
  {
    slug: 'recovery-walking-cool',
    nameTr: "Yürüyüş Soğuma",
    nameEn: "Walking Cool-Down",
    category: 'cooldown',
    description: "Pasif toparlanma — 5-10 dk düz yürüyüş, sohbet temposu.",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 10,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 600,
  },
  {
    slug: 'recovery-mobility-spiderman-lunge',
    nameTr: "Spiderman Lunge",
    nameEn: "Spiderman Lunge",
    category: 'recovery',
    description: "Kalça açıcılar — Şınav pozisyonundan ayağı dış el yanına derin lunge'a getirin. İpucu: Arka diz uzun",
    primaryMuscles: ["hip","spine"],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym', 'field'],
    difficulty: 1,
    defaultSets: 1,
    defaultReps: 10,
  },
  {
    slug: 'recovery-static-tspine',
    nameTr: "Üst Sırt Esnemesi",
    nameEn: "Thoracic Spine Stretch",
    category: 'recovery',
    description: "Üst sırt esnetme — Eller dirseğe destek, gövdeyi öne eğip kollar uzansın (child's pose).",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['bodyweight_anywhere', 'home', 'gym'],
    difficulty: 1,
    defaultSets: 3,
    defaultDurationSeconds: 30,
    defaultRestSeconds: 15,
  },
  {
    slug: 'recovery-active-recovery-spin',
    nameTr: "Hafif Bisiklet Toparlanma",
    nameEn: "Light Cycling Recovery",
    category: 'cooldown',
    description: "Aktif toparlanma — 10-20 dk hafif tempoda statik bisiklet (ya da düz yolda hafif pedal).",
    primaryMuscles: [],
    positionsTargeted: [],
    minAge: 14,
    requiredEquipment: [],
    locations: ['field', 'indoor_pitch', 'bodyweight_anywhere'],
    difficulty: 1,
    defaultSets: 1,
    defaultDurationSeconds: 1200,
  },
];
